packages/multicast_dns/CHANGELOG.md
packages/multicast_dns/lib/src/native_protocol_client.dart
packages/multicast_dns/pubspec.yaml

Version bump

---

packages/fuchsia_ctl/CHANGELOG.md
packages/fuchsia_ctl/lib/src/ssh_client.dart
packages/fuchsia_ctl/pubspec.yaml
packages/fuchsia_ctl/test/ssh_client_test.dart

Fixes https://github.com/flutter/flutter/issues/40980

Make sure command fails properly

---

packages/gauge/CHANGELOG.md
packages/gauge/lib/commands/base.dart
packages/gauge/lib/commands/ioscpugpu/new.dart
packages/gauge/pubspec.yaml
packages/gauge/test/gauge_general_test.dart

This would fix our device lab failure.
I didn't catch this mitake locally because I already downloaded the
resources...

Fix downloading

---

packages/multicast_dns/lib/src/packet.dart
packages/multicast_dns/test/decode_test.dart

This PR has two adjustments.
1. TXT records consist of a buffer containing one or strings prefixed by a length byte. Lumping the length bytes in with the strings when utf8 decoding will fail when the length byte is >= 128. This PR removes the length byte and joins the strings of a TXT record with newlines.
2. The RFC says that TXT records should be utf8 encoded, but we encounter one that isn't, instead of returning null from the decode, this PR decodes with `allowMalformed: true` so we can get the rest of the query response.

[multicast_dns] Make decode more resiliant against non-utf8 fields

---

packages/gauge/CHANGELOG.md
packages/gauge/README.md
packages/gauge/lib/parser.dart
packages/gauge/pubspec.yaml

This would help debug https://github.com/flutter/flutter/issues/45194

Log raw output lines for debugging

---

packages/palette_generator/README.md

Changed the url in [packages/palette_generator/Readme](https://github.com/flutter/packages/blob/master/packages/palette_generator/README.md)

update example url

---

packages/fuchsia_ctl/lib/src/dev_finder.dart

https://github.com/flutter/flutter/issues/42241

Increase the timeout to find fuchsia devices.

---

packages/fuchsia_ctl/CHANGELOG.md
packages/fuchsia_ctl/bin/main.dart
packages/fuchsia_ctl/lib/src/amber_ctl.dart
packages/fuchsia_ctl/lib/src/package_server.dart
packages/fuchsia_ctl/pubspec.lock
packages/fuchsia_ctl/pubspec.yaml

This is useful to push tiles and tiles_ctl to the device.

[fuchsia] Add support to puch packages from package repo

---

packages/animations/example/lib/container_transition.dart
packages/animations/example/lib/fade_scale_transition.dart
packages/animations/example/lib/fade_through_transition.dart
packages/animations/example/lib/main.dart
packages/animations/example/lib/shared_axis_transition.dart
packages/animations/example/pubspec.yaml
packages/animations/lib/src/open_container.dart
packages/animations/test/open_container_test.dart

Also adds the scrim to the open container transition.
This is a continuation of https://github.com/flutter/packages/pull/63.

[animations] OpenContainer demo and polish

---

packages/animations/example/lib/fade_scale_transition.dart

Reworked the fade transition demo to match the new spec:

[animations] Fade demo rework

---

packages/pigeon/CHANGELOG.md
packages/pigeon/README.md
packages/pigeon/lib/dart_generator.dart
packages/pigeon/lib/objc_generator.dart
packages/pigeon/lib/pigeon_lib.dart
packages/pigeon/pigeons/host2flutter.dart
packages/pigeon/pubspec.yaml
packages/pigeon/run_tests.sh
packages/pigeon/test/dart_generator_test.dart
packages/pigeon/test/objc_generator_test.dart
packages/pigeon/test/pigeon_lib_test.dart

- Added compilation tests until which point we can get e2e working for ios.
- Started generating code for host->flutter calls

[pigeon] added code generator for host->flutter calls for objc

---

packages/animations/test/open_container_test.dart

For https://github.com/flutter/flutter/pull/50979

Temporary fix for test with upcoming breaking change

---

packages/animations/CHANGELOG.md
packages/animations/lib/src/modal.dart
packages/animations/pubspec.yaml

Unfortunately, the analyzer ignore was one line too high.

[animations] Fix analyzer ignore location

---

packages/palette_generator/CHANGELOG.md
packages/palette_generator/lib/palette_generator.dart
packages/palette_generator/pubspec.yaml

Converting to `DiagnosticableMixin` in preparation for deprecating `Diagnosticable`

Diagnosticable => DiagnosticableMixin

---

packages/pigeon/example/README.md
packages/pigeon/lib/dart_generator.dart
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/java_generator.dart
packages/pigeon/lib/objc_generator.dart
packages/pigeon/run_tests.sh
packages/pigeon/test/objc_generator_test.dart

depends on: https://github.com/flutter/packages/pull/112

[pigeon] added the ability for objc handlers to return errors

---

README.md

chore: updating readme with available packages in the repository.

chore: updating readme with available packages

---

.ci/Dockerfile
.cirrus.yml
packages/pigeon/lib/dart_generator.dart
packages/pigeon/lib/objc_generator.dart
packages/pigeon/pigeons/voidflutter.dart
packages/pigeon/pigeons/voidhost.dart
third_party/packages/bsdiff/example/main.dart
third_party/packages/bsdiff/lib/bsdiff.dart

1. updating packages fixed the initial https error
2. installing `gpg-agent` fixed the missing gpg-agent error
3. I moved the installation of clang-format to the Dockerfile, to speed up the `test+format` job
4. I ran `dartfmt` to get the `test+format` job green (I only manually touched `.cirrus.yml` and `.ci/Dockerfile`, the rest of the diffs are from `dartfmt`).
Fixes https://github.com/flutter/flutter/issues/54319.

update dockerfile to fix gpg

---

packages/animations/CHANGELOG.md
packages/animations/example/lib/container_transition.dart
packages/animations/example/lib/fade_scale_transition.dart
packages/animations/example/lib/fade_through_transition.dart
packages/animations/example/lib/main.dart
packages/animations/pubspec.yaml
packages/animations/test/fade_scale_transition_test.dart
packages/animations/test/modal_test.dart

This is required to unblock the Dart SDK roll which contains fixes for this lint

[animations] fix prefer_const_constructors lint

---

customer_testing.bat

This updates the Flutter calls to be called with a `CALL` command instead of calling the command directly in the script. Calling directly results in no subprocess being created in windows, so when the flutter command finishes, the testing script finishes. This has led to only `flutter analyze` being called on windows tests.
Current log from the customer testing repo for example:
```
>> .\customer_testing.bat
|
| C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_customer_testing.flutter_packages.28a73a01-73d7-11ea-a63b-bd60639f7eab\tests>REM This file is used by
|
| C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_customer_testing.flutter_packages.28a73a01-73d7-11ea-a63b-bd60639f7eab\tests>REM https://github.com/flutter/tests/tree/master/registry/flutter_packages.test
| …
```

Fix windows testing script not calling tests

---

packages/animations/lib/src/open_container.dart
packages/palette_generator/example/ios/Flutter/flutter_export_environment.sh

OpenContainer's openBuilder action callback is used to close the container, and the reverse with closedBuilder.

Fixed small typo in documentation for OpenContainer

---

packages/fuchsia_ctl/lib/src/dev_finder.dart

Fixes this post-submit failure: https://github.com/flutter/packages/runs/631248298

Fix formatting to fix post-submit queue

---

packages/animations/example/lib/container_transition.dart
packages/animations/example/lib/fade_through_transition.dart
packages/animations/example/lib/shared_axis_transition.dart
packages/animations/lib/src/modal.dart

Nothing user-facing. All code cleanup for proper analyzer warnings and using deprecated getters

[animations] Remove all TODOs upon Flutter stable release

---

packages/animations/lib/src/open_container.dart

fixing OpenContainer comments

---

packages/animations/test/open_container_test.dart

Migrates test after https://github.com/flutter/flutter/pull/50979 was introduced

[animations] Migrate _getScrimColor to look for ColoredBox

---

packages/palette_generator/CHANGELOG.md
packages/palette_generator/pubspec.yaml

Bumping the version because I forgot to do that in my previous change.

[palette_generator] Bump version before publish

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/ast.dart
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/pigeon_lib.dart
packages/pigeon/pubspec.yaml
packages/pigeon/test/pigeon_lib_test.dart

and improved error handling.
related issue: https://github.com/flutter/flutter/issues/58896

[pigeon] made nested classes that aren't referenced in the apis work

---

.cirrus.yml

Remove CI brew dependencies already packaged in Flutter.

Remove brew dependencies

---

packages/fuchsia_ctl/.gitignore
packages/fuchsia_ctl/README.md
packages/fuchsia_ctl/bin/main.dart
packages/fuchsia_ctl/lib/src/dev_finder.dart
packages/fuchsia_ctl/test/dev_finder_test.dart

Make fuchsia_ctl use device-finder instead of dev_finder.

---

packages/fuchsia_ctl/CHANGELOG.md
packages/fuchsia_ctl/README.md

Update fuchsia_ctl version to 0.0.24.

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/java_generator.dart
packages/pigeon/lib/objc_generator.dart
packages/pigeon/pigeons/list.dart
packages/pigeon/pubspec.yaml
packages/pigeon/run_tests.sh
packages/pigeon/test/java_generator_test.dart
packages/pigeon/test/objc_generator_test.dart

relevant issue: https://github.com/flutter/flutter/issues/61660

[Pigeon] Added support for lists and maps in java and objc targets.

---

packages/xdg_directories/lib/xdg_directories.dart

Stumbled across the XDG directory library, and notice something small. Every little change is one step in the right direction! 😋👍

[xdg_directories] Apply missing test visibility annotation

---

packages/xdg_directories/lib/xdg_directories.dart
packages/xdg_directories/pubspec.yaml
packages/xdg_directories/test/xdg_directories_test.dart

I didn't notice a need to depend on flutter packages when they could be replaced with the more specific libraries. I opted to go for the latest versions, but I'm open to change that if needed. 😊👍

[xdg_directories] Swap flutter dependencies out

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/dart_generator.dart
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/pigeon.dart
packages/pigeon/pigeons/all_datatypes.dart
packages/pigeon/pubspec.yaml
packages/pigeon/run_tests.sh

relevant issue: https://github.com/flutter/flutter/issues/64806

[pigeon] made support of array datatypes more complete

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/dart_generator.dart
packages/pigeon/lib/generator_tools.dart
packages/pigeon/pubspec.yaml
packages/pigeon/run_tests.sh

relevant issue: https://github.com/flutter/flutter/issues/65872

[Pigeon] fixed dart linter problem

---

packages/pigeon/lib/java_generator.dart

Fix: #67586 Set 'code' in a wrapped exception to the exceptions simple name to stop PlatformException asserting.

Fix: #67586 wrapped exception causes assert in PlatformException

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/generator_tools.dart
packages/pigeon/pubspec.yaml

This will incorporate https://github.com/flutter/flutter/issues/67586.

[Pigeon] incremented version to 0.1.12 so we can publish the last commit

---

packages/fuchsia_ctl/CHANGELOG.md
packages/fuchsia_ctl/lib/src/amber_ctl.dart

Bug:
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=61329

Replace amberctl with pkgctl.

---

packages/pigeon/CHANGELOG.md
packages/pigeon/bin/pigeon.dart
packages/pigeon/lib/generator_tools.dart
packages/pigeon/pubspec.yaml

fixes https://github.com/flutter/flutter/issues/68196

pigeon: fixed windows execution by using posix path imports

---

packages/pigeon/CHANGELOG.md
packages/pigeon/bin/pigeon.dart
packages/pigeon/lib/generator_tools.dart
packages/pigeon/pubspec.yaml

fixes https://github.com/flutter/flutter/issues/70355

[pigeon] added dart version annotations until pigeon is migrated to nnbd

---

packages/metrics_center/CHANGELOG.md
packages/metrics_center/lib/src/flutter.dart
packages/metrics_center/pubspec.yaml
packages/metrics_center/test/flutter_test.dart

For now, we also preserve the datastore writing. We'll eventually remove
the datastore writing.

FlutterDestination writes into GCS

---

.github/PULL_REQUEST_TEMPLATE.md

*Replace this paragraph with a description of what this PR is changing or adding, and why.* …

Grammatical mistake on pull request template

---

packages/palette_generator/pubspec.yaml

Aligns with recent template changes.

[palette_generator] Remove Flutter version upper bound

---

packages/xdg_directories/CHANGELOG.md
packages/xdg_directories/pubspec.yaml
packages/xdg_directories/test/xdg_directories_test.dart

Updates all dependencies to stable versions, and updates its own version
to stable.
Replaces `mockito`'s Fake with the new `test` Fake to reduce
dependencies (and since `mockito` doesn't yet have a stable NNBD
release).
*Replace this paragraph with a description of what this PR is changing or adding, and why.*
[Flutter Style Guide]: …

[xdg_directories] Update to stable NNBD release

---

packages/animations/CHANGELOG.md
packages/animations/example/pubspec.yaml
packages/animations/pubspec.yaml

Updates version and dependency versions to stable NNBD releases.
Also removes the legacy CHANGELOG formatting so that it will be displayed better on pub.dev

[animations] Bump version for NNBD stable

---

packages/pigeon/lib/java_generator.dart
packages/pigeon/test/java_generator_test.dart

Made a bunch of minor improvements to the Java generation part of the pigeon. Those should make usage of pigeon from java side a bit more convenient.
Please see commit messages for full list of improvements.

[pigeon] Improve java generation

---

.cirrus.yml

Start using flutter-cirrus gcp project for linux tasks.
Bug: https://github.com/flutter/flutter/issues/77624

Use flutter-cirrus gcp project for linux tasks.

---

.cirrus.yml

Use a test-cluster for tasks that do not require building. This is to
optimize resources and do not share build(high resources) with test(low
resources) tasks. …

Update gke cluster used by this repo.

---

packages/web_benchmarks/pubspec.yaml

Towards unblocking https://github.com/flutter/flutter/pull/79099

Update web_benchmarks to support webkit_inspection_protocol 1.0.0

---

packages/animations/lib/src/open_container.dart

Updated code to match changed criteria for formatting.
Failing post submit: https://cirrus-ci.com/task/6287562093363200

unblock tree after changed format rules

---

packages/pigeon/lib/dart_generator.dart
packages/pigeon/run_tests.sh

changes:
* added ability to specify what class of test you want to run
* added list of available tests
* stages are all refactored into functions
* dart compilation tests run on null-safe and non-null-safe now (in parallel)
* removed `-x` added some print statements
* moved to bash
* made variables all lowercase to avoid collisions …

[pigeon] cleaned up run_test.sh

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/java_generator.dart
packages/pigeon/pigeons/java_double_host_api.dart
packages/pigeon/pubspec.yaml
packages/pigeon/run_tests.sh

fixes https://github.com/flutter/flutter/issues/72240

[pigeon] fixed bug where we can generate duplicate Result interfaces for java

---

packages/extension_google_sign_in_as_googleapis_auth/lib/extension_google_sign_in_as_googleapis_auth.dart

See https://github.com/flutter/flutter/issues/80905

[extension_google_sign_in] Add todo WRT correctly setting AccessToken expire value

---

packages/animations/example/lib/container_transition.dart
packages/animations/example/lib/fade_scale_transition.dart
packages/animations/example/lib/fade_through_transition.dart
packages/animations/example/lib/shared_axis_transition.dart
packages/animations/test/dual_transition_builder_test.dart
packages/animations/test/fade_scale_transition_test.dart
packages/animations/test/fade_through_transition_test.dart
packages/animations/test/modal_test.dart
packages/animations/test/shared_axis_transition_test.dart

See https://github.com/dart-lang/linter/issues/2609

Update imports to match the latest directives_ordering analyzer check

---

.cirrus.yml

- Use a specific version of the plugin tools, in preparation for
publishing an updated version out of flutter/plugins.
- Use templates the same way we do in flutter/plugins for consistency
and ease of maintenance.
- Separate some setup steps into their own script steps for better
inspectability in the UI.
- Enable build tests on `stable` in addition to `master`
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-cha …

Minor adjustments to Cirrus configuration

---

packages/animations/CHANGELOG.md
packages/animations/README.md
packages/animations/pubspec.yaml

Add links to the spec and codelab

Update animations README

---

packages/pigeon/copyright_header.txt
packages/pigeon/lib/dart_generator.dart
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/java_generator.dart
packages/pigeon/lib/objc_generator.dart
packages/pigeon/lib/pigeon_lib.dart
packages/pigeon/run_tests.sh
packages/pigeon/test/dart_generator_test.dart
packages/pigeon/test/java_generator_test.dart
packages/pigeon/test/objc_generator_test.dart
packages/pigeon/test/pigeon_lib_test.dart

fixes: https://github.com/flutter/flutter/issues/84206
This also introduced the concept of a Generator.  This made testing a bit easier in this case but also can provide users of Pigeon greater control over generating code (cc @zhenqiu1101 @xster)
[Discord]: …

[pigeon] added the ability to add a copyright notice to generated files

---

packages/metrics_center/CHANGELOG.md
packages/metrics_center/lib/src/common.dart
packages/metrics_center/lib/src/gcs_lock.dart
packages/metrics_center/lib/src/skiaperf.dart
packages/metrics_center/pubspec.yaml

https://github.com/flutter/flutter/issues/82705

[metric_center] Update packages to null safety

---

packages/cross_file/CHANGELOG.md
packages/cross_file/README.md
packages/cross_file/pubspec.yaml

[cross_file] Update README

---

packages/pigeon/CHANGELOG.md
packages/pigeon/README.md
packages/pigeon/lib/generator_tools.dart
packages/pigeon/pubspec.yaml

[pigeon] updated readme and made version 0.2.2

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/objc_generator.dart
packages/pigeon/platform_tests/ios_unit_tests/ios/RunnerTests/AsyncHandlersTest.m
packages/pigeon/pubspec.yaml

fixes https://github.com/flutter/flutter/issues/84551

[pigeon] fixed error returning errors from async void(void) functions

---

packages/cross_file/lib/src/types/html.dart

This fixes the red tree https://cirrus-ci.com/task/6498654409195520?logs=analyze#L80

[cross_file] sorted imports

---

.cirrus.yml

Issue: https://github.com/flutter/flutter/issues/84667

Update cirrus gcp credentials

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/pigeon_lib.dart
packages/pigeon/pubspec.yaml
packages/pigeon/run_tests.sh
packages/pigeon/test/pigeon_lib_test.dart

fixes https://github.com/flutter/flutter/issues/84848

[pigeon] fixed recursing into class declarations in the front end parser

---

packages/pigeon/.gitignore
packages/pigeon/CHANGELOG.md
packages/pigeon/lib/ast.dart
packages/pigeon/lib/pigeon_lib.dart
packages/pigeon/test/pigeon_lib_test.dart

issue: https://github.com/flutter/flutter/issues/63468

[pigeon] Added a more explicit error if generic fields are used.

---

packages/pigeon/diff_tool.sh

Now that we are not going to check in checked in generated code, this code will help review patches.

[pigeon] added tool to help compare the output from different versions

---

.ci.yaml

Update ci.yaml documentation link

---

.github/workflows/pull_request_label.yml
.github/workflows/release.yml
README.md

Enable auto publish for the repo.
Also adds the release badge to README
Fixes https://github.com/flutter/flutter/issues/85072

[ci] Enable auto publish

---

customer_testing.bat
customer_testing.sh

[animations] Add --no-fatal-infos to customer_testing scripts

---

packages/imitation_game/imitation_tests/smiley/flutter/smiley/lib/main.dart

The migration can't be done yet without breaking stable, so ignore the
warning for now.

[imitation_game] Ignore a new deprecation warning

---

packages/pigeon/lib/pigeon_lib.dart
packages/pigeon/test/pigeon_lib_test.dart

(cleanup that was discussed in a previous PR with @stuartmorgan)

[pigeon] cleanup pigeon lib tests

---

packages/pointer_interceptor/example/lib/src/shim/dart_ui_fake.dart
packages/pointer_interceptor/lib/src/shim/dart_ui_fake.dart

fixes https://github.com/flutter/flutter/issues/87300

[pointer_interceptor] suppressed new linter warnings

---

packages/metrics_center/lib/src/google_benchmark.dart

fixes https://github.com/flutter/flutter/issues/87300

[metrics_center] suppressed new linter warnings

---

packages/pigeon/lib/pigeon_lib.dart
packages/pigeon/test/pigeon_lib_test.dart

issue https://github.com/flutter/flutter/issues/87307

[pigeon] added an error until we support primitive enums

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/java_generator.dart
packages/pigeon/platform_tests/android_unit_tests/android/app/src/test/java/com/example/android_unit_tests/PigeonTest.java
packages/pigeon/test/java_generator_test.dart

fixes https://github.com/flutter/flutter/issues/67588

[pigeon] fixed some NPE for nested types in java

---

.ci.yaml

https://github.com/flutter/flutter/issues/85803

[ci.yaml] Add LUCI config information

---

packages/multicast_dns/CHANGELOG.md
packages/multicast_dns/README.md
packages/multicast_dns/pubspec.yaml

Fix for [#88242](https://github.com/flutter/flutter/issues/88242) multicast_dns README.md broken link for bin dir

[multicast_dns] Fix for #88242 README.md broken link for bin dir

---

packages/pigeon/lib/ast.dart
packages/pigeon/lib/dart_generator.dart
packages/pigeon/lib/java_generator.dart
packages/pigeon/lib/objc_generator.dart
packages/pigeon/test/dart_generator_test.dart
packages/pigeon/test/java_generator_test.dart
packages/pigeon/test/objc_generator_test.dart
packages/pigeon/test/pigeon_lib_test.dart

Refactor PR: Added a helper to remove most of the references to `'void'`.  This came up as a suggestion in a previous PR.

[pigeon] added void TypeDeclaration helper

---

packages/pigeon/lib/pigeon_cl.dart

A fix for https://github.com/flutter/packages/pull/434.
No external bug.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-br …

[Pigeon] Pass on the sdkPath parameter in pigeon_cl.dart.

---

.github/workflows/release.yml

Updates to match the current whitelist; see https://github.com/flutter/flutter/issues/85127#issuecomment-907656818 for context.

Update wait-on-check version

---

packages/flutter_markdown/lib/src/builder.dart
packages/flutter_markdown/lib/src/widget.dart
packages/flutter_markdown/test/text_test.dart

The markdown spec doesn't support soft line breaks, but many, such as GitHub, do, and we should provide that option.
close https://github.com/flutter/flutter/issues/88271 …

Support soft line break.

---

packages/flutter_markdown/CHANGELOG.md
packages/flutter_markdown/pubspec.yaml

Tagging `flutter_markdown` v0.6.6 for release

[flutter_markdown]: Release v0.6.6

---

packages/palette_generator/CHANGELOG.md
packages/palette_generator/lib/palette_generator.dart
packages/palette_generator/pubspec.yaml
packages/palette_generator/test/palette_generator_test.dart

Fixes https://github.com/flutter/flutter/issues/28383

[palette_generator] Add PaletteGenerator.fromByteData

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/java_generator.dart
packages/pigeon/platform_tests/android_unit_tests/android/app/src/test/java/com/example/android_unit_tests/AsyncTest.java
packages/pigeon/pubspec.yaml
packages/pigeon/test/java_generator_test.dart

fixes https://github.com/flutter/flutter/issues/83244

[pigeon] made it so async java handlers can report errors

---

packages/flutter_markdown/lib/src/builder.dart

This prepares for landing https://dart-review.googlesource.com/c/sdk/+/190360 into the analyzer.

Fix pre-existing HintCode.UNNECESSARY_TYPE_CHECK_TRUE

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/objc_generator.dart
packages/pigeon/pubspec.yaml

fixes https://github.com/flutter/flutter/issues/89838#issuecomment-916881259

[pigeon] updated the assert message for incomplete objc protocol implementation

---

packages/extension_google_sign_in_as_googleapis_auth/CHANGELOG.md
packages/extension_google_sign_in_as_googleapis_auth/README.md
packages/extension_google_sign_in_as_googleapis_auth/pubspec.yaml

*Removed the unnecessary triple dots from the code snippets that get copied*
*issue - unnecessary triple dots that gets copied with the snippet*

[extension_google_sign_in_as_googleapis_auth]updated the code snippet

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/java_generator.dart
packages/pigeon/platform_tests/android_unit_tests/android/app/src/test/java/com/example/android_unit_tests/AllDatatypesTest.java
packages/pigeon/platform_tests/android_unit_tests/android/app/src/test/java/com/example/android_unit_tests/PrimitiveTest.java
packages/pigeon/pubspec.yaml
packages/pigeon/test/java_generator_test.dart

fixes https://github.com/flutter/flutter/issues/90268

[pigeon] fixed bug when using integer primitives on java

---

packages/rfw/CHANGELOG.md
packages/rfw/README.md
packages/rfw/run_tests.sh
packages/rfw/test_coverage/.gitignore
packages/rfw/test_coverage/bin/test_coverage.dart
packages/rfw/test_coverage/pubspec.yaml

[rfw] Transition `lcov` from a shell script to Dart

---

packages/pigeon/lib/pigeon_lib.dart
packages/pigeon/pubspec.yaml

We evolve `package:analyzer` and need to update its users as we do this.
https://github.com/flutter/flutter/issues/91639

[pigeon] Update to analyzer 2.4.0 and fix deprecations.

---

customer_testing.sh
packages/rfw/run_tests.sh

[rfw] Update customer_testing.sh for recent rfw changes

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/java_generator.dart
packages/pigeon/platform_tests/android_unit_tests/android/app/src/test/java/com/example/android_unit_tests/EnumTest.java
packages/pigeon/pubspec.yaml
packages/pigeon/run_tests.sh
packages/pigeon/test/java_generator_test.dart

fixes https://github.com/flutter/flutter/issues/88078 …

[pigeon] fixed null support for java enums

---

.github/workflows/mirror.yml

This will allow us to update branch protection to make some branches
readonly and still allow the mirroring bot to mirror changes.
Bug: https://github.com/flutter/flutter/issues/90476 …

Update the token used for mirroring.

---

.github/workflows/mirror.yml

This will now mirror from main to master.
Bug: https://github.com/flutter/flutter/issues/90476 …

Revert order of mirroring.

---

packages/fuchsia_ctl/bin/main.dart
packages/fuchsia_ctl/lib/src/amber_ctl.dart
packages/fuchsia_ctl/lib/src/image_paver.dart
packages/fuchsia_ctl/lib/src/package_server.dart
packages/fuchsia_ctl/pubspec.lock
packages/fuchsia_ctl/pubspec.yaml
packages/fuchsia_ctl/tool/build.sh

A transitive dependency on an old version of `packages` is causing
issues with current versions of Dart. This updates `platform` to pick up
a newer version of `packages`.
Since updating that just that package caused conflicts, which when resolved
minimally caused more conflicts, this just updates all dependencies to current
versions.
Also updates the build script for recent deprecations; dart2native is no longer
present in the current SDK.
Fixes current issues with presubmit in other PRs …

[fuchsia_ctl] Update dependencies

---

packages/multicast_dns/CHANGELOG.md
packages/multicast_dns/lib/multicast_dns.dart
packages/multicast_dns/pubspec.yaml
packages/multicast_dns/test/client_test.dart

Move initialization of `_mDnsAddress` and `_mDnsPort` past checking of `_started`.
Fixes: https://github.com/flutter/flutter/issues/93964 …

[multicast_dns] make MDnsClient.start() idempotent

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/pigeon_lib.dart
packages/pigeon/pubspec.yaml

[pigeon] updated style for implicit return values

---

packages/animations/example/lib/container_transition.dart

No CHANGELOG change: just a linter fix to open the tree …

[animations] fixed new linter problems

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/ast.dart
packages/pigeon/lib/ast_generator.dart
packages/pigeon/lib/pigeon_lib.dart
packages/pigeon/run_tests.sh
packages/pigeon/test/ast_generator_test.dart
packages/pigeon/test/pigeon_lib_test.dart

Added `ast_out` option that prints out the AST to help with debugging.
No version change: NEXT used for minor debugging only feature
[exempt …

[pigeon] added AST generator to help with debugging

---

packages/xdg_directories/CHANGELOG.md
packages/xdg_directories/pubspec.yaml

Adds a platform key to indicate that the package is only intended to
work on Linux. …

[xdg_directories] Mark as Linux-only

---

.github/workflows/scorecards-analysis.yml

Scorecards is expecting a token that is not available on cron
executions and because we are running the workflow on every PR there is
no reason to run it on schedules. …

Remove scorecards scheduled runs.

---

packages/pointer_interceptor/CHANGELOG.md
packages/pointer_interceptor/pubspec.yaml

The change in 0.9.2 requires Flutter 2.10, but the min SDK version
wasn't updated so it would break people who are still on 2.8 (or
earlier).
0.9.2 has been retracted on pub.dev to address that; this will
effectively re-release 0.9.2 with the right constraints as 0.9.3.
_Similar to https://github.com/flutter/plugins/pull/4735_ …

[pointer_interceptor] Update min Flutter version

---

.ci.yaml

https://github.com/flutter/flutter/issues/92300

[ci.yaml] Migrate to Cocoon scheduler

---

.cirrus.yml

https://github.com/flutter/flutter/issues/99283

[cirrus] Refresh GCP service account

---

.cirrus.yml

Updates to Xcode 13, which is now required by Flutter master. The use of 12.x is currently blocking the flutter->packages roller.
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Pa …

[ci] Update Xcode

---

packages/pigeon/CHANGELOG.md
packages/pigeon/README.md
packages/pigeon/lib/ast.dart
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/java_generator.dart
packages/pigeon/lib/objc_generator.dart
packages/pigeon/lib/pigeon_lib.dart
packages/pigeon/pigeons/background_platform_channels.dart
packages/pigeon/platform_tests/ios_unit_tests/ios/Runner.xcodeproj/project.pbxproj
packages/pigeon/pubspec.yaml
packages/pigeon/run_tests.sh
packages/pigeon/test/java_generator_test.dart
packages/pigeon/test/objc_generator_test.dart
packages/pigeon/test/pigeon_lib_test.dart

fixes https://github.com/flutter/flutter/issues/99350 …

[pigeon] implements background platform channels support

---

.cirrus.yml
packages/metrics_center/CHANGELOG.md
packages/metrics_center/analysis_options.yaml
packages/metrics_center/lib/src/skiaperf.dart
packages/metrics_center/pubspec.yaml
packages/metrics_center/test/flutter_test.dart
packages/metrics_center/test/skiaperf_test.dart

Fixes https://github.com/flutter/flutter/issues/100075

[metrics_center] await future in metrics_center

---

packages/go_router/CHANGELOG.md
packages/go_router/lib/go_router.dart
packages/go_router/pubspec.yaml
packages/go_router/test/inherited_go_router_test.dart

inherited_go_router.dart file exported.
[#99800](https://github.com/flutter/flutter/issues/99800) …

[go_router] Export inherited_go_router.dart file

---

packages/go_router/CHANGELOG.md
packages/go_router/lib/src/go_route.dart
packages/go_router/lib/src/go_route_match.dart
packages/go_router/lib/src/go_router_delegate.dart
packages/go_router/pubspec.yaml
packages/go_router/test/go_route_test.dart
packages/go_router/test/go_router_delegate_test.dart
packages/go_router/test/go_router_test.dart

as title
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updat …

[go_router]refactor runtime check to assert

---

packages/go_router_builder/CHANGELOG.md
packages/go_router_builder/README.md
packages/go_router_builder/pubspec.yaml

Closes https://github.com/flutter/flutter/issues/102713

[go_router_builder] Readme fixes

---

.ci.yaml

https://github.com/flutter/flutter/issues/100259

[ci.yaml] Removes explicit caches

---

.ci/scripts/prepare_tool.sh
.cirrus.yml
.github/workflows/release.yml
.gitmodules
packages/flutter_markdown/README.md
script/configs/temp_exclude_excerpt.yaml
third_party/packages/cupertino_icons/README.md

- Rolls the pinned repo tooling to pick up the updated `readme-check`.
- Enables `readme-check` in CI, which I apparently forgot to ever do for this repository.
- Enables the secondary run with `--require-excerpts`, plus an opt-out list for all the current violations, so we can migrate incrementally.
- Fixes the few missing language tags so that the primary `readme-check` passes.
- Adds the submodule with the excerpt tools, and the task that runs excerpting, to allow for adopting excerpting in the future without repo-level changes.
- As in flutter/plugins, cloning the submodule is not required for most use cases, so this should not cause disruption.
Brings flutter/packages in line with the recent flutter/plugins changes.
No version change: Adding language tags in READMEs is too minor to …

[ci] Roll repo tooling and add readme-check

---

.cirrus.yml

This adds the same filtering that flutter/plugins uses to avoid re-running all tests when publishing a package.
Fixes https://github.com/flutter/flutter/issues/102801. …

[ci] Don't run tests for tags

---

packages/go_router_builder/CHANGELOG.md
packages/go_router_builder/example/test/ensure_build_test.dart

Related to https://github.com/flutter/flutter/issues/102799
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[following repository CHANGELOG …

[go_router_builder] fix integration test

---

packages/cross_file/CHANGELOG.md
packages/cross_file/README.md
packages/cross_file/pubspec.yaml
packages/cross_file/test/x_file_html_test.dart
packages/cross_file/test/x_file_io_test.dart

Removed unused Flutter dependencies to the cross_file package. Can now be imported and used from other Dart packages without the need of making it a Flutter package.
From https://github.com/flutter/packages/pull/1664
Fixes https://github.com/flutter/flutter/issues/102934 …

[cross_file] Remove unneeded flutter dependency.

---

packages/pigeon/run_tests.sh

This was breaking with new versions of `dart analyze`.
No version change: Just updating CI script.
No CHANGELOG change: Just updating CI script. …

[pigeon] Updated the analysis steps for dart compilation.

---

script/configs/windows_unit_tests_exceptions.yaml

fix typo xdg_directories

---

.ci.yaml

Starts Windows dart unit tests in presubmit

---

packages/cross_file/CHANGELOG.md
packages/cross_file/lib/src/types/base.dart
packages/cross_file/pubspec.yaml

Fixed lastModified unimplemented error description
Fixes https://github.com/flutter/flutter/issues/103930
[Discord]: …

[cross_file] fixed lastModified unimplemented error description

---

packages/pigeon/CHANGELOG.md
packages/pigeon/README.md
packages/pigeon/lib/cpp_generator.dart
packages/pigeon/lib/dart_generator.dart
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/java_generator.dart
packages/pigeon/lib/objc_generator.dart
packages/pigeon/lib/pigeon_lib.dart
packages/pigeon/pigeons/enum.dart
packages/pigeon/pigeons/enum_args.dart
packages/pigeon/pubspec.yaml
packages/pigeon/run_tests.sh
packages/pigeon/test/cpp_generator_test.dart
packages/pigeon/test/dart_generator_test.dart
packages/pigeon/test/java_generator_test.dart
packages/pigeon/test/objc_generator_test.dart
packages/pigeon/test/pigeon_lib_test.dart

issue: https://github.com/flutter/flutter/issues/87307 …

[pigeon] Implements primitive enums for arguments to HostApis

---

.ci/scripts/prepare_tool.sh

Attempt fix https://github.com/flutter/flutter/issues/105238

Switch master to main in prepare_tool.sh

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
packages/extension_google_sign_in_as_googleapis_auth/CHANGELOG.md
packages/extension_google_sign_in_as_googleapis_auth/README.md
packages/extension_google_sign_in_as_googleapis_auth/pubspec.yaml
packages/flutter_image/CHANGELOG.md
packages/flutter_image/lib/network.dart
packages/flutter_image/pubspec.yaml
packages/flutter_image/test/network_test.dart
packages/pointer_interceptor/CHANGELOG.md
packages/pointer_interceptor/README.md
packages/pointer_interceptor/pubspec.yaml
packages/rfw/CHANGELOG.md
packages/rfw/example/remote/lib/main.dart
packages/rfw/example/wasm/lib/main.dart
packages/rfw/lib/rfw.dart
packages/rfw/pubspec.yaml
third_party/packages/cupertino_icons/CHANGELOG.md
third_party/packages/cupertino_icons/README.md
third_party/packages/cupertino_icons/pubspec.yaml

See: https://github.com/flutter/flutter/issues/105336, this PR is the first half to fix the issue.
This PR also:
~~1. sets the git FETCH_HEAD to main to fix ci, because migrated the repot to main.~~ (fixed by https://github.com/flutter/packages/pull/2200#event-6740294133)
2. migrate other references to the master branch to main. …

[flutter_image][ci] ignore deprecation warning, migrate master references to main.

---

.cirrus.yml

Brings flutter/packages into alignment with flutter/plugins https://github.com/flutter/plugins/pull/5918

[ci] Sync Cirrus task filter with flutter/plugins

---

.ci.yaml

The builder config is fragile when dependencies are not pinned to specific versions. Any upstream changes may cause breakage. We should create a test to validate all .ci.yaml dependencies are pinned. This also requires that we pin specific versions for all dependencies.
https://github.com/flutter/flutter/issues/101712
[CLA]: …

Added versions to all dependencies.

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/generator_tools.dart
packages/pigeon/pubspec.yaml

The changes since 2.4 are almost all deprecations of, and removal of, code that Pigeon doesn't use, so we can support a range for maximal ecosystem compatibility.
Fixes https://github.com/flutter/flutter/issues/105090
[exempt from …

[pigeon] Allow newer versions of analyzer

---

packages/go_router/example/macos/Podfile

Follow up to https://github.com/flutter/packages/pull/2380 to fix the Podspec as well, which I missed in that PR.
Fixes building the example with `master` to unblock the roller.
No CHANGELOG change: Uninteresting change; not worth noting. …

Fix podfile

---

packages/go_router/CHANGELOG.md
packages/go_router/README.md
packages/go_router/pubspec.yaml

Updates the go_router README and adds more detail to the sample. …

[go_router] Update README.md

---

packages/go_router/CHANGELOG.md
packages/go_router/lib/src/redirection.dart
packages/go_router/lib/src/route.dart
packages/go_router/pubspec.yaml
packages/go_router/test/go_router_test.dart

fixes https://github.com/flutter/flutter/issues/101183 …

[go_router] redirect should be processed from top to bottom

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/pigeon_lib.dart
packages/pigeon/pubspec.yaml

We would like to replace these APIs.
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#ver …

[pigeon] Require analyzer 4.4.0, stop using deprecated APIs.

---

packages/go_router_builder/CHANGELOG.md
packages/go_router_builder/lib/src/route_config.dart
packages/go_router_builder/lib/src/type_helpers.dart
packages/go_router_builder/pubspec.yaml

Update the analyzer to 4.4.0 as minimum version and remove the usage of deprecated APIs. …

[go_router_builder]update analyzer to 4.4.0

---

.cirrus.yml

Bug:[#109367](https://github.com/flutter/flutter/issues/109367) …

Updating expiring cirrus key. #109461

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/dart_generator.dart
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/pigeon_lib.dart
packages/pigeon/pubspec.yaml
packages/pigeon/test/dart_generator_test.dart

fixes https://github.com/flutter/flutter/issues/97744
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins …

[pigeon] Deduces the package name for dart test file imports.

---

packages/imitation_game/CHANGELOG.md
packages/imitation_game/bin/imitation_game.dart
packages/imitation_game/pubspec.yaml
packages/imitation_game/run.sh

Migrate imitation game to null safety
Contributes to https://github.com/flutter/flutter/issues/110024
- [ x I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes]. …

[imitation_game] Migrate imitation game to null safety

---

packages/pigeon/test/dart_generator_test.dart

fixes https://github.com/flutter/flutter/issues/110109 …

[pigeon] fixes flake in deduces package name test

---

.cirrus.yml

incorrect legacy naming updated
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version- …

updates ios-custom_package_tests to macOS

---

.cirrus.yml
packages/go_router/CHANGELOG.md
packages/go_router/README.md
packages/go_router/example/README.md
packages/go_router/example/lib/async_redirection.dart
packages/go_router/example/lib/books/main.dart
packages/go_router/example/lib/others/transitions.dart
packages/go_router/example/lib/redirection.dart
packages/go_router/lib/src/builder.dart
packages/go_router/lib/src/delegate.dart
packages/go_router/lib/src/information_provider.dart
packages/go_router/lib/src/matching.dart
packages/go_router/lib/src/parser.dart
packages/go_router/lib/src/redirection.dart
packages/go_router/lib/src/route.dart
packages/go_router/lib/src/route_data.dart
packages/go_router/lib/src/router.dart
packages/go_router/lib/src/typedefs.dart
packages/go_router/pubspec.yaml
packages/go_router/test/go_router_test.dart
packages/go_router/test/parser_test.dart

fixes https://github.com/flutter/flutter/issues/105808
fixes https://github.com/flutter/flutter/issues/99121 …

[go_router] adds async feature and build context to redirect

---

packages/dynamic_layouts/README.md
packages/dynamic_layouts/lib/dynamic_layouts.dart
packages/dynamic_layouts/lib/src/base_grid_layout.dart
packages/dynamic_layouts/lib/src/dynamic_grid.dart
packages/dynamic_layouts/lib/src/wrap_layout.dart
packages/dynamic_layouts/test/base_grid_layout_test.dart
packages/dynamic_layouts/test/dynamic_grid_test.dart
packages/dynamic_layouts/test/wrap_layout_test.dart

Reland "[dynamic_layouts] Add Wrap layout and updates to the README(https://github.com/flutter/packages/commit/5ae3a26d1498aa1e6185ce7a54919879474c4aa7) …

[dynamic_layout] Reland Wrap layout

---

.github/workflows/scorecards-analysis.yml

Revert "Bump ossf/scorecard-action from 1.1.2 to 2.0.0"

---

.github/workflows/scorecards-analysis.yml

This PR fixes:
- Add `id-token:write` to the workflow permissions
- Update the scorecard-action to v2.0.3
Fixes https://github.com/ossf/scorecard-action/issues/900 …

Fix bug in scorecard-action workflow

---

packages/adaptive_scaffold/CHANGELOG.md
packages/adaptive_scaffold/pubspec.yaml

This marks the `adaptive_scaffold` package for publishing.

[adaptive_scaffold] Release `adaptive_scaffold` package

---

.cirrus.yml

Update Cirrus image to most recent macOS and Xcode, released on Sept 12. …

[ci] Update Cirrus to macOS Ventura and Xcode 14

---

packages/go_router/CHANGELOG.md
packages/go_router/lib/src/redirection.dart
packages/go_router/lib/src/route.dart
packages/go_router/pubspec.yaml
packages/go_router/test/go_route_test.dart

Fixes https://github.com/flutter/flutter/issues/111763

Fix an issue where GoRoutes with only a redirect were disallowed.

---

packages/dynamic_layouts/example/lib/main.dart
packages/dynamic_layouts/example/lib/staggered_layout_example.dart
packages/dynamic_layouts/example/test/staggered_example_test.dart

Adds the staggered grid meant for the example application. Not meant to land yet, will rebase when #2550 lands.
Follow up on #2520.
[exempt from …

[dynamic_layouts] Add a staggered grid layout example

---

packages/go_router_builder/CHANGELOG.md
packages/go_router_builder/example/lib/main.dart
packages/go_router_builder/example/pubspec.yaml
packages/go_router_builder/pubspec.yaml

Bumps the example version to unblock ci
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages# …

[go_router_builder] Bumps go_router version in example folder to v5.0.0

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/java_generator.dart
packages/pigeon/pubspec.yaml
packages/pigeon/test/java_generator_test.dart

This PR adds Java method @NonNull annotation for Pigeon. This code was based on the Java generator.
fixed https://github.com/flutter/flutter/issues/111634 …

[pigeon] Adds missing @NonNull annotations to some methods.

---

packages/go_router/CHANGELOG.md
packages/go_router/lib/src/route.dart
packages/go_router/pubspec.yaml

Fixed the missing code examples in [ShellRoute class - go_router library - Dart API](https://pub.dev/documentation/go_router/latest/go_router/ShellRoute-class.html). …

[go_router] Fix ShellRoute documentation

---

.ci/Dockerfile

- Updates the base image to a newer base, to get OS updates.
- Aligns with flutter/plugins in preparation for a future repository merge:
- Removes cruft.
- Adds requirements for some tests that aren't currently run here, but will be post-merge.

[ci] Update Dockerfile

---

packages/go_router/CHANGELOG.md
packages/go_router/example/lib/async_redirection.dart
packages/go_router/example/lib/books/main.dart
packages/go_router/example/lib/shell_route.dart
packages/go_router/pubspec.yaml

https://github.com/flutter/flutter/issues/112485 …

[go_router]CHANGE EXAMPLE Provider, Delegate, Parser to routerConfig

---

packages/flutter_adaptive_scaffold/CHANGELOG.md
packages/flutter_adaptive_scaffold/lib/src/adaptive_scaffold.dart
packages/flutter_adaptive_scaffold/pubspec.yaml
packages/flutter_adaptive_scaffold/test/adaptive_scaffold_test.dart

`AdaptiveScaffold`'s bottom navigation bar now updates itself based on the currently selected index (passed in the `AdaptiveScaffold`) and provides a callback to update the selected index when the `BottomNavigationBar` is tapped.

[flutter_adaptive_scaffold] Call onDestinationSelected in bottom nav.

---

packages/go_router/README.md

- https://github.com/flutter/flutter/issues/113053 …

[go_router] chore(docs): update redirection example in readme

---

packages/go_router/CHANGELOG.md
packages/go_router/lib/src/information_provider.dart
packages/go_router/lib/src/parser.dart
packages/go_router/lib/src/router.dart
packages/go_router/pubspec.yaml
packages/go_router/test/parser_test.dart

fixes https://github.com/flutter/flutter/issues/111348 …

[go_router] removes DebugGoRouteInformation

---

packages/go_router/CHANGELOG.md
packages/go_router/example/lib/named_routes.dart
packages/go_router/example/lib/others/extra_param.dart
packages/go_router/example/lib/path_and_query_parameters.dart

fixes https://github.com/flutter/flutter/issues/110210 …

[go_router] Removes dynamic calls in examples.

---

.cirrus.yml
packages/google_identity_services_web/CHANGELOG.md
packages/google_identity_services_web/example/integration_test/js_interop_gis_id_test.dart
packages/google_identity_services_web/example/pubspec.yaml
packages/google_identity_services_web/example/test_driver/integration_test.dart
packages/google_identity_services_web/example/web/mock-gis.js
packages/google_identity_services_web/lib/src/js_interop/google_accounts_id.dart
packages/google_identity_services_web/lib/src/js_interop/google_accounts_oauth2.dart
packages/google_identity_services_web/pubspec.yaml

This PR adds some tweaks to the JS-interop layer found while using the library to (re)write the `package:google_sign_in_gis_web`.
The main changes are:
* Mark optional arguments as properly optional (and not nullable, as they were now)
* Adds a (somewhat undocumented) `scope` parameter to the `OverridableTokenClientConfig`. It appears here: https://developers.google.com/identity/oauth2/web/guides/use-token-model#ajax, but not in the API reference that was used to initially write this API. …

[gis_web] Properly define optional args. Add scope to config.

---

packages/flutter_adaptive_scaffold/CHANGELOG.md
packages/flutter_adaptive_scaffold/lib/src/breakpoints.dart
packages/flutter_adaptive_scaffold/pubspec.yaml
packages/flutter_adaptive_scaffold/test/adaptive_scaffold_test.dart
packages/flutter_adaptive_scaffold/test/breakpoint_test.dart
packages/flutter_adaptive_scaffold/test/simulated_layout.dart
packages/flutter_adaptive_scaffold/test/test_breakpoints.dart

Adds Fuchsia as a mobile platform per: https://github.com/flutter/flutter/issues/113497. Note that Fuchsia will still be considered a desktop platform per this patch.
@gspencergoog let me know if I misinterpreted what you said in https://github.com/flutter/flutter/issues/113497#issuecomment-1287531535
> I think we probably should move Fuchsia to mobile, if only to keep it consistent with the testing infrastructure …

[flutter_adaptive_scaffold] Fuchsia is mobile.

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/kotlin_generator.dart
packages/pigeon/pubspec.yaml
packages/pigeon/test/kotlin_generator_test.dart

the kotlin code only reply when it catch the error.
this is the java generation code
fixes https://github.com/flutter/flutter/issues/113187
[exempt …

[pigeon] Fix Kotlin generated sync host api error

---

.gitignore

Ignores junk (?) `.uuid` files that seem to have started popping up in my working copy (generated by gradle?):
```console
dit@dit:~/github/packages$ git status
On branch main
Your branch is up to date with 'flutter/main'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
packages/adaptive_scaffold/example/android/.uuid
packages/adaptive_scaffold/example/android/gradle/.uuid
packages/adaptive_scaffold/example/android/gradle/wrapper/.uuid
packages/animations/example/android/.uuid
packages/animations/example/android/gradle/.uuid
packages/animations/example/android/gradle/wrapper/.uuid
packages/dynamic_layouts/example/android/.uuid
packages/dynamic_layouts/example/android/gradle/.uuid
packages/dynamic_layouts/example/android/gradle/wrapper/.uuid …
```

[git] Ignore .uuid files that have started popping up.

---

packages/flutter_markdown/test/html_test.dart

This removes a test from package:flutter_markdown related to preserving HTML entities when parsing. As discussed here: https://github.com/dart-lang/markdown/pull/467#discussion_r1006751654, an upcoming version of package:markdown will no longer preserve the entities (and it's thought that this more closely matches the CommonMark spec).
I'm not certain if I need a changelog entry for this change. It won't be user facing, and we won't need to publish a new version of the package. This will just allow the CI here to continue to pass after the new package:markdown version is published.
- fixes https://github.com/flutter/flutter/issues/114193
If you need help, consider asking for advice on the #hackers-new channel on …

[flutter_markdown] remove a test about preserving HTML entities

---

packages/go_router/CHANGELOG.md
packages/go_router/example/lib/shell_route.dart
packages/go_router/lib/go_router.dart
packages/go_router/lib/src/builder.dart
packages/go_router/lib/src/delegate.dart
packages/go_router/lib/src/misc/inherited_router.dart
packages/go_router/lib/src/router.dart
packages/go_router/lib/src/state.dart
packages/go_router/lib/src/typedefs.dart
packages/go_router/pubspec.yaml
packages/go_router/test/builder_test.dart
packages/go_router/test/go_router_state_test.dart
packages/go_router/test/go_router_test.dart
packages/go_router/test/test_helpers.dart

fixes https://github.com/flutter/flutter/issues/112262
fixes https://github.com/flutter/flutter/issues/113641
This pr makes it easier to use GoRouterState and pave the foundation for relative routing
[pub …

[go_router] Adds GoRouterState to context

---

packages/go_router/CHANGELOG.md
packages/go_router/lib/src/route.dart
packages/go_router/pubspec.yaml

Fixes https://github.com/flutter/flutter/issues/112537 …

[go_router] Remove `path` parameter from `ShellRoute` in the documentation

---

.cirrus.yml

Update the flutter-cirrus key.
[114917](https://github.com/flutter/flutter/issues/114917) …

Update flutter-cirrus key

---

.ci/scripts/build_all_packages_app.sh
.ci/scripts/create_all_packages_app.sh
.ci/scripts/prepare_tool.sh
.cirrus.yml
.github/workflows/release.yml

Picks up rename of the command to create an app that bulids all packages together.
[following …

[ci] Roll repo tool to 0.13.0

---

.ci.yaml
.ci/scripts/build_all_packages_app.sh
.ci/targets/mac_build_all_packages.yaml

Enable `Mac build_all_packages` in luci

---

packages/go_router/CHANGELOG.md
packages/go_router/lib/src/delegate.dart
packages/go_router/lib/src/matching.dart
packages/go_router/lib/src/parser.dart
packages/go_router/lib/src/path_utils.dart
packages/go_router/lib/src/route.dart
packages/go_router/pubspec.yaml
packages/go_router/test/go_router_test.dart

fixes https://github.com/flutter/flutter/issues/115832
fixes https://github.com/flutter/flutter/issues/115962 …

[go_router] fixes pop and push to update urls correctly

---

packages/go_router/CHANGELOG.md
packages/go_router/lib/src/parser.dart
packages/go_router/pubspec.yaml
packages/go_router/test/go_router_test.dart

fixes https://github.com/flutter/flutter/issues/116729 …

[go_router] Fixes crashes when using async redirect.

---

packages/pigeon/platform_tests/test_plugin/example/windows/runner/CMakeLists.txt
packages/pigeon/platform_tests/test_plugin/example/windows/runner/flutter_window.cpp
packages/pigeon/platform_tests/test_plugin/example/windows/runner/main.cpp
packages/pigeon/platform_tests/test_plugin/example/windows/runner/win32_window.cpp
packages/pigeon/platform_tests/test_plugin/example/windows/runner/win32_window.h

Regenerates platform_tests/test_plugin/example/windows using `stable`, since it was created on `master`, where the template uses APIs that aren't available on stable yet. …

[pigeon] Make Windows tests run on stable

---

packages/dynamic_layouts/example/pubspec.yaml
packages/pigeon/platform_tests/ios_unit_tests/pubspec.yaml
packages/web_benchmarks/testing/test_app/pubspec.yaml

This is suppose to fix the flutter->package roller. Copied the solution from https://github.com/flutter/plugins/pull/6807 …

[various] update cupertino_icon to above 1.0.0

---

packages/flutter_markdown/test/header_test.dart
packages/flutter_markdown/test/horizontal_rule_test.dart
packages/flutter_markdown/test/scrollable_test.dart
packages/flutter_markdown/test/style_sheet_test.dart
packages/flutter_markdown/test/text_alignment_test.dart
packages/flutter_markdown/test/text_test.dart
packages/flutter_markdown/test/utils.dart

Make the tests more resilient by not asserting anything about the root of the widget tree, which isn't relevant for the tests and also changing as part of https://github.com/flutter/flutter/pull/116924.
[pub …

[flutter_markdown] Make markdown tests more resilient

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/ast.dart
packages/pigeon/lib/cpp_generator.dart
packages/pigeon/lib/dart_generator.dart
packages/pigeon/lib/generator_tools.dart
packages/pigeon/lib/java_generator.dart
packages/pigeon/lib/kotlin_generator.dart
packages/pigeon/lib/objc_generator.dart
packages/pigeon/lib/pigeon_lib.dart
packages/pigeon/lib/swift_generator.dart
packages/pigeon/pigeons/enum.dart
packages/pigeon/pubspec.yaml
packages/pigeon/test/cpp_generator_test.dart
packages/pigeon/test/dart_generator_test.dart
packages/pigeon/test/java_generator_test.dart
packages/pigeon/test/kotlin_generator_test.dart
packages/pigeon/test/objc_generator_test.dart
packages/pigeon/test/swift_generator_test.dart

Add documentation comment support for Enum members
https://github.com/flutter/flutter/issues/116835 …

[pigeon] Add documentation comment support for Enum members

---

packages/go_router_builder/example/lib/main.dart

Closes https://github.com/flutter/flutter/issues/117381 …

[go_router_builder] Use enum entry's name

---

packages/google_identity_services_web/CHANGELOG.md
packages/google_identity_services_web/README.md
packages/google_identity_services_web/example/integration_test/js_interop_gis_id_test.dart
packages/google_identity_services_web/example/integration_test/js_interop_id_test.dart
packages/google_identity_services_web/example/integration_test/js_interop_oauth_test.dart
packages/google_identity_services_web/example/integration_test/utils.dart
packages/google_identity_services_web/example/lib/main.dart
packages/google_identity_services_web/example/lib/main_oauth.dart
packages/google_identity_services_web/example/web/mock-gis.js
packages/google_identity_services_web/lib/src/js_interop/dom.dart
packages/google_identity_services_web/lib/src/js_interop/google_accounts_id.dart
packages/google_identity_services_web/lib/src/js_interop/google_accounts_oauth2.dart
packages/google_identity_services_web/lib/src/js_interop/shared.dart
packages/google_identity_services_web/pubspec.yaml
packages/google_identity_services_web/test/README.md

This PR:
* Adds `renderButton` API to `id.dart`.
* **Breaking Change:** Makes JS-interop API more `dart2wasm`-friendly.
* Removes external getters for function types
* Introduces an external getter for the whole libraries instead.
* Updates `README.md` with the new way of `import`ing the desired libraries.
* Adds tests to the `oauth2` side of the JS-interop layer. …

[gis_web] Adds id.renderButton JS-interop.

---

.ci.yaml

These tests were added in bringup mode, but never fully enabled.
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#versi …

[ci] Enable Windows build-all

---

packages/camera/camera/CHANGELOG.md
packages/camera/camera/README.md
packages/camera/camera/example/ios/Flutter/AppFrameworkInfo.plist
packages/camera/camera/example/ios/Podfile
packages/camera/camera/example/ios/Runner.xcodeproj/project.pbxproj
packages/camera/camera/example/ios/Runner/Info.plist
packages/camera/camera/pubspec.yaml
packages/camera/camera_avfoundation/CHANGELOG.md
packages/camera/camera_avfoundation/example/ios/Flutter/AppFrameworkInfo.plist
packages/camera/camera_avfoundation/example/ios/Podfile
packages/camera/camera_avfoundation/example/ios/Runner.xcodeproj/project.pbxproj
packages/camera/camera_avfoundation/example/ios/Runner/Info.plist
packages/camera/camera_avfoundation/ios/Classes/CameraPlugin.m
packages/camera/camera_avfoundation/ios/Classes/FLTCam.h
packages/camera/camera_avfoundation/ios/Classes/FLTCam.m
packages/camera/camera_avfoundation/ios/Classes/FLTCam_Test.h
packages/camera/camera_avfoundation/ios/Classes/FLTSavePhotoDelegate.m
packages/camera/camera_avfoundation/ios/camera_avfoundation.podspec
packages/camera/camera_avfoundation/pubspec.yaml

camera part of https://github.com/flutter/flutter/issues/101965.
Built the `camera` and `camera_avfoundation` example projects on Flutter 3.3. and let the tool auto-migrate various Xcode project/Podfile files.
[Discord]: …

[camera] Update minimum Flutter version to 3.3 and iOS 11

---

packages/go_router/CHANGELOG.md
packages/go_router/example/ios/Flutter/AppFrameworkInfo.plist
packages/go_router/example/ios/Podfile
packages/go_router/example/ios/Runner.xcodeproj/project.pbxproj
packages/go_router/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/go_router/example/ios/Runner/Info.plist

Related to https://github.com/flutter/flutter/issues/101965.  Built the example project on Flutter 3.3. and let the tool auto-migrate various Xcode project/Podfile files.  This only touched the example app since go_router is a package, not a plugin.
[Discord]: …

[go_router] Update example app to iOS 11

---

packages/file_selector/file_selector/CHANGELOG.md
packages/file_selector/file_selector/README.md
packages/file_selector/file_selector/example/ios/Runner.xcodeproj/project.pbxproj
packages/file_selector/file_selector/example/ios/Runner.xcworkspace/contents.xcworkspacedata
packages/file_selector/file_selector/pubspec.yaml
packages/file_selector/file_selector_ios/CHANGELOG.md
packages/file_selector/file_selector_ios/example/ios/Runner.xcodeproj/project.pbxproj
packages/file_selector/file_selector_ios/example/ios/RunnerTests/FileSelectorTests.m
packages/file_selector/file_selector_ios/ios/Classes/FFSFileSelectorPlugin.m
packages/file_selector/file_selector_ios/ios/file_selector_ios.podspec
packages/file_selector/file_selector_ios/pubspec.yaml

file_selector part of https://github.com/flutter/flutter/issues/101965.
Built the `file_selector` and `file_selector_ios` example projects on Flutter 3.3. and let the tool auto-migrate various Xcode project/Podfile files. …

[file_selector] Update minimum Flutter version to 3.3 and iOS 11

---

packages/video_player/video_player/CHANGELOG.md
packages/video_player/video_player/README.md
packages/video_player/video_player/example/ios/Flutter/AppFrameworkInfo.plist
packages/video_player/video_player/example/ios/Podfile
packages/video_player/video_player/example/ios/Runner.xcodeproj/project.pbxproj
packages/video_player/video_player/example/ios/Runner/Info.plist
packages/video_player/video_player/pubspec.yaml
packages/video_player/video_player_avfoundation/CHANGELOG.md
packages/video_player/video_player_avfoundation/example/ios/Flutter/AppFrameworkInfo.plist
packages/video_player/video_player_avfoundation/example/ios/Podfile
packages/video_player/video_player_avfoundation/example/ios/Runner.xcodeproj/project.pbxproj
packages/video_player/video_player_avfoundation/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/video_player/video_player_avfoundation/example/ios/Runner/Info.plist
packages/video_player/video_player_avfoundation/ios/video_player_avfoundation.podspec
packages/video_player/video_player_avfoundation/pubspec.yaml

video_player part of https://github.com/flutter/flutter/issues/101965.
Built the `video_player` and `video_player_avfoundation` example projects on Flutter 3.3. and let the tool auto-migrate various Xcode project/Podfile files.
[Discord]: …

[video_player] Update minimum Flutter version to 3.3 and iOS 11

---

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/google_maps_flutter/README.md
packages/google_maps_flutter/google_maps_flutter/example/ios/Flutter/AppFrameworkInfo.plist
packages/google_maps_flutter/google_maps_flutter/example/ios/Podfile
packages/google_maps_flutter/google_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj
packages/google_maps_flutter/google_maps_flutter/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/google_maps_flutter/google_maps_flutter/example/ios/Runner/Info.plist
packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
packages/google_maps_flutter/google_maps_flutter_ios/CHANGELOG.md
packages/google_maps_flutter/google_maps_flutter_ios/example/ios/Flutter/AppFrameworkInfo.plist
packages/google_maps_flutter/google_maps_flutter_ios/example/ios/Podfile
packages/google_maps_flutter/google_maps_flutter_ios/example/ios/Runner.xcodeproj/project.pbxproj
packages/google_maps_flutter/google_maps_flutter_ios/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/google_maps_flutter/google_maps_flutter_ios/example/ios/Runner/Info.plist
packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapController.m
packages/google_maps_flutter/google_maps_flutter_ios/ios/google_maps_flutter_ios.podspec
packages/google_maps_flutter/google_maps_flutter_ios/lib/src/google_maps_flutter_ios.dart
packages/google_maps_flutter/google_maps_flutter_ios/pubspec.yaml

google_maps_flutter part of https://github.com/flutter/flutter/issues/101965.
Built the `google_maps_flutter` and `google_maps_flutter_ios` example projects on Flutter 3.3. and let the tool auto-migrate various Xcode project/Podfile files.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking- …

[google_maps_flutter] Update minimum Flutter version to 3.3 and iOS 11

---

packages/google_sign_in/google_sign_in/CHANGELOG.md
packages/google_sign_in/google_sign_in/README.md
packages/google_sign_in/google_sign_in/example/ios/Flutter/AppFrameworkInfo.plist
packages/google_sign_in/google_sign_in/example/ios/Podfile
packages/google_sign_in/google_sign_in/example/ios/Runner.xcodeproj/project.pbxproj
packages/google_sign_in/google_sign_in/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/google_sign_in/google_sign_in/example/ios/Runner/Info.plist
packages/google_sign_in/google_sign_in/pubspec.yaml
packages/google_sign_in/google_sign_in_ios/CHANGELOG.md
packages/google_sign_in/google_sign_in_ios/example/ios/Flutter/AppFrameworkInfo.plist
packages/google_sign_in/google_sign_in_ios/example/ios/Podfile
packages/google_sign_in/google_sign_in_ios/example/ios/Runner.xcodeproj/project.pbxproj
packages/google_sign_in/google_sign_in_ios/example/ios/Runner/Info.plist
packages/google_sign_in/google_sign_in_ios/ios/google_sign_in_ios.podspec
packages/google_sign_in/google_sign_in_ios/pubspec.yaml

video_player part of https://github.com/flutter/flutter/issues/101965.
Built the `google_sign_in` and `google_sign_in_ios` example projects on Flutter 3.3. and let the tool auto-migrate various Xcode project/Podfile files.
[Discord]: …

[google_sign_in] Update minimum Flutter version to 3.3 and iOS 11

---

packages/local_auth/local_auth/CHANGELOG.md
packages/local_auth/local_auth/README.md
packages/local_auth/local_auth/example/ios/Flutter/AppFrameworkInfo.plist
packages/local_auth/local_auth/example/ios/Podfile
packages/local_auth/local_auth/example/ios/Runner.xcodeproj/project.pbxproj
packages/local_auth/local_auth/example/ios/Runner/Info.plist
packages/local_auth/local_auth/pubspec.yaml
packages/local_auth/local_auth_ios/CHANGELOG.md
packages/local_auth/local_auth_ios/example/ios/Flutter/AppFrameworkInfo.plist
packages/local_auth/local_auth_ios/example/ios/Podfile
packages/local_auth/local_auth_ios/example/ios/Runner.xcodeproj/project.pbxproj
packages/local_auth/local_auth_ios/example/ios/Runner/Info.plist
packages/local_auth/local_auth_ios/example/ios/RunnerTests/FLTLocalAuthPluginTests.m
packages/local_auth/local_auth_ios/ios/Classes/FLTLocalAuthPlugin.m
packages/local_auth/local_auth_ios/ios/local_auth_ios.podspec
packages/local_auth/local_auth_ios/pubspec.yaml

local_auth part of https://github.com/flutter/flutter/issues/101965.
Built the `local_auth` and `local_auth_ios` example projects on Flutter 3.3. and let the tool auto-migrate various Xcode project/Podfile files.
[Discord]: …

[local_auth] Update minimum Flutter version to 3.3 and iOS 11

---

packages/pigeon/README.md

[pigeon] Removed my name from the readme

---

packages/google_maps_flutter/google_maps_flutter/example/android/app/build.gradle
packages/google_maps_flutter/google_maps_flutter/example/android/app/src/debug/AndroidManifest.xml
packages/google_maps_flutter/google_maps_flutter/example/android/app/src/main/AndroidManifest.xml
packages/google_maps_flutter/google_maps_flutter/example/android/build.gradle
packages/google_maps_flutter/google_maps_flutter/example/android/gradle/wrapper/gradle-wrapper.properties

Updates the example android configuration to fix the following issue:
Fixes https://github.com/flutter/flutter/issues/122137
I think this change should be exempt from a version bump since it only affects example configuration, but let me know if I should bump it anyways. …

[google_maps_flutter] Update example android configuration

---

packages/video_player/video_player/CHANGELOG.md
packages/video_player/video_player/lib/video_player.dart
packages/video_player/video_player/pubspec.yaml
packages/video_player/video_player/test/video_player_test.dart
packages/video_player/video_player_android/CHANGELOG.md
packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
packages/video_player/video_player_android/android/src/test/java/io/flutter/plugins/videoplayer/VideoPlayerTest.java
packages/video_player/video_player_android/lib/src/android_video_player.dart
packages/video_player/video_player_android/pubspec.yaml
packages/video_player/video_player_android/test/android_video_player_test.dart

Relands https://github.com/flutter/packages/pull/3266

Reland: [video_player] Passing http headers to file constructor

---

packages/video_player/video_player/lib/video_player.dart
packages/video_player/video_player_android/example/lib/mini_controller.dart
packages/video_player/video_player_avfoundation/example/lib/mini_controller.dart

This PR is part of #3361
This is why this part is created: https://github.com/flutter/packages/pull/3361#issuecomment-1463675104
[exempt from …

[video_player] add missing_enum_constant_in_switch

---

packages/shared_preferences/shared_preferences/test/shared_preferences_test.dart

This fix unblocks https://github.com/flutter/packages/pull/3497 …

[shared_preferences] Changes test class to extend platform rather than implement.

---

customer_testing.bat
customer_testing.sh
script/tool_runner.sh

Remove temporary flags added in https://github.com/flutter/packages/pull/3442 …

remove temporary flag after migration

---

.cirrus.yml

The oldest version of Chromium (84) we were using for benchmarking is [no longer supported by the web engine](https://caniuse.com/mdn-javascript_builtins_intl_segmenter_segmenter), so we need to update to something newer than 87+.
This PR:
* Keeps the former "new" version as the new "old" version of Chromium (to have some sort of "continuity" in the benchmarks)
* Updates the "new" version to match [the one used in `flutter/engine`](https://github.com/flutter/engine/blob/main/lib/web_ui/dev/browser_lock.yaml#L16).
This should allow `web_benchmarks_test CHROMIUM_BUILD:XXX` check to pass, and re-enable merges from master.
Closes: https://github.com/flutter/packages/pull/3611 …

[ci] Update version of Chromium in benchmarks to keep up with engine.

---

packages/webview_flutter/webview_flutter_wkwebview/example/ios/RunnerUITests/FLTWebViewUITests.m

https://github.com/flutter/flutter/issues/124156
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and- …

[webview_flutter_wkwebview] Skip flaky transparency test

---

packages/image_picker/image_picker/CHANGELOG.md
packages/image_picker/image_picker/example/lib/main.dart
packages/image_picker/image_picker/pubspec.yaml

fix a broken link in the example of image_picker.
broken-link: https://pub.dev/packages/image_picker#getting-ready-for-the-web-platform
correct-link: https://pub.dev/packages/image_picker_for_web#limitations-on-the-web-platform
fixes: https://github.com/flutter/flutter/issues/111556
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-brea …

[image_picker] [example] fix broken link for image_picker_for_web in image_picker example

---

packages/shared_preferences/shared_preferences/example/android/build.gradle
packages/shared_preferences/shared_preferences/example/android/gradle/wrapper/gradle-wrapper.properties
packages/shared_preferences/shared_preferences_android/example/android/build.gradle
packages/shared_preferences/shared_preferences_android/example/android/gradle/wrapper/gradle-wrapper.properties

partial take over from https://github.com/flutter/packages/pull/3742
Tools 8.0 is not supported yet see https://github.com/flutter/flutter/issues/125181
https://github.com/flutter/flutter/issues/122213

[shared_preferences] Update gradle/agp in example apps

---

packages/path_provider/path_provider/CHANGELOG.md
packages/path_provider/path_provider/README.md
packages/path_provider/path_provider/example/ios/Flutter/AppFrameworkInfo.plist
packages/path_provider/path_provider/example/ios/Podfile
packages/path_provider/path_provider/example/ios/Runner.xcodeproj/project.pbxproj
packages/path_provider/path_provider/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/path_provider/path_provider/example/ios/Runner/Info.plist
packages/path_provider/path_provider/pubspec.yaml
packages/path_provider/path_provider_foundation/CHANGELOG.md
packages/path_provider/path_provider_foundation/darwin/path_provider_foundation.podspec
packages/path_provider/path_provider_foundation/pubspec.yaml

path_provider part of https://github.com/flutter/flutter/issues/101965.
Built the `path_provider` and `path_provider_foundation` example projects on Flutter 3.7 and let the tool auto-migrate various Xcode project/Podfile files. (These changes don't affect plugin clients, so I used the latest stable instead of 3.3.)
No Flutter version update was necessary, as `path_provider_foundation` already has a minimum of 3.3. …

[path_provider] Update minimum iOS version to 11

---

packages/shared_preferences/shared_preferences/CHANGELOG.md
packages/shared_preferences/shared_preferences/README.md
packages/shared_preferences/shared_preferences/example/ios/Flutter/AppFrameworkInfo.plist
packages/shared_preferences/shared_preferences/example/ios/Podfile
packages/shared_preferences/shared_preferences/example/ios/Runner.xcodeproj/project.pbxproj
packages/shared_preferences/shared_preferences/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/shared_preferences/shared_preferences/example/ios/Runner/Info.plist
packages/shared_preferences/shared_preferences/pubspec.yaml
packages/shared_preferences/shared_preferences_foundation/CHANGELOG.md
packages/shared_preferences/shared_preferences_foundation/darwin/shared_preferences_foundation.podspec
packages/shared_preferences/shared_preferences_foundation/pubspec.yaml

shared_preferences part of https://github.com/flutter/flutter/issues/101965.
Built the `shared_preferences` and `shared_preferences_foundation` example projects on Flutter 3.7 and let the tool auto-migrate various Xcode project/Podfile files. (These changes don't affect plugin clients, so I used the latest stable instead of 3.3.)
No Flutter version update was necessary, as `shared_preferences_foundation` already has a minimum of 3.3.
[breaking change …

[shared_preferences] Update minimum iOS version to 11

---

.github/dependabot.yml

Updates the dependabot configuration with new reviewers and the autosubmit label for the actions workflows. …

Update infra reviewers and add label.

---

packages/url_launcher/url_launcher_android/test/url_launcher_android_test.dart

Fixes `unawaited_futures` lint errors from https://github.com/flutter/packages/pull/4045.
This only updates the tests, so no version bump.
[exempt …

[url_launcher_android] Fix `unawaited_futures` lint errors

---

packages/go_router/CHANGELOG.md
packages/go_router/doc/error-handling.md
packages/go_router/example/README.md
packages/go_router/example/lib/exception_handling.dart
packages/go_router/example/lib/redirection.dart
packages/go_router/example/test/exception_handling_test.dart
packages/go_router/lib/src/configuration.dart
packages/go_router/lib/src/delegate.dart
packages/go_router/lib/src/match.dart
packages/go_router/lib/src/misc/errors.dart
packages/go_router/lib/src/parser.dart
packages/go_router/lib/src/router.dart
packages/go_router/lib/src/state.dart
packages/go_router/pubspec.yaml
packages/go_router/test/exception_handling_test.dart
packages/go_router/test/go_router_test.dart
packages/go_router/test/parser_test.dart
packages/go_router/test/test_helpers.dart

fixes https://github.com/flutter/flutter/issues/108144 …

[go_router] Adds onException to GoRouter constructor.

---

packages/web_benchmarks/CHANGELOG.md
packages/web_benchmarks/testing/test_app/lib/benchmarks/runner.dart

Remove unnecessary non null assertion.
Fixes [#114434](https://github.com/flutter/flutter/issues/114434)
[Discord]: …

[web_benchmark] Fix unnecessary_non_null_assertion for Scrollable.of.

---

script/configs/custom_analysis.yaml

https://github.com/flutter/flutter/issues/127323 has been closed and the packages no longer have the custom analysis files. …

[ci] Remove webview_flutter implementation opt outs for custom analysis

---

packages/go_router_builder/CHANGELOG.md
packages/go_router_builder/example/lib/all_types.dart
packages/go_router_builder/example/lib/shell_route_example.dart
packages/go_router_builder/example/lib/shell_route_with_keys_example.dart
packages/go_router_builder/example/pubspec.yaml
packages/go_router_builder/pubspec.yaml

unblock any go_router or go_router_builder ci
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Pac …

[go_router] Bumps example go_router version and migrate example code

---

AUTHORS

As per title, because of contributing to the following PRs:
[#3702](https://github.com/flutter/packages/pull/3702)
[#3665](https://github.com/flutter/packages/pull/3665)
[#3627](https://github.com/flutter/packages/pull/3627)
[Discord]: …

Adding myself and Michele to AUTHORS

---

packages/go_router/doc/configuration.md

Hey all maintainers,
I was going through the documentation of go_router package. In the [configuration topic](https://pub.dev/documentation/go_router/latest/topics/Configuration-topic.html), I found a sentence that might not be conveying the actual meaning to the reader.
As I faced the same issue, I would like to take the opportunity to improve it and contribute for the same. Is the change valid? Do let me know in case of any improvements
[CLA]: …

[go_router] fix(docs): improve docs and fix typo

---

.cirrus.yml

Update the cirrus key.
[Discord]: …

Update the cirrus key jul-31-2023

---

.ci.yaml

In order to avoid new tasks from not being scheduled we are not going to backfill the autoroller because it can sometimes play transactions out of order causing issues with tasks that are scheduled but not known.
Part of https://github.com/flutter/flutter/issues/127063 …

Update to not backfill the ci.yaml roller task.

---

packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
packages/webview_flutter/webview_flutter_platform_interface/lib/src/platform_webview_controller.dart
packages/webview_flutter/webview_flutter_platform_interface/pubspec.yaml
packages/webview_flutter/webview_flutter_platform_interface/test/platform_webview_controller_test.dart

Platform interface portion of https://github.com/flutter/packages/pull/4472 …

[webview_flutter_platform_interface] Adds support for retrieving user agent

---

packages/google_maps_flutter/google_maps_flutter_android/example/android/secrets.properties
packages/google_maps_flutter/google_maps_flutter_android/example/lib/example_google_map.dart
packages/google_maps_flutter/google_maps_flutter_android/example/pubspec.yaml
packages/google_maps_flutter/google_maps_flutter_android/example/test/example_google_map_test.dart
packages/google_maps_flutter/google_maps_flutter_android/example/test/fake_google_maps_flutter_platform.dart
packages/google_maps_flutter/google_maps_flutter_ios/example/shared/maps_example_dart/lib/example_google_map.dart
packages/google_maps_flutter/google_maps_flutter_ios/example/shared/maps_example_dart/pubspec.yaml
packages/google_maps_flutter/google_maps_flutter_ios/example/shared/maps_example_dart/test/example_google_map_test.dart
packages/google_maps_flutter/google_maps_flutter_ios/example/shared/maps_example_dart/test/fake_google_maps_flutter_platform.dart

Applies the fixes from https://github.com/flutter/packages/pull/4171 to the minimal ExampleGoogleMaps class used in the Android and iOS implementation package examples, as they had the same issue.
Also sets up unit testing of the examples in order to add testing of this fix. The fake is copied directly from the app-facing package, and the unit tests are slightly modified versions of the tests in the app-facing package as well. …

[google_maps_flutter] Fix async handling in examples

---

packages/image_picker/image_picker/example/lib/main.dart

Fixed AlertDialog Height of example in image_picker

---

packages/webview_flutter/webview_flutter/example/integration_test/legacy/webview_flutter_test.dart
packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/legacy/webview_flutter_test.dart

Same fix as https://github.com/flutter/packages/pull/5037 …

[webview_flutter] [webview_flutter_wkwebview]Fix race condition in flaky test

---

packages/shared_preferences/shared_preferences_linux/CHANGELOG.md
packages/shared_preferences/shared_preferences_linux/pubspec.yaml
packages/shared_preferences/shared_preferences_windows/CHANGELOG.md
packages/shared_preferences/shared_preferences_windows/pubspec.yaml

Prep for https://github.com/flutter/flutter/pull/136418.

[shared_preferences] update file version constraints

---

.ci/targets/android_device_tests.yaml

This is to unblock tests in packages timing out because of long queue times in ftl tests. …

Update the ftl hardware version.

---

packages/video_player/video_player/CHANGELOG.md
packages/video_player/video_player/example/lib/main.dart
packages/video_player/video_player/pubspec.yaml

This PR replaces `ButtonBar` with `OverflowBar` in `video_player/example`  in preparation of `ButtonBar` deprecation.
Related to https://github.com/flutter/flutter/issues/127955 …

[video_player] Update example app to replace `ButtonBar` with `OverflowBar`

---

packages/pigeon/CHANGELOG.md
packages/pigeon/lib/generator_tools.dart
packages/pigeon/pubspec.yaml

`analyzer` 6.0 just removes deprecated methods, so we can add support for 6.x without changes, as well as keeping 5.13 compatibility for now to minimize incompatibilities.
Fixes https://github.com/flutter/flutter/issues/138616
[exempt …

[pigeon] Adds `analyzer` 6.x compatibility

---

packages/cross_file/CHANGELOG.md
packages/cross_file/README.md
packages/cross_file/example/assets/hello.txt
packages/cross_file/example/lib/readme_excerpts.dart
packages/cross_file/example/pubspec.yaml
packages/cross_file/example/test/readme_excerpts_test.dart
packages/cross_file/pubspec.yaml
script/configs/temp_exclude_excerpt.yaml

Updates the README to use a compiled excerpt source for its example of instantiating an `XFile`.
Part of [flutter/flutter#102679](https://github.com/flutter/flutter/issues/102679)

[cross_file] adopt code excerpts in README

---

.github/labeler.yml
.github/workflows/pull_request_label.yml

* Manually update labeler to 5.0.0
* Update the labeler yaml format to adhere to requirements in 5.0.0 …

Update labeler to 5.0.0, fix yml format

---

CODEOWNERS

Take back codeownership from @stuartmorgan.  See https://github.com/flutter/packages/pull/3793. …

Swap some iOS package CODEOWNERS

---

.ci.yaml

Part of https://github.com/flutter/flutter/issues/140457.

Add env_variables in ci.yaml

---

README.md

https://github.com/flutter/flutter/issues/140460

Add Flutter CI Status badge to README

---

.ci.yaml

mac_toolchain has been updated to no longer have 2 minute slowdown (https://github.com/flutter/flutter/issues/138109), so unpin to use the latest version. …

Unpin mac_toolchain version

---

packages/rfw/CHANGELOG.md
packages/rfw/lib/src/dart/model.dart
packages/rfw/lib/src/dart/text.dart
packages/rfw/lib/src/flutter/runtime.dart
packages/rfw/pubspec.yaml
packages/rfw/test/model_test.dart
packages/rfw/test/source_locations_test.dart
packages/rfw/test_coverage/bin/test_coverage.dart

Fixes https://github.com/flutter/flutter/issues/141070. …

[rfw] Add support for tracking source locations of BlobNodes.

---

.ci.yaml

Update the android virtual device to use the proto config as the version instead of the integer version. This is more robust from the recipes side as the chromium team is changing names.
Expose the avd_cipd_version flag so developers can update this without touching recipes.
Fixes https://github.com/flutter/flutter/issues/142261 …

Update the emulator versions and expose cipd.

---

.ci.yaml

Add a link the different possible Android virtual device configs

---

CODEOWNERS

So that I get notified for code reviews. I am mainly interested in Swift codegen. 
[CLA]: …

[pigeon]Add hellohuanlin to pigeon iOS for code reviews

---

packages/in_app_purchase/in_app_purchase_storekit/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/in_app_purchase/in_app_purchase_storekit/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme

Fixes https://github.com/flutter/flutter/issues/146254

Fix macos_platform_tests package build times out when built for all packages

---

packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
packages/in_app_purchase/in_app_purchase_android/example/lib/main.dart
packages/in_app_purchase/in_app_purchase_android/lib/src/in_app_purchase_android_platform_addition.dart
packages/in_app_purchase/in_app_purchase_android/pubspec.yaml

Updates the Android example app to use the replacement for the deprecated `getCountryCode`. Also udpates the deprecations method for `getCountryCode` to point to the correct variant of the platform interface method.
Follow-up to https://github.com/flutter/flutter/issues/147230 …

[in_app_purchase] Update country code Android example

---

packages/flutter_image/example/macos/Runner/DebugProfile.entitlements
packages/flutter_image/example/macos/Runner/Release.entitlements
packages/google_sign_in/google_sign_in/example/macos/Runner/DebugProfile.entitlements
packages/google_sign_in/google_sign_in/example/macos/Runner/Release.entitlements
packages/google_sign_in/google_sign_in_ios/example/macos/Runner/DebugProfile.entitlements
packages/google_sign_in/google_sign_in_ios/example/macos/Runner/Release.entitlements
packages/image_picker/image_picker/example/macos/Runner/DebugProfile.entitlements
packages/image_picker/image_picker/example/macos/Runner/Release.entitlements
packages/in_app_purchase/in_app_purchase/example/macos/Runner/DebugProfile.entitlements
packages/in_app_purchase/in_app_purchase/example/macos/Runner/Release.entitlements
packages/in_app_purchase/in_app_purchase_storekit/example/macos/Runner/DebugProfile.entitlements
packages/in_app_purchase/in_app_purchase_storekit/example/macos/Runner/Release.entitlements
packages/path_provider/path_provider/example/macos/Runner/DebugProfile.entitlements
packages/path_provider/path_provider/example/macos/Runner/Release.entitlements
packages/path_provider/path_provider_foundation/example/macos/Runner/DebugProfile.entitlements
packages/path_provider/path_provider_foundation/example/macos/Runner/Release.entitlements
packages/pigeon/platform_tests/alternate_language_test_plugin/example/macos/Runner/DebugProfile.entitlements
packages/pigeon/platform_tests/alternate_language_test_plugin/example/macos/Runner/Release.entitlements
packages/shared_preferences/shared_preferences/example/macos/Runner/DebugProfile.entitlements
packages/shared_preferences/shared_preferences/example/macos/Runner/Release.entitlements
packages/shared_preferences/shared_preferences_foundation/example/macos/Runner/DebugProfile.entitlements
packages/shared_preferences/shared_preferences_foundation/example/macos/Runner/Release.entitlements
packages/url_launcher/url_launcher/example/macos/Runner/DebugProfile.entitlements
packages/url_launcher/url_launcher/example/macos/Runner/Release.entitlements
packages/url_launcher/url_launcher_macos/example/macos/Runner/DebugProfile.entitlements
packages/url_launcher/url_launcher_macos/example/macos/Runner/Release.entitlements
packages/video_player/video_player/example/macos/Runner/DebugProfile.entitlements
packages/video_player/video_player/example/macos/Runner/Release.entitlements
packages/video_player/video_player_avfoundation/example/macos/Runner/DebugProfile.entitlements
packages/video_player/video_player_avfoundation/example/macos/Runner/Release.entitlements

macOS 14 requires sandboxing to be disabled in CI (see https://github.com/flutter/flutter/pull/149618 for details). This is handled via the tool in https://github.com/flutter/flutter/pull/149618, but that commit has yet to land in stable. To allow packages stable tests to run on macOS 14, disable sandboxing directly for macOS example apps.
Verified tests pass on macOS 14:
https://ci.chromium.org/ui/p/flutter/builders/staging.shadow/Mac_arm64%20macos_platform_tests%20stable%20-%20packages/6/infra
https://ci.chromium.org/ui/p/flutter/builders/staging.shadow/Mac_arm64%20custom_package_tests%20stable/3/overview
[Tree …

Disable sandboxing directly for macOS tests

---

CODEOWNERS

Remove CODEOWNER for google_sign_in_ios and image_picker_ios

---

packages/interactive_media_ads/CHANGELOG.md
packages/interactive_media_ads/README.md
packages/interactive_media_ads/pubspec.yaml

Fixes the source of the pub version badge.
Fixes https://github.com/flutter/flutter/issues/150719
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/co …

[interactive_media_ads] Fix README badge image URL

---

.github/labeler.yml
packages/interactive_media_ads/pubspec.yaml

[interactive_media_ads] Adds IMA plugin to labeler yaml

---

packages/shared_preferences/shared_preferences/example/integration_test/shared_preferences_test.dart

[shared_preferences] Add test to enforce mutable lists

---

packages/shared_preferences/shared_preferences/CHANGELOG.md

This PR fixes a typo in the changelog of shared_preferences, relating to what Dart / Flutter version are supported from version 2.3.2 onwards
Fixes https://github.com/flutter/flutter/issues/154177
I'm not sure if this requires a version change. Does it fall under "Updating the minimum Dart or Flutter SDK for all packages when we adjust our test matrix." ? Although, developers probably want to see this corrected on Pub, so that would require a version change? …

[shared_preferences] Fix typo in changelog

---

.ci/targets/macos_platform_tests.yaml

Bump Xcode analyze minimum check version macOS 13 -> macOS 14.
The last bump https://github.com/flutter/packages/pull/7431
Related https://github.com/flutter/plugins/pull/5778 and https://github.com/flutter/flutter/issues/102835 …

[ci] Increase deprecation check minimum to macOS 14

---

packages/flutter_adaptive_scaffold/CHANGELOG.md
packages/flutter_adaptive_scaffold/example/lib/main.dart
packages/flutter_adaptive_scaffold/lib/src/adaptive_layout.dart
packages/flutter_adaptive_scaffold/lib/src/adaptive_scaffold.dart
packages/flutter_adaptive_scaffold/pubspec.yaml
packages/flutter_adaptive_scaffold/test/adaptive_layout_test.dart
packages/flutter_adaptive_scaffold/test/test_breakpoints.dart

[flutter_adaptive_scaffold] Use improved MediaQuery methods

---

packages/quick_actions/quick_actions_android/CHANGELOG.md
packages/quick_actions/quick_actions_android/README.md
packages/quick_actions/quick_actions_android/pubspec.yaml

Builds on https://github.com/flutter/packages/pull/7686 to give more context about the issue I solved in https://github.com/flutter/flutter/issues/152883 and hopefully leave better breadcrumbs for developers that find themselves wanting to use a launcher activity and the `quick_actions_android` plugin.
Fixes https://github.com/flutter/flutter/issues/152883.
[linked to at least one issue that this …

[quick_actions_android] Update instructions for using a launcher activity with more breadcrumbs

---

packages/flutter_plugin_android_lifecycle/example/android/app/build.gradle
packages/flutter_plugin_android_lifecycle/example/android/build.gradle
packages/flutter_plugin_android_lifecycle/example/android/settings.gradle

Updated applying gradle plugins to usage of declarative blocks. Intending on updating all android example apps under packages. Did one as a proof of concept before doing more.
Fixes partially [#152656](https://github.com/flutter/flutter/issues/152656) …

[WIP] Updated applying gradle plugin for flutter_plugin_android_lifecycles

---

packages/webview_flutter/webview_flutter/CHANGELOG.md
packages/webview_flutter/webview_flutter/README.md
packages/webview_flutter/webview_flutter/example/pubspec.yaml
packages/webview_flutter/webview_flutter/pubspec.yaml

`webview_flutter_android` now requires API 21+ from https://github.com/flutter/packages/pull/7801. This bumps the `webview_flutter_android` version and updates the readme in the app-facing package.
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/ …

[webview_flutter] Updates minimum supported `webview_flutter_android` from 3.16.0 to 4.0.0

---

.github/labeler.yml

Adds autolabel rules for the new packages.

[ci] Add vector_graphics and flutter_svg to autolabeler

---

.github/dependabot.yml

The dependabot version bumps are set up to ignore minor and patch "testing" dependencies bumps.  Add Kotlin mocking library [io.mockk:mockk:](https://mockk.io/) to that list.  Example where the patch was bumped https://github.com/flutter/packages/pull/7866
This isn't particularly a noisy dependency, but I noticed it when working on https://github.com/flutter/packages/pull/8048.
Also delete `/packages/image_picker/image_picker/android` since that path doesn't exist. …

Ignore dependabot minor and patch updates of Kotlin mocking library

---

packages/flutter_image/example/.gitignore
packages/local_auth/local_auth_darwin/example/.gitignore
packages/pigeon/example/app/.gitignore
packages/pointer_interceptor/pointer_interceptor_ios/example/.gitignore
packages/shared_preferences/shared_preferences_foundation/example/.gitignore
packages/two_dimensional_scrollables/example/.gitignore

Migrated by running:
```
dart run script/tool/bin/flutter_plugin_tools.dart build-examples --ios --swift-package-manager
dart run script/tool/bin/flutter_plugin_tools.dart build-examples --macos --swift-package-manager
```
No test changes as this is a configuration change. I will get a test exemption.
Part of https://github.com/flutter/flutter/issues/159173
[Discord]: …

[various] Update example apps' .gitignore

---

packages/pigeon/example/app/ios/Flutter/AppFrameworkInfo.plist
packages/pigeon/example/app/ios/Podfile
packages/pigeon/example/app/ios/Runner.xcodeproj/project.pbxproj
packages/pigeon/example/app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/pigeon/example/app/ios/Runner.xcworkspace/contents.xcworkspacedata
packages/pigeon/example/app/macos/Runner.xcodeproj/project.pbxproj
packages/pigeon/example/app/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme

This migrates Pigeon's example app to have Swift Package Manager integration. This raises the example apps' Flutter SDK requirement to 3.24.0 or higher.
This also checks-in CocoaPods integration stuff that was missing.
I will get a text exemption for this change.
The example apps were migrated using the following commands:
```
dart run script/tool/bin/flutter_plugin_tools.dart build-examples --ios --swift-package-manager
dart run script/tool/bin/flutter_plugin_tools.dart build-examples --macos --swift-package-manager
```
Part of: https://github.com/flutter/flutter/issues/159173 …

[pigeon] Add Swift Package Manager integration to example app

---

packages/google_sign_in/google_sign_in/example/ios/Runner.xcodeproj/project.pbxproj
packages/google_sign_in/google_sign_in/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/google_sign_in/google_sign_in/example/macos/Runner.xcodeproj/project.pbxproj
packages/google_sign_in/google_sign_in/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/google_sign_in/google_sign_in_ios/example/ios/Runner.xcodeproj/project.pbxproj
packages/google_sign_in/google_sign_in_ios/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/google_sign_in/google_sign_in_ios/example/macos/Runner.xcodeproj/project.pbxproj
packages/google_sign_in/google_sign_in_ios/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme

This migrates the following plugins' example apps to have Swift Package Manager integration:
1. google_sign_in
2. google_sign_in_ios
This also checks-in CocoaPods integration stuff that was missing.
This raises the example apps' Flutter SDK requirement to 3.24.0 or higher.
I will get a text exemption for this change.
The example apps were migrated using the following commands:
```
dart run script/tool/bin/flutter_plugin_tools.dart build-examples --ios --swift-package-manager
dart run script/tool/bin/flutter_plugin_tools.dart build-examples --macos --swift-package-manager
```
Completes: https://github.com/flutter/flutter/issues/159173 …

[various] Add Swift Package Manager integration to Google sign in example apps

---

packages/go_router/CHANGELOG.md
packages/go_router/README.md
packages/go_router/pubspec.yaml

[go_router] Updates readme to reflect current status

---

packages/shared_preferences/shared_preferences/CHANGELOG.md
packages/shared_preferences/shared_preferences/example/integration_test/shared_preferences_migration_util_test.dart
packages/shared_preferences/shared_preferences/example/lib/main.dart
packages/shared_preferences/shared_preferences/lib/shared_preferences.dart
packages/shared_preferences/shared_preferences/lib/util/legacy_to_async_migration_util.dart
packages/shared_preferences/shared_preferences/pubspec.yaml

fixes https://github.com/flutter/flutter/issues/162381

[shared_preferences] Exposed SharedPreferencesOptions.

---

packages/local_auth/local_auth_darwin/darwin/Tests/FLALocalAuthPluginTests.swift

Follow up to a review comment I missed https://github.com/flutter/packages/pull/8348/files#r1917486689.

[local_auth_darwin] Fix test name for clarity

---

packages/camera/camera_android_camerax/pubspec.yaml
packages/google_sign_in/google_sign_in/pubspec.yaml
packages/google_sign_in/google_sign_in_android/pubspec.yaml
packages/google_sign_in/google_sign_in_ios/pubspec.yaml
packages/in_app_purchase/in_app_purchase/pubspec.yaml
packages/local_auth/local_auth/pubspec.yaml
packages/path_provider/path_provider/pubspec.yaml
packages/path_provider/path_provider_android/pubspec.yaml
packages/quick_actions/quick_actions/pubspec.yaml
packages/quick_actions/quick_actions_android/pubspec.yaml
packages/quick_actions/quick_actions_ios/pubspec.yaml
packages/shared_preferences/shared_preferences/pubspec.yaml

Many of our plugins have `dev_dependencies` on `integration_test` at the plugin level, for some reason. Integration tests run in the example app, not the plugin, so only the example app should need the dependency.
In practice it shouldn't matter since it's a dev dependency, but it's best to be accurate about our requirements.
[Discord]: …

[various] Remove plugin-level `integration_test` dependencies

---

.github/dependabot.yml

https://github.com/flutter/packages/pull/8710#issuecomment-2683188854
Default to dependabot to ignore only patch versions for test dependencies and com.android.tools.build:gradle, and update major and minor. We can revert for any that get noisy.
The minor/patch ignore has been around awhile: https://github.com/flutter/packages/pull/2832/files#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R120-R121
[CLA]: …

Dependabot to update major and minor versions of test dependencies, ignore patch

---

packages/video_player/video_player_android/CHANGELOG.md
packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/texture/TextureVideoPlayer.java
packages/video_player/video_player_android/android/src/test/java/io/flutter/plugins/videoplayer/TextureVideoPlayerTest.java
packages/video_player/video_player_android/pubspec.yaml

Fixes https://github.com/flutter/flutter/issues/164689

[video_player_android] Provide the current surface to the new ExoPlayer in TextureVideoPlayer.onSurfaceAvailable

---

packages/shared_preferences/shared_preferences_android/example/android/app/build.gradle
packages/shared_preferences/shared_preferences_android/example/android/gradle/wrapper/gradle-wrapper.properties
packages/shared_preferences/shared_preferences_android/example/android/settings.gradle

replacement for https://github.com/flutter/packages/pull/8957
Changelog not required https://github.com/flutter/packages/pull/9062 as an example.

[shared_preferences] Update AGP to 8.9.1

---

packages/video_player/video_player_web/example/integration_test/video_player_web_test.dart

Replaces `video_player_web` integration test usage of the legacy `create` and `buildView` methods with their replacements.
No issue; updating per https://github.com/flutter/flutter/blob/main/docs/infra/Packages-Gardener-Rotation.md#deprecations
[CLA]: …

[video_player] Update tests for deprecatitons

---

packages/go_router_builder/example/test/case_sensitivity_example_test.dart

Part of  https://github.com/flutter/flutter/issues/169809
Prepare for https://github.com/flutter/packages/pull/9426, this skips a test that needs to migrated with the new version of `go_router`.
[the auto-formatter]: https://github.com/flutter/packages/blob/main/script/tool/READ …

[go_router_builder] Skip case sensitive test

---

packages/go_router/lib/src/match.dart
packages/go_router/lib/src/route.dart

Prepares for: https://github.com/flutter/flutter/issues/171410
I created a calendar event for January 30, 2026. Hopefully I'll still employed then 🤞 
**Version change exemption reason**, **CHANGELOG exemption reason**, **Test exemption reason**: This only adds comments. No semantic changes. …

[go_router] Add TODOs for meta migration

---

packages/camera/camera/CHANGELOG.md
packages/camera/camera/lib/camera.dart
packages/camera/camera/pubspec.yaml
packages/camera/camera/test/camera_export_test.dart
packages/camera/camera/test/camera_test.dart

Closes https://github.com/flutter/flutter/issues/171433
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Cha …

[camera] fix `CameraLensType` export

---

packages/go_router_builder/example/pubspec.yaml
packages/go_router_builder/example/test/case_sensitivity_example_test.dart

Part of
- https://github.com/flutter/flutter/issues/169809
Follow-up of 
- https://github.com/flutter/packages/pull/9426
- https://github.com/flutter/packages/pull/9444
Unskips and migrates the test about case sensitivity to the new version of `go_router` 15.2.4.
[the …

[go_router_builder] Update case sensitive test to `go_router` 16.0.0

---

packages/in_app_purchase/in_app_purchase_storekit/example/shared/RunnerTests/Stubs.h

Interface change PR: https://github.com/flutter/flutter/pull/174168
[^1]: Regular contributors who have demonstrated familiarity with the repository guidelines only need to comment if the …

Update Stubs for FlutterPluginRegistrar interface change

---

.ci.yaml

SDK 36v3 has been uploaded to CI. It includes the new ndk version r28c that supports 16kb page sizes. We ensure packages CI tests against it.
[^1]: Regular contributors who have …

Update CI to Test Against SDK 36v3
