flutter/packages

- packages/go_router/CHANGELOG.md
- packages/go_router/example/lib/on_exit.dart
- packages/go_router/example/test/on_exit_test.dart
- packages/go_router/lib/src/builder.dart
- packages/go_router/lib/src/delegate.dart
- packages/go_router/lib/src/route.dart
- packages/go_router/pubspec.yaml
- packages/go_router/test/on_exit_test.dart
related https://github.com/flutter/flutter/issues/102408 …
> [go_router] Adds on exit

- packages/url_launcher/url_launcher_ios/example/ios/RunnerTests/URLLauncherTests.swift
- packages/webview_flutter/webview_flutter_wkwebview/example/ios/RunnerTests/FWFWebViewHostApiTests.m
For applications linked against iOS 17 or later, NSURL no longer returns `nil` for invalid URLs, so tests that were specific to that behavior have to be adjusted to allow for another outcome.
Fixes https://github.com/flutter/flutter/issues/134972
Part of https://github.com/flutter/flutter/issues/134971
[Discord]: …
> [various] Update invalid NSURL tests

- packages/camera/camera_android/CHANGELOG.md
- packages/camera/camera_android/test/android_camera_test.dart
- packages/camera/camera_android/test/method_channel_mock.dart
Since the minimum Flutter version for this package is +3.0, we can remove the `_ambiguate` method. Because this PR only affects tests, we don't need to publish a new version.
Part of https://github.com/flutter/flutter/issues/111841
[Discord]: …
> [camera_android] Removes usage of `_ambiguate` method in tests

- packages/camera/camera_android/CHANGELOG.md
- packages/camera/camera_android/android/build.gradle
- packages/camera/camera_android/example/android/build.gradle
- packages/camera/camera_android/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/camera/camera_android/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/134818
See https://github.com/flutter/packages/pull/4535 for an example of when this was done for a different plugin. …
> [camera_android] Set buildconfig to true for compatibility with AGP 8.0+

- packages/camera/camera_android/CHANGELOG.md
- packages/camera/camera_android/android/build.gradle
- packages/camera/camera_android/pubspec.yaml
- script/configs/exclude_all_packages_app.yaml
- script/tool/lib/src/create_all_packages_app_command.dart
- script/tool/test/create_all_packages_app_command_test.dart
Fixes the current failures of the build_all_packages tests that were caused in https://github.com/flutter/packages/pull/4951/files. 
[exempt from …
> [camera_android] Downgrade to AGP 7.3.0 to fix build_alll_packages test failures

- packages/video_player/video_player_web/CHANGELOG.md
- packages/video_player/video_player_web/example/integration_test/video_player_test.dart
- packages/video_player/video_player_web/lib/src/video_player.dart
- packages/video_player/video_player_web/pubspec.yaml
This PR changes the initialization of the `video` element used by the web implementation of the video_player plugin to **ensure the `autoplay` attribute is set to _**false**_**, as expected by the code.
* Fixes flutter/flutter#135194
* ~~May be the root cause of flutter/flutter#130147~~ (it isn't, I've seen the integration test failing again) …
> [video_player] Ensures autoplay is false on the web.

- packages/go_router/CHANGELOG.md
- packages/go_router/lib/src/route.dart
- packages/go_router/pubspec.yaml
Fixes https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8768923225300611905/+/u/Run_flutter_plugins_tests/stdout
Each `{@tool}` tag must also have an `{@end-tool}` tag. …
> [go_router] Fix @tool directive with missing @end-tool

- script/tool/lib/src/podspec_check_command.dart
- script/tool/test/podspec_check_command_test.dart
The Flutter build process creates podspecs that are just shims pointing to the local Flutter framework, and which don't pass the linter since they aren't intended for publishing. When finding podspecs to lint, skip those.
This avoids incorrect failures when running on a tree that isn't clean (in particular, where macOS and/or iOS builds have happened), which is very common locally.
> [tool] Don't lint Flutter shim podspecs

- packages/camera/camera_android/CHANGELOG.md
- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/CameraCaptureCallback.java
- packages/camera/camera_android/android/src/test/java/io/flutter/plugins/camera/CameraCaptureCallbackTest.java
- packages/camera/camera_android/pubspec.yaml
Fixes a typo introduced during a testability refactor that caused the capture state machine to read the wrong value for autofocus state, breaking the state machine.
Fixes https://github.com/flutter/flutter/issues/135554
Part of https://github.com/flutter/flutter/issues/84957 …
> [camera] Fix Android autofocus state reading

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/example/ios/Runner.xcodeproj/project.pbxproj
- packages/camera/camera_avfoundation/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/camera/camera_avfoundation/example/ios/RunnerTests/CameraPropertiesTests.m
- packages/camera/camera_avfoundation/ios/Classes/CameraProperties.h
- packages/camera/camera_avfoundation/ios/Classes/CameraProperties.m
- packages/camera/camera_avfoundation/ios/Classes/FLTCam.m
- packages/camera/camera_avfoundation/pubspec.yaml
Using `@throw` in iOS code violates the style guide, so it shouldn't be done in the plugin as mechanism for communicating errors. More importantly, `NSError` is not intended to be used with `@throw`/`@catch`, and is causing issues when compiled with the iOS 17 SDK.
This removes all use of `@throw`, and all `@catch (NSError* e)`, in favor of other methods of communicating errors. It explicitly does not try to fix all the other strange things about this code (having an `NSError` out-param in an init method, using Cocoa and NSURL error domains and codes for some reason), and instead preserves existing behavior as much as possible. In practice, none of these codepaths should ever actually happen (they indicate programming errors within the plugin, not unexpected runtime behavior), and all of …
> [camera] Remove `@throw` from iOS implementation

- script/configs/exclude_integration_android_emulator.yaml
When the emulator tests for Android were brought up, `google_maps_fluter_android` was excluded due to flake. We're also seeing high flake from `google_maps_flutter` on Android, so disabling that as well.
We continue to have coverage of these tests via FTL, so it's only the relatively new emulator version that is being disabled here.
See https://github.com/flutter/flutter/issues/130986
> [ci] Disable maps tests in Android emulator

- packages/webview_flutter/webview_flutter/CHANGELOG.md
- packages/webview_flutter/webview_flutter/lib/webview_flutter.dart
- packages/webview_flutter/webview_flutter/pubspec.yaml
- packages/webview_flutter/webview_flutter/test/webview_flutter_test.dart
`JavaScriptConsoleMessage` includes a field with type  `JavaScriptLogLevel` and was missing from https://github.com/flutter/packages/pull/4705. …
> [webview_flutter] Exposes missing `JavaScriptLogLevel` from platform interface

- packages/flutter_markdown/CHANGELOG.md
- packages/flutter_markdown/lib/src/builder.dart
- packages/flutter_markdown/pubspec.yaml
Because of using `DecoratedBox` for code block the content is above the decoration. This PR replaces `DecoratedBox` with `Container`.
Issue: https://github.com/flutter/flutter/issues/135858 …
> [flutter_markdown] Code decoration

- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_wkwebview/lib/src/webkit_webview_controller.dart
- packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml
It seems that [WKWebView.customUserAgent](https://developer.apple.com/documentation/webkit/wkwebview/1414950-customuseragent?language=objc) is never actually set to nil. It was always an empty String. Even after attempting to set the value to nil, the value would always return as an empty String. This is in contrary to the documentation for the property.
I'm not sure if this is based on the iOS version, so this PR checks if the value is null or is empty.
Fixes https://github.com/flutter/flutter/issues/135813 …
> [webview_flutter_wkwebview] Fixes bug where `WebkitWebViewController.getUserAgent` was incorrectly returning an empty String 

- packages/path_provider/path_provider/example/integration_test/path_provider_test.dart
- Fix the `throwsA` test to properly await.
- Updates the `getDownloadsDirectory` test to not assume that Android will throw, since that is no longer true.
> [path_provider] Fix integration tests

- packages/url_launcher/url_launcher_ios/example/ios/RunnerUITests/URLLauncherUITests.swift
For some reason tapping the "Done" button in the XCUITest stopped working in Xcode 15, but tapping it via coordinates works, so switch to that as a workaround.
Fixes https://github.com/flutter/flutter/issues/134971
> [webview_flutter] Fix XCUITest in Xcode 15

- packages/go_router/CHANGELOG.md
- packages/go_router/lib/src/configuration.dart
- packages/go_router/pubspec.yaml
- packages/go_router/test/exception_handling_test.dart
This will help in knowing the extra Object passed when the _non-existing-location_ was asked.
- The issue looks small, I will create it if needed by the maintainers
- No breaking changes …
> [go_router] Fixes missing state.extra in onException()

- .ci.yaml
This begins to migrate the Windows CI tests to use a new x64 specific Windows platform. For now these duplicate the existing tests in `bringup` mode.
A subsequent pull request (https://github.com/flutter/packages/pull/5141) will complete the migration by removing the old Windows tests and removing the `bringup` from the new x64 specific tests. Here are the resulting changes from both steps of the migration: https://github.com/flutter/packages/compare/main...loic-sharma:flutter-packages:windows_x64_ci_finalize
In the future, a new platform will be added for Windows Arm64 tests.
Prepares for https://github.com/flutter/flutter/issues/129813
Subsequent pull requests:
* https://github.com/flutter/packages/pull/5141
* https://github.com/flutter/packages/pull/5142
If you need help, consider …
> [ci] Add x64 specific Windows platform 

- packages/flutter_lints/CHANGELOG.md
- packages/flutter_lints/pubspec.yaml
- rev package:flutter_lints to 3.0 in order to increase the dep. on package:lints (to its recently released 3.0.0 version)
- [-] I listed at least one issue that this PR fixes in the description above. …
> [flutter_lints] rev flutter_lints to 3.0; increase dep on package:lints

- packages/go_router/CHANGELOG.md
- packages/go_router/README.md
- packages/go_router/doc/configuration.md
- packages/go_router/example/lib/routing_config.dart
- packages/go_router/example/test/routing_config_test.dart
- packages/go_router/lib/src/configuration.dart
- packages/go_router/lib/src/match.dart
- packages/go_router/lib/src/parser.dart
- packages/go_router/lib/src/router.dart
- packages/go_router/pubspec.yaml
- packages/go_router/test/builder_test.dart
- packages/go_router/test/configuration_test.dart
- packages/go_router/test/inherited_test.dart
- packages/go_router/test/match_test.dart
- packages/go_router/test/matching_test.dart
- packages/go_router/test/parser_test.dart
- packages/go_router/test/routing_config_test.dart
- packages/go_router/test/test_helpers.dart
fixes https://github.com/flutter/flutter/issues/136005 …
> [go_router] adds ability to dynamically update routing table.

- packages/pigeon/CHANGELOG.md
- packages/pigeon/example/app/ios/Runner/Messages.g.swift
- packages/pigeon/lib/generator_tools.dart
- packages/pigeon/lib/swift_generator.dart
- packages/pigeon/pigeons/core_tests.dart
- packages/pigeon/platform_tests/alternate_language_test_plugin/android/src/main/java/com/example/alternate_language_test_plugin/CoreTests.java
- packages/pigeon/platform_tests/alternate_language_test_plugin/ios/Classes/CoreTests.gen.h
- packages/pigeon/platform_tests/alternate_language_test_plugin/ios/Classes/CoreTests.gen.m
- packages/pigeon/platform_tests/alternate_language_test_plugin/macos/Classes/CoreTests.gen.h
- packages/pigeon/platform_tests/alternate_language_test_plugin/macos/Classes/CoreTests.gen.m
- packages/pigeon/platform_tests/shared_test_plugin_code/lib/src/generated/core_tests.gen.dart
- packages/pigeon/platform_tests/test_plugin/android/src/main/kotlin/com/example/test_plugin/CoreTests.gen.kt
- packages/pigeon/platform_tests/test_plugin/example/ios/RunnerTests/RunnerTests.swift
- packages/pigeon/platform_tests/test_plugin/ios/Classes/CoreTests.gen.swift
- packages/pigeon/platform_tests/test_plugin/macos/Classes/CoreTests.gen.swift
- packages/pigeon/platform_tests/test_plugin/windows/pigeon/core_tests.gen.cpp
- packages/pigeon/platform_tests/test_plugin/windows/pigeon/core_tests.gen.h
- packages/pigeon/pubspec.yaml
Protocols to make testing with mocks easier.
Fixes https://github.com/flutter/flutter/issues/136811 …
> [pigeon] add flutter api protocol

- script/tool/lib/src/common/package_command.dart
- script/tool/test/common/package_command_test.dart
`filter-packages-to` didn't correctly the handle the case where the set of target packages is empty, meaning that all packages should be tested. This broke it for cases such as changing a CI configuration file, making the filter not take effect.
> [tool] Fix `filter-packages-to` when everything is changed

- packages/image_picker/image_picker_ios/example/ios/RunnerUITests/ImagePickerFromGalleryUITests.m
- packages/image_picker/image_picker_ios/example/ios/RunnerUITests/ImagePickerFromLimitedGalleryUITests.m
With Xcode 15, XCTest's `addUIInterruptionMonitorWithDescription` sometimes doesn't work. To fix, I added a fallback to query for the buttons in the permissions dialog.
Also, the Allow text in the permissions dialog is different in iOS 17 than previous versions.
Fixes https://github.com/flutter/flutter/issues/136747
Example passing on Xcode 15 with iOS 17 simulator: https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20ios_platform_tests_shard_3%20master/7604/overview …
> [image_picker_ios] Update UITests for Xcode 15/iOS 17

- .ci.yaml
https://github.com/flutter/packages/pull/5133 began to migrate the Windows CI tests to use a new x64 specific Windows platform. This completes the migration by removing the old Windows tests and removing `bringup` from the new x64 specific tests.
To see the resulting changes from both steps of the migration, refer to: https://github.com/flutter/packages/compare/0bddb1638ad2ebcc8b04bdc81d1b1530f7cee05d...loic-sharma:flutter-packages:windows_x64_ci_finalize_2#diff-9e73abde9fff445f31e5928e80d2d3f88847e02fd8f76d46f66f147fdc82786d
Prepares for https://github.com/flutter/flutter/issues/129813
Previous stacked pull request: https://github.com/flutter/packages/pull/5133
Next stacked pull request: https://github.com/flutter/packages/pull/5142
If you need help, consider asking for advice on the …
> [ci] Finalize migration to x64 specific Windows platform

- .ci.yaml
Add build-only Windows Arm64 CI tests, mirroring the way we handle multi-arch for macOS.
Completes: https://github.com/flutter/flutter/issues/129813
Previous stacked pull requests:
* https://github.com/flutter/packages/pull/5133
* https://github.com/flutter/packages/pull/5174
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-ch …
> [ci] Add build-only Windows Arm64 tests

- script/tool/lib/src/format_command.dart
- script/tool/test/format_command_test.dart
Adds support for swift-format in the `format` command. For now this is optional, so is only triggered if the flag is explictly passed. In the future, once we have CI support for swift-format, we will likely want to make it on-by-default as with the other formatters.
Part of https://github.com/flutter/flutter/issues/41129
> [tool] Add optional swift-format support

- .ci.yaml
The Windows Arm64 tests are failing to start as no machines match desired properties. This removes the `device_type: none` property as no Windows Arm64 machines match this ([with `device_type`](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=cpu%3Aarm64&f=os%3AWindows&f=pool%3Aluci.flutter.staging&f=device_type%3Anone&s=id), [without `device_type`](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=cpu%3Aarm64&f=os%3AWindows&f=pool%3Aluci.flutter.staging&s=id)).
This matches the corresponding framework `.ci.yaml` platform properties, which also omits the `device_type: none` for Windows Arm64: https://github.com/flutter/flutter/blob/997a94fd1f022492b6c955013eeec7e4c4e67c62/.ci.yaml#L192-L209
Part of …
> [ci] Remove device_type property from Windows Arm64 properties

- .ci/targets/android_device_tests.yaml
Changes firebase device tests to use android 13. I know there is consideration [for turning them off](https://github.com/flutter/flutter/issues/131429), but as long as we are running them we may as well run them on as new an android version as we can (I'm assuming here we can't use android 14 due to the [ongoing work](https://github.com/flutter/packages/pull/4974) to fix some tests on android 14).
The particular device is listed as high capacity. The list can be seen here in the 3rd option without any login https://firebase.google.com/docs/test-lab/android/available-testing-devices …
> Change firebase device tests from Android api 30 to 33

- .ci.yaml
Uses a capital for the first letter of the task names for consistency with the other tasks (which affects sorting in the GitHub PR UI).
Part of https://github.com/flutter/flutter/issues/130010
> [ci] Fix legacy Android task names

- .ci.yaml
The Windows Arm64 build-only stable test is currently failing as the necessary build layout migration hasn't landed on stable yet: https://github.com/flutter/flutter/commit/792e26df9540cf2cf510ea0c11a53ba10a243424
This test can be re-added after the next Flutter stable release. This is tracked by https://github.com/flutter/flutter/issues/129813 …
> [ci] Disable Windows Arm64 stable CI

- .ci.yaml
The new ruby packages are fully automated and already include cocoapods.
Bug: https://github.com/flutter/flutter/issues/136377 …
> Replace gems dependency with ruby.

- packages/url_launcher/url_launcher/CHANGELOG.md
- packages/url_launcher/url_launcher/README.md
- packages/url_launcher/url_launcher/lib/src/url_launcher_uri.dart
- packages/url_launcher/url_launcher/pubspec.yaml
- packages/url_launcher/url_launcher/test/src/url_launcher_uri_test.dart
The new query APIs added in 6.2.0 accidentally used `PreferredLaunchMode`, which is only intended for the platform interface layer, rather than `LaunchMode`, which is the app-facing analog (they are separate to allow controlling when each is updated separately).
Technically this is a breaking change, but 6.2.0 was out for less than 24 hours, so extremely few people will be affected (they would have to have updated, written code against the new API, and worked around the lack of type export), and a breaking change to fix this would have much more disruptive effects on the ecosystem.
Fixes https://github.com/flutter/flutter/issues/137278 …
> [url_launcher] Fix launch mode types in new APIs

- packages/flutter_lints/CHANGELOG.md
- packages/flutter_lints/README.md
- packages/flutter_lints/pubspec.yaml
This pull request is to replace `—dev` with `dev:`, as this is the newer way and is used in the Flutter documentation.
https://dart.dev/tools/pub/cmd/pub-add#dev-dependency
https://docs.flutter.dev/data-and-backend/serialization/json#setting-up-json_serializable-in-a-project
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-cha …
> [flutter_lints] Replace "flutter pub add --dev" with "dev:"

- packages/pigeon/CHANGELOG.md
- packages/pigeon/example/app/macos/Runner/messages.g.h
- packages/pigeon/example/app/macos/Runner/messages.g.m
- packages/pigeon/lib/generator_tools.dart
- packages/pigeon/lib/objc_generator.dart
- packages/pigeon/platform_tests/alternate_language_test_plugin/example/ios/RunnerTests/MultipleArityTest.m
- packages/pigeon/platform_tests/alternate_language_test_plugin/example/ios/RunnerTests/NullFieldsTest.m
- packages/pigeon/platform_tests/alternate_language_test_plugin/example/ios/RunnerTests/PrimitiveTest.m
- packages/pigeon/platform_tests/alternate_language_test_plugin/example/macos/Runner.xcodeproj/project.pbxproj
- packages/pigeon/platform_tests/alternate_language_test_plugin/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/pigeon/platform_tests/alternate_language_test_plugin/ios/Classes/AlternateLanguageTestPlugin.m
- packages/pigeon/platform_tests/alternate_language_test_plugin/ios/Classes/CoreTests.gen.h
- packages/pigeon/platform_tests/alternate_language_test_plugin/ios/Classes/CoreTests.gen.m
- packages/pigeon/platform_tests/alternate_language_test_plugin/macos/Classes/AlternateLanguageTestPlugin.m
- packages/pigeon/platform_tests/alternate_language_test_plugin/macos/Classes/CoreTests.gen.h
- packages/pigeon/platform_tests/alternate_language_test_plugin/macos/Classes/CoreTests.gen.m
- packages/pigeon/platform_tests/test_plugin/example/macos/Runner.xcodeproj/project.pbxproj
- packages/pigeon/platform_tests/test_plugin/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/pigeon/pubspec.yaml
- packages/pigeon/test/objc_generator_test.dart
Updates the Objective-C generator to use `BOOL`, `NSInteger`, and `double` for non-nullable versions of those primitives, instead of boxing them with `NSNumber*`. This makes the code more idiomatic, brings them into alignment with enum behavior, and importantly helps minimize the chances of clients having issues with silent conversion of `NSNumber*` to `BOOL` in the long term (although it may cause some such issues in the short term when people update; the changelog contains a prominent warning about this).
As an incidental fix, this also fixes the use of `strong` for collections and strings, which is not best practice, since I was already changing related code.
Fixes https://github.com/flutter/flutter/issues/116680
Fixes https://github.com/flutter/flutter/issues/127401
[Contributor …
> [pigeon] Don't wrap non-nullable primitives in Obj-C

- packages/image_picker/image_picker_ios/CHANGELOG.md
- packages/image_picker/image_picker_ios/example/ios/RunnerTests/ImagePickerPluginTests.m
- packages/image_picker/image_picker_ios/ios/Classes/FLTImagePickerPlugin.m
- packages/image_picker/image_picker_ios/pubspec.yaml
The image picker plugin's implementation doesn't currently handle multiple calls correctly due to the use of an ivar to track the response object; the original entry point handles that by cancelling earlier requests when new ones come in, but as we added more entry points we didn't replicate that logic. This adds it to all picker entry points. (Longer term, we should instead handle multiple concurrent calls, but this is consistent with historical behavior, and is better than having some `await`s on the Dart side never return as can happen now.)
The newer PHPicker code path not only didn't cancel, but used an ivar for the picker view controller, which in some cases could result in the same controller being presented multiple times, crashing the app (see referenced issue). While the new …
> [image_picker] Prevent multiple active calls on iOS

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/example/ios/RunnerTests/CameraOrientationTests.m
- packages/camera/camera_avfoundation/example/ios/RunnerTests/CameraPropertiesTests.m
- packages/camera/camera_avfoundation/example/lib/camera_preview.dart
- packages/camera/camera_avfoundation/ios/Classes/CameraProperties.m
- packages/camera/camera_avfoundation/pubspec.yaml
- Fixes https://github.com/flutter/flutter/issues/117981
- Fixes https://github.com/flutter/flutter/issues/101878
Tests are also updated correspondingly. …
> [camera_avfoundation] 🐛 Fix inverted orientation strings

- packages/video_player/video_player_web/CHANGELOG.md
- packages/video_player/video_player_web/example/integration_test/video_player_test.dart
- packages/video_player/video_player_web/lib/src/video_player.dart
- packages/video_player/video_player_web/lib/video_player_web.dart
- packages/video_player/video_player_web/pubspec.yaml
This PR configures the underlying HTMLVideoElement used by the plugin so it triggers a `VideoEventType.initialized` both for `canplay` (current behavior) and `loadedmetadata` events (fixes iOS 17).
It also sets `src` as the last configuration value when creating the VideoElement, which is common practice when listening to events from HTMLElements, like `img` or even `iframe`s.
* Fixes: **P1** https://github.com/flutter/flutter/issues/137023
* Added a small integration test to ensure `loadedmetadata` triggers the expected VideoPlayer event.
* Deployed changes to: https://dit-videoplayer-tests.web.app for manual verification on an actual iOS device. …
> [video_player_web] Listen to loadedmetadata event from video element.

- packages/google_sign_in/google_sign_in_web/CHANGELOG.md
- packages/google_sign_in/google_sign_in_web/example/integration_test/src/jwt_examples.dart
- packages/google_sign_in/google_sign_in_web/example/integration_test/utils_test.dart
- packages/google_sign_in/google_sign_in_web/lib/src/gis_client.dart
- packages/google_sign_in/google_sign_in_web/lib/src/utils.dart
- packages/google_sign_in/google_sign_in_web/pubspec.yaml
* Enables [**FedCM API**](https://developer.mozilla.org/en-US/docs/Web/API/FedCM_API) on compatible browsers.
* The GIS JS SDK falls-back to the JS implementation on browsers that don't support the new standard. See [migration instructions](https://developers.google.com/identity/gsi/web/guides/fedcm-migration)).
* Uses the supplied token expiration information to **more accurately compute `isSignedIn()` and `canAccessScopes(scopes)`**.
* This does not handle the case where users sign in/out in another tab or from outside the web app, that's still something that needs to be checked server-side.
* **Deprecates the `signIn()` method on the web.**
* Users should migrate to a combination of `renderButton()` and `silentSignIn()`, as described …
> [google_sign_in] Enable FedCM for web. Use token expiration.

- packages/flutter_image/lib/network.dart
- packages/flutter_markdown/lib/src/style_sheet.dart
Fixes https://github.com/flutter/flutter/issues/117838 …
> [flutter_image] [flutter_markdown] Do not use dynamic in an == operator override

- packages/webview_flutter/webview_flutter/CHANGELOG.md
- packages/webview_flutter/webview_flutter/example/lib/main.dart
- packages/webview_flutter/webview_flutter/pubspec.yaml
- packages/webview_flutter/webview_flutter_android/CHANGELOG.md
- packages/webview_flutter/webview_flutter_android/example/lib/main.dart
- packages/webview_flutter/webview_flutter_android/pubspec.yaml
- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/example/lib/main.dart
- packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml
Fixes in preparation for https://dart-review.googlesource.com/c/sdk/+/330561.
The change referenced above tightens the `use_build_context_synchronously` lint to ensure that `mounted` is checked on the appropriate `BuildContext` or `State`. This change fixes up violations in the flutter/packages repo in preparation of this new enforcement.
> Fix mounted checks

- packages/google_sign_in/google_sign_in_ios/ios/Classes/FLTGoogleSignInPlugin.m
Fix a formatting mistake from the conversion to Pigeon; the `;` here doesn't affect the behavior, but it's confusing, and makes the autoformatter unhappy. …
> [google_sign_in] Fix Obj-C formatting bug

- script/tool/lib/src/version_check_command.dart
- script/tool/test/version_check_command_test.dart
This tweaks the errors messages that provide info like how to override a repo check for versioning or changelog updates.
Basically added newlines, so the errors do not require scrolling far off to the right to get the message.
[Discord]: …
> [repo] Adjust error message layout for repo checks

- .ci.yaml
Newer versions of mac_toolchain increase Xcode install times by ~2 minutes (https://github.com/flutter/flutter/issues/138109). As a temporary solution, we're using an older version of mac_toolchain. …
> Use specific version of mac_toolchain

- packages/in_app_purchase/in_app_purchase_storekit/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_storekit/darwin/Classes/FIAPaymentQueueHandler.h
- packages/in_app_purchase/in_app_purchase_storekit/darwin/Classes/FIAPaymentQueueHandler.m
- packages/in_app_purchase/in_app_purchase_storekit/darwin/Classes/InAppPurchasePlugin.m
- packages/in_app_purchase/in_app_purchase_storekit/example/shared/RunnerTests/InAppPurchasePluginTests.m
- packages/in_app_purchase/in_app_purchase_storekit/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart
- packages/in_app_purchase/in_app_purchase_storekit/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_storekit/test/store_kit_wrappers/sk_methodchannel_apis_test.dart
Add `Future<SKStorefrontWrapper?> storefront()` method in SKPaymentQueue wrapper
fixes https://github.com/flutter/flutter/issues/137560
[exempt …
> [in_app_purchase] add storefront in skpaymentqueuewrapper

- .github/workflows/release.yml
The last commit failed to publish because it requires 3.16, and `release` is still using 3.13.
> Update release step to 3.16

- packages/go_router/CHANGELOG.md
- packages/go_router/example/pubspec.yaml
- packages/go_router/lib/src/delegate.dart
- packages/go_router/pubspec.yaml
Replaces an `extends Iterable` with `implements Iterable` for Dart 3.0 compatibility, and updates the minimum version of the Dart SDK to 3.0 to test it.
This helps unblock rolling the entire repo forward to Flutter 3.10/Dart 3.0 as a minimum version. …
> [go_router] Fixes use of `Iterable`

- packages/plugin_platform_interface/CHANGELOG.md
- packages/plugin_platform_interface/lib/plugin_platform_interface.dart
- packages/plugin_platform_interface/pubspec.yaml
The test mixin is currently declared as a `class`, which causes problems for projects with a minimum Dart version of 3.0. This switches it to `mixin class`; ideally it would just be a `mixin`, but in theory that could break something, so since this is such a core package in the ecosystem we want to be as conservative as possible. (While the breaking change would only in theory happen to test code, it's possible that someone ignored the `visibleForTesting`, and we have an easy way to avoid the possibility entirely.)
Fixes https://github.com/flutter/flutter/issues/123241 …
> [plugin_platform_interface] Switch mixin to `mixin class`

- packages/shared_preferences/shared_preferences_web/CHANGELOG.md
- packages/shared_preferences/shared_preferences_web/example/integration_test/shared_preferences_web_test.dart
- packages/shared_preferences/shared_preferences_web/example/pubspec.yaml
- packages/shared_preferences/shared_preferences_web/lib/shared_preferences_web.dart
- packages/shared_preferences/shared_preferences_web/lib/src/keys_extension.dart
- packages/shared_preferences/shared_preferences_web/pubspec.yaml
This allows this package to be used in a web app compiled to Wasm.
Helps unblock https://github.com/flutter/devtools/issues/6606
[exempt from …
> [shared_preferences_web] migrate to pkg:web

- packages/flutter_image/CHANGELOG.md
- packages/flutter_image/example/lib/main.dart
- packages/flutter_image/pubspec.yaml
Changed image link to use image within package.
> [flutter image] Changed image link to use image within package

- packages/flutter_markdown/CHANGELOG.md
- packages/flutter_markdown/lib/src/builder.dart
- packages/rfw/CHANGELOG.md
- packages/rfw/lib/src/flutter/argument_decoders.dart
- packages/rfw/lib/src/flutter/core_widgets.dart
See https://github.com/flutter/flutter/pull/138881
Fixes parts of https://github.com/flutter/flutter/issues/87235
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-c …
> [rfw, flutter_markdown] Prepare for removing dart:ui imports.

- packages/google_maps_flutter/google_maps_flutter_android/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_android/README.md
- packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/test/java/io/flutter/plugins/googlemaps/GoogleMapControllerTest.java
- packages/google_maps_flutter/google_maps_flutter_android/example/lib/readme_excerpts.dart
- packages/google_maps_flutter/google_maps_flutter_android/lib/src/google_maps_flutter_android.dart
- packages/google_maps_flutter/google_maps_flutter_android/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_android/test/google_maps_flutter_android_test.dart
The Google Maps LATEST renderer always uses a TextureView. We can use a signal from this TextureView to perform view invalidation that fixes the rendering glitches (missing updates) in TLHC mode.
NOTE: We have an internal bug 311013682 requesting an official way of achieving this functionality but if the bug is ever acted on it will take many months/years before we can rely on this functionality.
In the meantime, chain the internal SurfaceTextureListener with our own and piggyback on the OnSurfaceTextureUpdated callback to invalidate the MapView.
Fixes https://github.com/flutter/flutter/issues/103686
Tested on an emulator and a physical device (Pixel 6 Pro).
> Fix Google Maps rendering issues in TLHC mode when using LATEST renderer

- packages/pointer_interceptor/pointer_interceptor_platform_interface/AUTHORS
- packages/pointer_interceptor/pointer_interceptor_platform_interface/CHANGELOG.md
- packages/pointer_interceptor/pointer_interceptor_platform_interface/LICENSE
- packages/pointer_interceptor/pointer_interceptor_platform_interface/README.md
- packages/pointer_interceptor/pointer_interceptor_platform_interface/lib/pointer_interceptor_platform_interface.dart
- packages/pointer_interceptor/pointer_interceptor_platform_interface/lib/src/default_pointer_interceptor.dart
- packages/pointer_interceptor/pointer_interceptor_platform_interface/lib/src/pointer_interceptor_platform.dart
- packages/pointer_interceptor/pointer_interceptor_platform_interface/pubspec.yaml
- packages/pointer_interceptor/pointer_interceptor_platform_interface/test/default_pointer_interceptor_test.dart
- packages/pointer_interceptor/pointer_interceptor_platform_interface/test/pointer_interceptor_platform_test.dart
Addresses https://github.com/flutter/flutter/issues/30143 by adding an iOS implementation 
This PR is Part 1 of https://github.com/flutter/packages/pull/5233
> [pointer_interceptor] Add platform interface

- packages/flutter_image/CHANGELOG.md
- packages/flutter_image/README.md
- packages/flutter_image/example/lib/readme_excerpts.dart
- packages/flutter_image/example/test/readme_excerpts_test.dart
- packages/flutter_image/pubspec.yaml
- script/configs/temp_exclude_excerpt.yaml
Updates the README to use a compiled excerpt source for its example of using `NetworkImageWithRetry`.
Part of [flutter/flutter#102679](https://github.com/flutter/flutter/issues/102679) …
> [flutter_image] Adopt code excerpts in README

- packages/google_sign_in/google_sign_in_web/CHANGELOG.md
- packages/google_sign_in/google_sign_in_web/lib/src/gis_client.dart
- packages/google_sign_in/google_sign_in_web/pubspec.yaml
When initializing a `CodeClient`, it is mandatory to pass at least one `scope` (or the JS initialization will crash).
This PR ensures that the `CodeClient` is not created unless `initialScopes.isNotEmpty`, and lets the user know when attempting to use said client that it hasn't been initialized properly.
* Fixes: https://github.com/flutter/flutter/issues/139382
* Fixes: https://github.com/flutter/flutter/issues/62474
* Closes: https://github.com/flutter/cocoon/pull/3304 (makes this PR unneeded)
* Tested locally with `cocoon`. …
> [gsi_web] Do not initialize CodeClient if scopes are empty.

- .ci.yaml
Now that the [Windows build directory update](https://github.com/flutter/flutter/commit/792e26df9540cf2cf510ea0c11a53ba10a243424) migration is on the stable channel, add the build-only Windows Arm64 CI stable test.
Part of https://github.com/flutter/flutter/issues/129813 …
> [ci] Add Windows Arm64 stable build-only test

- packages/file_selector/file_selector_macos/example/lib/get_multiple_directories_page.dart
- packages/file_selector/file_selector_windows/example/lib/get_multiple_directories_page.dart
This PR is to remove deprecated `primary` and `onPrimary` references([deprecation PR](https://github.com/flutter/flutter/pull/105291)) from `ElevatedButton.styleFrom`.
`primary` should be replaced with `backgroundColor` and `onPrimary` should be replaced with `foregroundColor`.
No new tests needed. Please let me know if I incorrectly handled the CHANGELOG and version change.
> [file_selector] Remove deprecated `primary` and `onPrimary` references from `ElevatedButton.styleFrom`

- packages/pigeon/tool/shared/generation.dart
- packages/pigeon/tool/shared/process_utils.dart
Applies the same change as https://github.com/flutter/packages/pull/5410 to the Pigeon tooling, avoiding the need to manually wire up output forwarding.
Also adjusts a call site in the tooling that was forwarding all output normally but then also logging all output on failure to only log all output on failure.
[Discord]: …
> [pigeon] Use dart:io output inheritance for tooling

- packages/web_benchmarks/CHANGELOG.md
- packages/web_benchmarks/lib/client.dart
- packages/web_benchmarks/lib/src/recorder.dart
- packages/web_benchmarks/pubspec.yaml
- packages/web_benchmarks/testing/README.md
- packages/web_benchmarks/testing/test_app/.gitignore
Drop dart:html
Enables usage via WebAssembly
Fixes https://github.com/flutter/flutter/issues/139577
> [web_benchmarks] migrate to pkg:web

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/pubspec.yaml
- packages/camera/camera_android/example/pubspec.yaml
- packages/camera/camera_avfoundation/example/pubspec.yaml
- packages/google_sign_in/google_sign_in_platform_interface/CHANGELOG.md
- packages/google_sign_in/google_sign_in_platform_interface/lib/src/types.dart
- packages/google_sign_in/google_sign_in_platform_interface/pubspec.yaml
camera: was NOT used at all. Superfluous usage!
google_sign_in_platform_interface: dropping usage was trivial with
new dart:core APIs
[exempt from …
> Drop quiver usage in several packages

- packages/go_router/CHANGELOG.md
- packages/go_router/doc/navigation.md
- packages/go_router/pubspec.yaml
Fixed a typo in navigation.md:
```dart
context.go('/123, extra: 'abc');
```
to 
```dart
context.go('/123', extra: 'abc');
``` …
> [go_router] Fix(docs): Typo in Update navigation.md

- packages/web_benchmarks/CHANGELOG.md
- packages/web_benchmarks/lib/client.dart
- packages/web_benchmarks/lib/server.dart
- packages/web_benchmarks/lib/src/compilation_options.dart
- packages/web_benchmarks/lib/src/runner.dart
- packages/web_benchmarks/pubspec.yaml
- packages/web_benchmarks/testing/web_benchmarks_test.dart
This uses the same run flags that the flutter benchmark tests use: https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/web_benchmarks.dart#L36-L40
CC @kevmoo
> Add the ability to run web_benchmarks with Wasm

- packages/google_identity_services_web/CHANGELOG.md
- packages/google_identity_services_web/example/pubspec.yaml
- packages/google_identity_services_web/pubspec.yaml
The previous push to this package didn't update its pub.dev score/docs [(error log)](https://pub.dev/packages/google_identity_services_web/versions/0.3.0/score/log.txt).
---
This PR attempts to re-publish the package, in the hope that it was a transient error in pub.
~~Maybe workaround for https://github.com/dart-lang/pub-dev/issues/7267~~
It's confirmed that this was a transient error in pub, this PR now just corrects the changelog of the previous change to list the correct dart/flutter versions that are required (and update the dependency definitions to match the rest of the repo)
--- …
> [gis_web] Correct pub.dev changelog entry.

- .github/labeler.yml
Fixes an indentation bug in the config file that causes the task to fail.
> [ci] Fix indentation in labeler.yml

- packages/google_maps_flutter/google_maps_flutter/example/integration_test/src/maps_controller.dart
- packages/google_maps_flutter/google_maps_flutter_ios/example/ios11/integration_test/google_maps_test.dart
Disables the tests that have started failing for unknown OOB reasons, in order to fix the tree.
https://github.com/flutter/flutter/issues/139825
> [google_maps_flutter] Disable failing iOS tests

- script/tool/lib/src/update_min_sdk_command.dart
- script/tool/test/update_min_sdk_command_test.dart
The update-min-sdk command has been using explicitly ranges for the Dart SDK, because that used to be required. Current versions of `pub` no longer require that, and using `^` for Dart ranges is okay, so this updates the tooling to use that format in the future.
Also removes the special casing that changed the upper bound from 3 to 4, since we have passed the point where we are generating upper bounds less than 4 anyway.
To minimize churn, this doesn't update the existing pubspecs. We can incrementally adopt this going forward as we roll dependencies forward.
Fixes https://github.com/flutter/flutter/issues/139806
> [tool] Use ^ for Dart SDK

- packages/pointer_interceptor/pointer_interceptor/CHANGELOG.md
- packages/pointer_interceptor/pointer_interceptor/README.md
- packages/pointer_interceptor/pointer_interceptor/pubspec.yaml
Addresses https://github.com/flutter/flutter/issues/30143 by adding an iOS implementation, and https://github.com/flutter/flutter/issues/138217 by fixing README links
This PR is Part 3/3 of https://github.com/flutter/packages/pull/5233
> [pointer_interceptor] Fully publish pointer_interceptor package

- script/tool/lib/src/pubspec_check_command.dart
- script/tool/test/pubspec_check_command_test.dart
Fixes https://github.com/flutter/flutter/issues/139305
> [tools] Validate pubspec topic format

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/example/lib/main.dart
- packages/camera/camera/example/pubspec.yaml
- packages/camera/camera/pubspec.yaml
- packages/camera/camera_android/CHANGELOG.md
- packages/camera/camera_android/example/lib/main.dart
- packages/camera/camera_android/example/pubspec.yaml
- packages/camera/camera_android/pubspec.yaml
- packages/camera/camera_android_camerax/CHANGELOG.md
- packages/camera/camera_android_camerax/example/lib/main.dart
- packages/camera/camera_android_camerax/example/pubspec.yaml
- packages/camera/camera_android_camerax/pubspec.yaml
- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/example/lib/main.dart
- packages/camera/camera_avfoundation/example/pubspec.yaml
- packages/camera/camera_avfoundation/pubspec.yaml
- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/example/lib/main.dart
- packages/image_picker/image_picker/example/pubspec.yaml
- packages/image_picker/image_picker/pubspec.yaml
Updates examples in other packages (image_picker, camera) that use the deprecated `VideoPlayerController.network` to use the newer `VideoPlayerController.networkUrl` instead.
Fixes https://github.com/flutter/flutter/issues/127754 …
> [various] Update examples using video_player

- packages/google_sign_in/google_sign_in_web/CHANGELOG.md
- packages/google_sign_in/google_sign_in_web/example/integration_test/flexible_size_html_element_view_test.dart
- packages/google_sign_in/google_sign_in_web/lib/google_sign_in_web.dart
- packages/google_sign_in/google_sign_in_web/lib/src/flexible_size_html_element_view.dart
- packages/google_sign_in/google_sign_in_web/pubspec.yaml
The private `FlexHtmlElementView` widget that backs the `renderButton` method currently relies on internal web engine knowledge (a CSS selector) to work.
This PR reimplements that bit of the `FlexHtmlElementView` so it uses standard framework APIs, and removes its reliance in undocumented behavior.
* Related to: https://github.com/flutter/engine/pull/48960
[breaking change …
> [google_sign_in_web] Stop relying on framework internals.

- packages/google_identity_services_web/CHANGELOG.md
- packages/google_identity_services_web/lib/src/js_interop/shared.dart
- packages/google_identity_services_web/pubspec.yaml
- packages/google_sign_in/google_sign_in/example/lib/src/sign_in_button/web.dart
- packages/google_sign_in/google_sign_in/example/pubspec.yaml
- packages/google_sign_in/google_sign_in/example/web/index.html
**google_sign_in:**
* Updates web bootstrap following [Flutter Web initialization docs](https://docs.flutter.dev/platform-integration/web/initialization#skipping-this-step).
* Uses the recent [`web_only` library](https://pub.dev/documentation/google_sign_in_web/0.12.3/web_only/web_only-library.html) to `renderButton`.
* Updates dependencies so it can compile with `--wasm`.
(opportunistic weekend commit) **google_identity_services_web:**
* Adds missing `CredentialSelectBy.fedcm_auto` enum value.
* Bump patch version + changelog.
* Fixes https://github.com/flutter/flutter/issues/139852
* Missing bit of https://github.com/flutter/flutter/issues/138202
* Deployed to: https://dit-gis-test.web.app …
> [google_sign_in] Update (web) example app.

- packages/file_selector/file_selector_web/example/integration_test/dom_helper_test.dart
- packages/google_identity_services_web/example/integration_test/js_interop_id_test.dart
- packages/google_identity_services_web/lib/src/js_interop/google_accounts_id.dart
- packages/google_sign_in/google_sign_in_web/lib/src/flexible_size_html_element_view.dart
The definition of `JSArray` (and `JSPromise`) from `dart:js_interop` is changing to `JSArray<T>`, and our analyzer complains about our usage of it with default `T`s, blocking Dart SDK rolls.
This PR ignores the `always_specify_types` lint in the usages of `JSArray`, so this code passes analysis both with the current version of `dart:js_interop` and the next one.
* Fixes https://github.com/flutter/flutter/issues/140076
* Cleanup https://github.com/flutter/flutter/issues/140095 …
> [ci][web] Ignore always_specify_types for JSArray.

- packages/ios_platform_images/CHANGELOG.md
- packages/ios_platform_images/README.md
- packages/ios_platform_images/example/lib/main.dart
- packages/ios_platform_images/pubspec.yaml
- script/configs/temp_exclude_excerpt.yaml
Replaces the Dart example code with a code excerpt.
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-change …
> [ios_platform_images] Adopt code-excerpts

- packages/go_router/example/lib/extra_codec.dart
- packages/go_router/example/test/extra_codec_test.dart
Replace 
```
throw FormatException('Unable tp parse input: $input');
```
by
```
throw FormatException('Unable to parse input: $input');
```
[exempt …
> [go_router] fix(docs): typo in example extra_codec.dart

- packages/path_provider/path_provider_android/example/integration_test/path_provider_test.dart
Accidentally missed this in https://github.com/flutter/packages/pull/5628
fixes https://github.com/flutter/flutter/issues/139808
[exempt from …
> [path_provider_android] Re-enable getExternalStorageDirectories test

- packages/camera/camera_platform_interface/AUTHORS
- packages/camera/camera_platform_interface/CHANGELOG.md
- packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart
- packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart
- packages/camera/camera_platform_interface/lib/src/types/image_file_format.dart
- packages/camera/camera_platform_interface/lib/src/types/types.dart
- packages/camera/camera_platform_interface/pubspec.yaml
- packages/camera/camera_platform_interface/test/events/camera_event_test.dart
- packages/camera/camera_platform_interface/test/method_channel/method_channel_camera_test.dart
Part of  #4586
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-upd …
> [camera_platform_interface] Adds support for setting the image file format

- packages/google_sign_in/google_sign_in_ios/CHANGELOG.md
- packages/google_sign_in/google_sign_in_ios/pubspec.yaml
Fixes: https://github.com/flutter/flutter/issues/140213
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugi …
> [google_sign_in_ios] Move pigeon as a dev dependency

- script/tool/lib/src/podspec_check_command.dart
- script/tool/test/podspec_check_command_test.dart
CI has been updated to Cocoapods 1.13, which fixes previous issues with the plugin_lint_mac test. Remove workarounds added previously.
See https://github.com/flutter/flutter/issues/125812. …
> Remove workarounds for `check_podspecs` needed for older version of Cocoapods

- packages/go_router/CHANGELOG.md
- packages/go_router/README.md
- packages/go_router/doc/navigation.md
- packages/go_router/example/lib/push_with_shell_route.dart
- packages/go_router/example/test/push_with_shell_route_test.dart
- packages/go_router/lib/src/builder.dart
- packages/go_router/lib/src/configuration.dart
- packages/go_router/lib/src/delegate.dart
- packages/go_router/lib/src/match.dart
- packages/go_router/lib/src/pages/cupertino.dart
- packages/go_router/lib/src/pages/material.dart
- packages/go_router/lib/src/parser.dart
- packages/go_router/lib/src/route.dart
- packages/go_router/pubspec.yaml
- packages/go_router/test/builder_test.dart
- packages/go_router/test/delegate_test.dart
- packages/go_router/test/go_router_test.dart
- packages/go_router/test/imperative_api_test.dart
- packages/go_router/test/inherited_test.dart
- packages/go_router/test/match_test.dart
- packages/go_router/test/matching_test.dart
- packages/go_router/test/parser_test.dart
- packages/go_router/test/test_helpers.dart
This pr refactor RouteMatchList to be a tree structure.
Added a common base class RouteMatchBase. It is extended by both RouteMatch and ShellRouteMatch.
The RouteMatch is for GoRoute, and is always a leaf node
The ShellRouteMatch is for ShellRouteBase, and is always and intermediate node with a list of child RouteMatchBase[s].
This pr also redo how push is processed. Will add a doc explain this shortly.
This is a breaking change, will write a migration guide soon.
fixes https://github.com/flutter/flutter/issues/134524
fixes https://github.com/flutter/flutter/issues/130406
fixes https://github.com/flutter/flutter/issues/126365
fixes https://github.com/flutter/flutter/issues/125752
fixes https://github.com/flutter/flutter/issues/120791
fixes https://github.com/flutter/flutter/issues/120665 …
> [go_router] Refactored RouteMatchList and imperative APIs

- .ci.yaml
These targets are not enabled in presubmit, but enabled in CQ. This caused latest changes not surfaced from CQ side: CQ runs are based on out dated try runs. For example: `Mac_arm64 ios_platform_tests_shard_1 stable` is using the old build executed on 12/13: https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20ios_platform_tests_shard_1%20stable
This PR disables CQ for targets that are with `presubmit: false`, to unblock recipes CL: https://flutter-review.googlesource.com/c/recipes/+/53301
> Disable `presubmit: false` targets for recipes CQ

- script/tool/lib/src/common/repository_package.dart
- script/tool/test/common/repository_package_test.dart
A non-Flutter package can have Flutter-based tests (e.g., cupertino_icons), in which case we need to use `flutter test` rather than `dart test` just like we would for a package with a non-dev Flutter dependency. This updates the `requiresFlutter` check to include dev dependencies as well as normal dependencies.
> [tool] Handle Flutter dev dependencies

- AUTHORS
- packages/image_picker/image_picker_for_web/CHANGELOG.md
- packages/image_picker/image_picker_for_web/example/integration_test/image_picker_for_web_test.dart
- packages/image_picker/image_picker_for_web/lib/image_picker_for_web.dart
- packages/image_picker/image_picker_for_web/pubspec.yaml
This PR attempts to remove the input element added to the DOM after image selection is completed.
Fixes https://github.com/flutter/flutter/issues/139442 …
> [image_picker] Remove input element after completion

- script/tool/lib/src/fetch_deps_command.dart
- script/tool/test/fetch_deps_command_test.dart
For iOS and macOS move fetch deps from explicity running `pub get` and `pod install` to instead run `flutter build x --config-only` which smartly fetches deps and lays down the required native pieces.  I didn't guard it on whether certain files are present since the command already has similar guards, and runs pretty fast if the native code has already been generated.
This fixes an issue where `pod install` is run before the Flutter native bits and migrations are run.
Fixes issues seen in the Flutter roll https://github.com/flutter/packages/pull/5792#issuecomment-1876103613
```
Running command: "pod install" in /Volumes/Work/s/w/ir/x/w/packages/packages/camera/camera_avfoundation/example/ios
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Flutter":
In …
```
> [ci] Run 'flutter build --config-only for iOS and macOS during fetch deps

- .ci/targets/android_platform_tests.yaml
- script/configs/exclude_native_integration_android_emulator.yaml
To address extreme flake in the tree.
See https://github.com/flutter/flutter/issues/141136
> [ci] Exclude quick_actions from Android emulators

- packages/video_player/video_player/example/integration_test/video_player_test.dart
Temporary workaround for https://github.com/flutter/flutter/issues/141145
This doesn't fully skip the test because this problem doesn't happen in CI device tests or locally, so rather than totally lose coverage this detects the very specific markers of this flake and skips only when that happens. This should allow the tree to stop being so red with the minimal coverage loss while we investigate this further.
Part of https://github.com/flutter/flutter/issues/141145 …
> [video_player] Skip flaky tests in certain circumstances on Android

- .github/workflows/release.yml
google_maps_flutter_ios now requires 3.16.6, so we need to bump the release script so that it can be published by CI.
Fixes the tree.
> Bump `release` to use 3.16.6

- packages/pigeon/CHANGELOG.md
- packages/pigeon/lib/dart_generator.dart
- packages/pigeon/lib/generator_tools.dart
- packages/pigeon/lib/pigeon_lib.dart
- packages/pigeon/pubspec.yaml
- packages/pigeon/test/dart_generator_test.dart
Pigeon was not generating the wrapResponse method, and therefore failing compilation of the generated tests.
Fixes: https://github.com/flutter/flutter/issues/141499 …
> [pigeon] Fix pigeon test generation missing wrapResponse method.

- .ci.yaml
Fixes https://github.com/flutter/flutter/issues/141493 …
> [ci] Run check_podspecs on arm Mac bots

- .ci.yaml
- .ci/scripts/create_simulator.sh
- .ci/targets/ios_platform_tests.yaml
- packages/pigeon/tool/shared/test_suites.dart
Packages part of https://github.com/flutter/flutter/issues/132237. …
> Update tests to Xcode 15 and iOS 17 simulator

- script/tool/lib/src/format_command.dart
- script/tool/test/format_command_test.dart
Get ready for a world where `swift-format` is available on the `PATH` https://flutter-review.googlesource.com/c/recipes/+/54020
1. Add `format --clang-format --java --kotlin --swift --dart` flags to decide whether to run specific formatters, as opposed to using the `path`.  Keep `swift-format` optional but default the others to run.  This matches the current behavior on Linux.
2. Add `*-path` variants of each.
This will allow us to run `format --swift --no-clang-format --no-java --no-kotlin --no-dart`  on the macOS bot so it doesn't duplicate same `format` call run on Linux.
Part of https://github.com/flutter/flutter/issues/41129 …
> [ci] Add flags to formatter command to decide which formatters to run

- packages/google_maps_flutter/google_maps_flutter/example/ios/Podfile
- packages/google_maps_flutter/google_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj
- packages/google_maps_flutter/google_maps_flutter/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Follows up on https://github.com/flutter/packages/pull/5915 to remove the example-app-level workaround for the lack of arm64 slice, since the `flutter` build process will handle it automatically with current versions (now that the plugin-level workaround has been restored).
Also fixes another problem I noticed while removing those, which is that when I federated this plugin I never removed the RunnerTests and RunnerUITests targets from this project, even though all of the files had moved, leaving missing file references and targets that would not build. This hadn't been noticed because our tooling doesn't even try to run native tests on plugins that indicate that their implementation is in a different package (and we rarely manually open the native projects for the app-facing package). …
> [google_maps_flutter] Clean up iOS example project

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/example/ios/Runner.xcodeproj/project.pbxproj
`DEVELOPMENT_TEAM` should not be set in the example Xcode app.  Introduced extraneously in #3272 …
> [camera_avfoundation] Remove development team from Xcode example app

- packages/path_provider/path_provider_foundation/darwin/Classes/PathProviderPlugin.swift
- packages/path_provider/path_provider_foundation/darwin/RunnerTests/RunnerTests.swift
Run `swift-format` linter/formatter on Swift files.
Part of turning on swift-format CI formatting https://github.com/flutter/packages/pull/5928 …
> [path_provider_foundation] Run swift-format on Swift files

- packages/pigeon/CHANGELOG.md
- packages/pigeon/example/README.md
- packages/pigeon/example/app/ios/Runner/AppDelegate.swift
- packages/pigeon/platform_tests/alternate_language_test_plugin/example/macos/RunnerTests/RunnerTests.swift
- packages/pigeon/platform_tests/test_plugin/example/ios/Runner/AppDelegate.swift
- packages/pigeon/platform_tests/test_plugin/example/ios/RunnerTests/AllDatatypesTests.swift
- packages/pigeon/platform_tests/test_plugin/example/ios/RunnerTests/AsyncHandlersTest.swift
- packages/pigeon/platform_tests/test_plugin/example/ios/RunnerTests/EchoBinaryMessenger.swift
- packages/pigeon/platform_tests/test_plugin/example/ios/RunnerTests/EnumTests.swift
- packages/pigeon/platform_tests/test_plugin/example/ios/RunnerTests/HandlerBinaryMessenger.swift
- packages/pigeon/platform_tests/test_plugin/example/ios/RunnerTests/ListTests.swift
- packages/pigeon/platform_tests/test_plugin/example/ios/RunnerTests/MockBinaryMessenger.swift
- packages/pigeon/platform_tests/test_plugin/example/ios/RunnerTests/MultipleArityTests.swift
- packages/pigeon/platform_tests/test_plugin/example/ios/RunnerTests/NSNullFieldTests.swift
- packages/pigeon/platform_tests/test_plugin/example/ios/RunnerTests/NonNullFieldsTest.swift
- packages/pigeon/platform_tests/test_plugin/example/ios/RunnerTests/NullableReturnsTests.swift
- packages/pigeon/platform_tests/test_plugin/example/ios/RunnerTests/PrimitiveTests.swift
- packages/pigeon/platform_tests/test_plugin/example/macos/RunnerTests/BasicCompileTest.swift
- packages/pigeon/platform_tests/test_plugin/ios/Classes/TestPlugin.swift
- packages/pigeon/platform_tests/test_plugin/macos/Classes/TestPlugin.swift
Run `swift-format` linter/formatter on Swift files in example apps.  This only touches Swift files in example/test code.  
This also doesn't format any autogenerated Swift files, which would require changed in the pigeon generator: https://github.com/flutter/flutter/issues/141799
Part of turning on swift-format CI formatting https://github.com/flutter/packages/pull/5928 …
> [pigeon] Run swift-format on ungenerated example app Swift files

- packages/rfw/CHANGELOG.md
- packages/rfw/lib/src/flutter/runtime.dart
- packages/rfw/pubspec.yaml
- packages/rfw/test/runtime_test.dart
- packages/rfw/test_coverage/bin/test_coverage.dart
This exposes the necessary information to allow rfwpg to display registered libraries and widgets in a list or tree.
> Expose registered widget libraries and local widget library widgets.

- .ci.yaml
- .ci/targets/macos_repo_checks.yaml
- .ci/targets/repo_checks.yaml
- packages/file_selector/file_selector_macos/example/macos/RunnerTests/RunnerTests.swift
- packages/pigeon/tool/shared/generation.dart
- script/tool/lib/src/format_command.dart
- script/tool/test/format_command_test.dart
Make `swift-format` CIPD package available on the `PATH` https://flutter-review.googlesource.com/c/recipes/+/54020
Run `format --no-clang-format --no-java --no-kotlin --no-dart`  on the macOS builder so it doesn't duplicate same `format` call run on Linux.
Filter out generated files until https://github.com/flutter/flutter/issues/141799 is done.
Also add `swift-format lint` call during `format` command.  Fix the one casing issue it found in a test file.
Failing run:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8758535881172004177/+/u/Run_package_tests/Swift_format/stdout
Successful run:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8758492350529121249/+/u/Run_package_tests/Swift_format/stdout
Fixes https://github.com/flutter/flutter/issues/41129
If …
> [ci] Run Swift formatter and linter during CI formatting

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/example/ios/RunnerTests/FLTCamSampleBufferTests.m
- packages/camera/camera_avfoundation/ios/Classes/FLTCam.m
- packages/camera/camera_avfoundation/ios/Classes/QueueUtils.h
- packages/camera/camera_avfoundation/pubspec.yaml
This memory leak happens when pause/resume the recording. Depending on camera resolution, about 1-2MB leaks for every resume, so it can add up pretty fast if we frequently pause/resume. 
We only reference this sample buffer inside the scope of this method (e.g. directly piping into file IO), so no need to retain it again, as it's already retained and will be released afterwards by apple. (We did keep around the pixel buffer, but we already manually [retain](https://github.com/flutter/packages/blob/d7ee75ad59ad7bc45e659d0599e935e9e7981ea1/packages/camera/camera_avfoundation/ios/Classes/FLTCam.m#L403) and [release](https://github.com/flutter/packages/blob/d7ee75ad59ad7bc45e659d0599e935e9e7981ea1/packages/camera/camera_avfoundation/ios/Classes/FLTCam.m#L415) that)
Bug was introduced in …
> [camera]fix a sample buffer memory leak on pause resume recording

- packages/url_launcher/url_launcher/CHANGELOG.md
- packages/url_launcher/url_launcher/lib/src/url_launcher_uri.dart
- packages/url_launcher/url_launcher/pubspec.yaml
I found a grammer error in the comments of `launchUrl()` method. This PR fixes the error. …
> [url_launcher]: Fix a grammar error in the comments of launchUrl method

- packages/webview_flutter/webview_flutter_web/example/integration_test/legacy/webview_flutter_test.dart
- script/tool/lib/src/drive_examples_command.dart
Use a local web server for the legacy test, just as for the non-legacy version.
Also updates the repo tooling to ensure that this test file is found, so it's run regardless of whether tests are run by directory or by individual path.
Part of https://github.com/flutter/flutter/issues/95420
[pub …
> [webview_flutter] Use a local web server for legacy web integration tests

- packages/webview_flutter/webview_flutter_android/CHANGELOG.md
- packages/webview_flutter/webview_flutter_android/android/src/main/java/io/flutter/plugins/webviewflutter/GeneratedAndroidWebView.java
- packages/webview_flutter/webview_flutter_android/android/src/main/java/io/flutter/plugins/webviewflutter/WebChromeClientFlutterApiImpl.java
- packages/webview_flutter/webview_flutter_android/android/src/main/java/io/flutter/plugins/webviewflutter/WebChromeClientHostApiImpl.java
- packages/webview_flutter/webview_flutter_android/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_android/example/lib/main.dart
- packages/webview_flutter/webview_flutter_android/example/pubspec.yaml
- packages/webview_flutter/webview_flutter_android/lib/src/android_proxy.dart
- packages/webview_flutter/webview_flutter_android/lib/src/android_webview.dart
- packages/webview_flutter/webview_flutter_android/lib/src/android_webview.g.dart
- packages/webview_flutter/webview_flutter_android/lib/src/android_webview_api_impls.dart
- packages/webview_flutter/webview_flutter_android/lib/src/android_webview_controller.dart
- packages/webview_flutter/webview_flutter_android/pigeons/android_webview.dart
- packages/webview_flutter/webview_flutter_android/pubspec.yaml
- packages/webview_flutter/webview_flutter_android/test/android_navigation_delegate_test.dart
- packages/webview_flutter/webview_flutter_android/test/android_webview_controller_test.dart
- packages/webview_flutter/webview_flutter_android/test/android_webview_controller_test.mocks.dart
- packages/webview_flutter/webview_flutter_android/test/android_webview_test.mocks.dart
- packages/webview_flutter/webview_flutter_android/test/legacy/webview_android_widget_test.mocks.dart
- packages/webview_flutter/webview_flutter_android/test/test_android_webview.g.dart
* There are cases where Web calls System Popup with javascript on webview_flutter
* Android has a interface on WebChromeClient
* https://developer.android.com/reference/android/webkit/WebChromeClient#onJsAlert(android.webkit.WebView,%20java.lang.String,%20java.lang.String,%20android.webkit.JsResult)
* Related issue: https://github.com/flutter/flutter/issues/30358#issuecomment-1645347616
* Related Interface PR: https://github.com/flutter/packages/pull/5670
* The PR that contains all changes can be found at https://github.com/flutter/packages/pull/4704 …
> [webview_flutter_android] Add javascript panel interface for android

- packages/process/CHANGELOG.md
- packages/process/README.md
- packages/process/pubspec.yaml
This PR fixes https://github.com/flutter/flutter/issues/136221.
BTW it's a great package! I use it extensively in [patrol_cli] and love it.
[patrol_cli]: https://pub.dev/packages/patrol_cli
> Update README of `package:process`

- CONTRIBUTING.md
I never updated the contributing notes about languages when we added Kotlin to the repo.
> Add Kotlin to CONTRIBUTING.md

- packages/camera/camera_avfoundation/test/avfoundation_camera_test.dart
- packages/camera/camera_avfoundation/test/method_channel_mock.dart
- packages/camera/camera_platform_interface/test/utils/method_channel_mock.dart
- packages/camera/camera_windows/test/utils/method_channel_mock.dart
- packages/file_selector/file_selector_linux/test/file_selector_linux_test.dart
- packages/file_selector/file_selector_platform_interface/test/method_channel_file_selector_test.dart
- packages/go_router/test/go_router_test.dart
- packages/google_maps_flutter/google_maps_flutter_android/test/google_maps_flutter_android_test.dart
- packages/google_maps_flutter/google_maps_flutter_ios/test/google_maps_flutter_ios_test.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/method_channel/method_channel_google_maps_flutter_test.dart
- packages/google_sign_in/google_sign_in_platform_interface/test/method_channel_google_sign_in_test.dart
- packages/image_picker/image_picker_platform_interface/test/method_channel_image_picker_test.dart
- packages/in_app_purchase/in_app_purchase_android/test/billing_client_wrappers/billing_client_manager_test.dart
- packages/in_app_purchase/in_app_purchase_android/test/billing_client_wrappers/billing_client_wrapper_test.dart
- packages/in_app_purchase/in_app_purchase_android/test/in_app_purchase_android_platform_addition_test.dart
- packages/in_app_purchase/in_app_purchase_android/test/in_app_purchase_android_platform_test.dart
- packages/in_app_purchase/in_app_purchase_storekit/test/fakes/fake_storekit_platform.dart
- packages/in_app_purchase/in_app_purchase_storekit/test/in_app_purchase_storekit_platform_addtion_test.dart
- packages/in_app_purchase/in_app_purchase_storekit/test/in_app_purchase_storekit_platform_test.dart
- packages/in_app_purchase/in_app_purchase_storekit/test/store_kit_wrappers/sk_methodchannel_apis_test.dart
- packages/in_app_purchase/in_app_purchase_storekit/test/store_kit_wrappers/sk_payment_queue_delegate_api_test.dart
- packages/local_auth/local_auth_platform_interface/test/default_method_channel_platform_test.dart
- packages/path_provider/path_provider_platform_interface/test/method_channel_path_provider_test.dart
- packages/quick_actions/quick_actions_platform_interface/test/method_channel_quick_actions_test.dart
- packages/shared_preferences/shared_preferences_platform_interface/test/method_channel_shared_preferences_test.dart
- packages/url_launcher/url_launcher_linux/test/url_launcher_linux_test.dart
- packages/url_launcher/url_launcher_platform_interface/test/method_channel_url_launcher_test.dart
- packages/video_player/video_player_android/test/android_video_player_test.dart
- packages/video_player/video_player_avfoundation/test/avfoundation_video_player_test.dart
- packages/webview_flutter/webview_flutter_android/test/legacy/surface_android_test.dart
Removes the "ambiguate" method that was used to allow compatibility with both stable and master during the transition of `TestDefaultBinaryMessengerBinding.instance` from a nullable return to a non-nullable return, now that all versions we analyze are sufficiently new to have the non-nullable version.
Part of https://github.com/flutter/flutter/issues/111841
> [various] Disambiguate TestDefaultBinaryMessengerBinding

- .github/PULL_REQUEST_TEMPLATE.md
Reword the checklist item to make it clear that the issue should be a link to an actual filed issue, not just a description of a problem, and link to the relevant part of the wiki.
This is a common point of confusion.
> Clarify issue requirement

- .ci.yaml
- .ci/targets/repo_checks.yaml
Help buy a bit of time until we eliminate the max number of tasks for `release` to wait for, and be more efficient with CI resources:
- Folds the very fast repo-tooling-unit-test step into the existing repo checks task, cutting down on machine overhead.
- Removes the `master` version of downgraded analysis, since it's hard to imagine a plausible scenario where it fails but the `stable` version does not, so we don't need to spend resources on both.
See https://github.com/flutter/flutter/issues/141196
> [ci] Reduce tasks slightly

- packages/rfw/CHANGELOG.md
- packages/rfw/lib/src/flutter/content.dart
- packages/rfw/pubspec.yaml
- packages/rfw/test/runtime_test.dart
- packages/rfw/test_coverage/bin/test_coverage.dart
fixes https://github.com/flutter/flutter/issues/141069 …
> [rfw] Enable subscribing to the root of a DynamicContent

- script/tool/lib/src/drive_examples_command.dart
- script/tool/test/drive_examples_command_test.dart
Expand the multiple-test-files workaround in `drive-examples` from macOS to all of the desktop platforms, now that we know it's not macOS-specific.
See https://github.com/flutter/flutter/issues/135673
> [tool] Extend `flutter test` workaround to other desktops

- packages/camera/camera_android_camerax/CHANGELOG.md
- packages/camera/camera_android_camerax/lib/src/android_camera_camerax.dart
- packages/camera/camera_android_camerax/pubspec.yaml
- packages/camera/camera_android_camerax/test/android_camera_camerax_test.dart
Changes the `buildPreview` implementation to return a `Texture` versus a `FutureBuilder` that would ultimately return that same `Texture`.
The `FutureBuilder` depended on checking a condition that should be true by default assuming `createCamera` was called prior. This seems to be an assumption made consistently across other platform implementations (including `camera_android`-- see [source](https://github.com/flutter/packages/blob/7b1ae1f4cceea02f330716e701c6dcd9f0ca3f7e/packages/camera/camera_android/lib/src/android_camera.dart#L520)), so this PR is achieving consistency with them.
Fixes https://github.com/flutter/flutter/issues/140567. Thanks to @davidmartos96 for the push to investigate deeper on that issue! …
> [camerax] Change `buildPreview` to return `Texture` versus `FutureBuilder`

- packages/file_selector/file_selector/CHANGELOG.md
- packages/file_selector/file_selector/lib/file_selector.dart
- packages/file_selector/file_selector/pubspec.yaml
Replaces "pltaform" with "platform" in each instance.
> [file_selector] Fix comment typo

- script/tool/lib/src/dependabot_check_command.dart
- script/tool/test/dependabot_check_command_test.dart
When failing a package due to missing gradle coverage, explain what needs to be done to fix it.
Fixes https://github.com/flutter/flutter/issues/132453
> [tool] Add details to missing gradle coverage error

- packages/web_benchmarks/testing/web_benchmarks_test.dart
The semantics for the wasm stuff is changing, and this is blocking the roll. See https://github.com/flutter/flutter/issues/142809
Also, this test wasn't actually testing the wasm build previously, since it is still serving the `build/web` directory even though `--wasm` used to actually output to `build/web_wasm`.
> Skip the wasm test for now, it doesn't even actually test wasm currently

- packages/image_picker/image_picker_platform_interface/lib/src/types/picked_file/html.dart
See https://github.com/flutter/flutter/issues/143110
> [image_picker] Suppress analyzer warning about deprecation of UnmodifiableUint8ListView

- packages/go_router/CHANGELOG.md
- packages/go_router/lib/src/configuration.dart
- packages/go_router/lib/src/information_provider.dart
- packages/go_router/lib/src/parser.dart
- packages/go_router/lib/src/path_utils.dart
- packages/go_router/pubspec.yaml
- packages/go_router/test/go_router_test.dart
- packages/go_router/test/information_provider_test.dart
- packages/go_router/test/parser_test.dart
A number of developers have voiced the desire to be able to know whether a `GoRouterState` is the result of a deep-link or in-app navigation from within their `GoRouter`'s `redirect` method. This can be accomplished by exposing the `Uri`'s `scheme` and `host` on the `GoRouterState`. This way, we can know whether the `GoRouterState` is the result of a deep-link by checking `state.uri.scheme != null` or `state.uri.host != null`.
This PR would close [#103659](https://github.com/flutter/flutter/issues/103659#issuecomment-1865112881).
No tests were broken as a result of this change, and we have added coverage for this change through new tests. …
> [go_router] Expose full `Uri` on `GoRouterState` in `GoRouterRedirect`

- script/configs/allowed_unpinned_deps.yaml
We aren't quite ready to switch the endorsement to `local_auth_darwin`, so allow `local_auth_ios` for now.
> [ci] Allow dependencies on local_auth_ios

- packages/google_maps_flutter/google_maps_flutter_ios/example/ios12/integration_test/google_maps_test.dart
Skips `testTakeSnapshot` test re-enabeld by https://github.com/flutter/packages/pull/5823, but causing failures and blocking the `flutter/packages` tree, e.g. https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64%20ios_platform_tests_shard_2%20master/1697/overview. …
> [google_maps_flutter][iOS 12] Skip `testTakeSnapshot`

- packages/flutter_adaptive_scaffold/test/adaptive_layout_test.dart
- packages/flutter_adaptive_scaffold/test/simulated_layout.dart
- packages/flutter_image/lib/network.dart
- packages/flutter_image/test/network_test.dart
- packages/flutter_markdown/lib/src/_functions_io.dart
- packages/flutter_markdown/lib/src/_functions_web.dart
- packages/flutter_markdown/lib/src/builder.dart
- packages/flutter_markdown/test/text_scale_factor_test.dart
- packages/flutter_markdown/test/utils.dart
- packages/flutter_migrate/lib/src/base/common.dart
- packages/flutter_migrate/test/src/common.dart
- packages/flutter_migrate/test/src/test_flutter_command_runner.dart
- packages/go_router_builder/CHANGELOG.md
- packages/go_router_builder/lib/src/route_config.dart
- packages/go_router_builder/lib/src/type_helpers.dart
- packages/go_router_builder/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/bitmap_test.dart
- packages/image_picker/image_picker_platform_interface/lib/src/types/picked_file/html.dart
- packages/ios_platform_images/lib/ios_platform_images.dart
- packages/rfw/lib/src/flutter/core_widgets.dart
- packages/url_launcher/url_launcher/test/src/legacy_api_test.dart
- packages/url_launcher/url_launcher_platform_interface/lib/link.dart
- packages/url_launcher/url_launcher_platform_interface/test/link_test.dart
- packages/web_benchmarks/lib/src/recorder.dart
- packages/webview_flutter/webview_flutter_android/lib/src/android_webview_api_impls.dart
As of https://github.com/flutter/packages/pull/6111 `deprecated_member_use` is no longer on in the repository, so we no longer need (most; see below) of these annotations. Since we will not be annotating deprecated usage going forward, the associated comments with TODOs have also been removed, for consistency with the new process. This also opportunistically removes `deprecated_member_use_from_same_package` everywhere, since that has been disabled for a long time, so they were cruft.
I have ensured that issues are filed for all of these usages, with the new `p: deprecated api` tag, per the new process for tracking deprecated APIs that is now described in the Ecosystem gardener rotation handbook. (In summary: there will be a manual weekly process of checking for new deprecations and filing …
> [various] Clean up `deprecated_member_use` ignores

- packages/flutter_image/CHANGELOG.md
- packages/flutter_image/lib/network.dart
- packages/flutter_image/pubspec.yaml
- packages/flutter_image/test/network_test.dart
Now that it's available on every supported version, switch to `loadImage` instead of the deprecated `loadBuffer`.
Fixes https://github.com/flutter/flutter/issues/132856 …
> [flutter_image] Replace deprecated APIs

- packages/flutter_migrate/lib/src/base/common.dart
- packages/flutter_migrate/pubspec.yaml
- packages/flutter_migrate/test/src/common.dart
- packages/flutter_migrate/test/src/test_flutter_command_runner.dart
Updates package for `test_api` deprecation and deprecation of `runZoned`s `onError` parameter.
Fixes https://github.com/flutter/flutter/issues/143447
Fixes https://github.com/flutter/flutter/issues/143455 …
> [flutter_migrate] Replace deprecated APIs

- packages/flutter_adaptive_scaffold/test/adaptive_layout_test.dart
- packages/flutter_adaptive_scaffold/test/breakpoint_test.dart
- packages/flutter_adaptive_scaffold/test/simulated_layout.dart
Replaces the use of deprecated `MediaQueryData.fromWindow` and `window` in tests.
Fixes https://github.com/flutter/flutter/issues/143397
Part of https://github.com/flutter/flutter/issues/143399 …
> [flutter_adaptive_scaffold] Replace deprecated APIs

- packages/rfw/CHANGELOG.md
- packages/rfw/example/hello/pubspec.yaml
- packages/rfw/example/local/pubspec.yaml
- packages/rfw/example/remote/pubspec.yaml
- packages/rfw/example/wasm/pubspec.yaml
- packages/rfw/lib/src/flutter/core_widgets.dart
- packages/rfw/pubspec.yaml
- packages/rfw/test_coverage/pubspec.yaml
Replaces the deprecated `textScaleFactor` with a linear `TextScaler`.
Updates the minimum deployment version to 3.16 where the new API was added.
Part of https://github.com/flutter/flutter/issues/143400 …
> [rfw] Replace deprecated `textScaleFactor`

- packages/url_launcher/url_launcher_platform_interface/CHANGELOG.md
- packages/url_launcher/url_launcher_platform_interface/lib/link.dart
- packages/url_launcher/url_launcher_platform_interface/pubspec.yaml
- packages/url_launcher/url_launcher_platform_interface/test/link_test.dart
Update for
https://docs.flutter.dev/release/breaking-changes/route-information-uri and makes 3.13 the minimum supported version accordingly.
Fixes https://github.com/flutter/flutter/issues/124045 …
> [url_launcher] Replace deprecated RouteInformation APIs

- packages/google_sign_in/google_sign_in_ios/CHANGELOG.md
- packages/google_sign_in/google_sign_in_ios/darwin/Classes/FLTGoogleSignInPlugin.m
- packages/google_sign_in/google_sign_in_ios/pubspec.yaml
Internal native helper code was still using `id` arguments, doing type checking, and handling `NSNull`, none of which is relevant now that the calling code has been converted to Pigeon and is already strongly typed as `NSString`. …
> [google_sign_in] Clean up pre-Pigeon code

- packages/in_app_purchase/in_app_purchase_storekit/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_storekit/darwin/Classes/messages.g.h
- packages/in_app_purchase/in_app_purchase_storekit/darwin/Classes/messages.g.m
- packages/in_app_purchase/in_app_purchase_storekit/lib/src/messages.g.dart
- packages/in_app_purchase/in_app_purchase_storekit/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart
- packages/in_app_purchase/in_app_purchase_storekit/pigeons/messages.dart
- packages/in_app_purchase/in_app_purchase_storekit/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_storekit/test/store_kit_wrappers/pigeon_converter_test.dart
Should fix https://github.com/flutter/flutter/issues/143177
> [in_app_purchase] fix skerror nullability

- packages/flutter_migrate/test/src/fakes.dart
https://dart-review.googlesource.com/c/sdk/+/326761/24/sdk/lib/io/stdio.dart#380 added a `lineTerminator` field to `Stdout`.
See https://github.com/flutter/flutter/issues/143614
> [flutter_migrate] Implement lineTerminator in the MemoryStdout fake

- packages/google_sign_in/google_sign_in_web/CHANGELOG.md
- packages/google_sign_in/google_sign_in_web/example/pubspec.yaml
- packages/google_sign_in/google_sign_in_web/lib/src/flexible_size_html_element_view.dart
- packages/google_sign_in/google_sign_in_web/pubspec.yaml
This PR updates `google_sign_in_web` to use package `web: ^0.5.0`.
Manually verified using the `example/lib/button_tester.dart` app.
This should be text exempt? This is a refactor with no semantic change (also, I wouldn't know how to test we're using `package:web` the expected way!) I removed a couple of `//ignore` at least!
* Fast follow of: https://github.com/flutter/packages/pull/5791 …
> [google_sign_in_web] Updates package:web dependency to 0.5.0.

- packages/flutter_markdown/CHANGELOG.md
- packages/flutter_markdown/lib/src/_functions_web.dart
- packages/flutter_markdown/lib/src/builder.dart
- packages/flutter_markdown/pubspec.yaml
> [flutter_markdown] Support wasm

- packages/two_dimensional_scrollables/CHANGELOG.md
- packages/two_dimensional_scrollables/lib/src/table_view/table.dart
- packages/two_dimensional_scrollables/pubspec.yaml
- packages/two_dimensional_scrollables/test/table_view/table_test.dart
Fixes https://github.com/flutter/flutter/issues/143526
This fixes the layout offset computation when there are merged cells within pinned rows and/or columns in TableView.
[linked to at least one issue that this PR …
> [two_dimensional_scrollables] Fix layout offset of merged pinned cells

- packages/cross_file/CHANGELOG.md
- packages/cross_file/lib/src/types/html.dart
- packages/cross_file/lib/src/web_helpers/web_helpers.dart
- packages/cross_file/pubspec.yaml
- packages/cross_file/test/x_file_html_test.dart
- packages/file_selector/file_selector_web/CHANGELOG.md
- packages/file_selector/file_selector_web/example/integration_test/dom_helper_test.dart
- packages/file_selector/file_selector_web/example/integration_test/file_selector_web_test.dart
- packages/file_selector/file_selector_web/lib/src/dom_helper.dart
- packages/file_selector/file_selector_web/pubspec.yaml
- packages/image_picker/image_picker_platform_interface/CHANGELOG.md
- packages/image_picker/image_picker_platform_interface/lib/src/types/picked_file/html.dart
- packages/image_picker/image_picker_platform_interface/pubspec.yaml
- packages/web_benchmarks/CHANGELOG.md
- packages/web_benchmarks/lib/client.dart
- packages/web_benchmarks/lib/src/recorder.dart
- packages/web_benchmarks/pubspec.yaml
This PR removes a bunch of deprecated APIs from the following packages:
* `web_benchmarks`
* `file_selector_web`
* `cross_file`
* `image_picker_platform_interface`
* Fixes https://github.com/flutter/flutter/issues/143113
* Fixes https://github.com/flutter/flutter/issues/143399
* Fixes https://github.com/flutter/flutter/issues/143878
* Fixes https://github.com/flutter/flutter/issues/143892
* Closes https://github.com/flutter/packages/pull/5248
[CLA]: …
> [web] Removes a few deprecated API usages.

- packages/camera/camera_platform_interface/CHANGELOG.md
- packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart
- packages/camera/camera_platform_interface/pubspec.yaml
Documents `getExposureOffsetStepSize` to return -1 if the device does not support exposure compensation. Helps account for `camera_android_camerax` since CameraX does not return a step size if exposure compensation is not supported.
A follow up to [this discussion](https://github.com/flutter/packages/pull/6059#discussion_r1481839497).
[Discord]: …
> [camera] Document -1 return value for `getExposureOffsetStepSize`

- script/tool/lib/src/format_command.dart
- script/tool/test/format_command_test.dart
This file fails `swift-format lint`, so including it in `format` causes lots of warnings when run locally.
> [tool] Ignore GeneratedPluginRegistrant.swift for `format`

- packages/url_launcher/url_launcher_ios/CHANGELOG.md
- packages/url_launcher/url_launcher_ios/ios/Classes/Launcher.swift
- packages/url_launcher/url_launcher_ios/ios/Classes/URLLauncherPlugin.swift
- packages/url_launcher/url_launcher_ios/pubspec.yaml
When trying to compile url_launcher_ios as an independent library (for instance, when using Bazel/Blaze) compilation fails due to a missing UIKit import. Presumably this is not a problem when using the Flutter build tools because UIKit is included implicitly.
> [url_launcher] Add explicit imports of UIKit

- packages/pigeon/CHANGELOG.md
- packages/pigeon/lib/generator_tools.dart
- packages/pigeon/lib/kotlin_generator.dart
- packages/pigeon/lib/pigeon_lib.dart
- packages/pigeon/platform_tests/test_plugin/android/src/main/kotlin/com/example/test_plugin/CoreTests.gen.kt
- packages/pigeon/platform_tests/test_plugin/android/src/main/kotlin/com/example/test_plugin/TestPlugin.kt
- packages/pigeon/pubspec.yaml
- packages/pigeon/tool/shared/generation.dart
Allows kotlin generator to skip error class generation by creating `includeErrorClass` argument.
This may be considered only a partial fix, as it requires another pigeon file with the class generated rather than creating a new file with the class.
This solution seems to me to solve the problem well enough as creating another file is a non-trivial task and there is already a working solution - renaming the error class per file.
fixes: https://github.com/flutter/flutter/issues/142099 …
> [pigeon] Allows kotlin generator to skip error class generation

- packages/pigeon/CHANGELOG.md
- packages/pigeon/example/app/README.md
- packages/pigeon/example/app/windows/runner/messages.g.cpp
- packages/pigeon/lib/cpp_generator.dart
- packages/pigeon/lib/generator_tools.dart
- packages/pigeon/platform_tests/test_plugin/example/windows/flutter/CMakeLists.txt
- packages/pigeon/platform_tests/test_plugin/windows/pigeon/core_tests.gen.cpp
- packages/pigeon/pubspec.yaml
- packages/pigeon/test/cpp_generator_test.dart
Please let me know if I goofed anything, this is my first time contributing to Pigeon!
Addresses https://github.com/flutter/flutter/issues/144042 …
> [pigeon] Remove heap allocation in generated C++ code

- packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/google_maps_controller_test.dart
- packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/marker_test.dart
- packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/markers_test.dart
- packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/overlay_test.dart
- packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/overlays_test.dart
- packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/shapes_test.dart
- packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/test_utils.dart
- packages/google_maps_flutter/google_maps_flutter_web/example/lib/main.dart
- packages/google_maps_flutter/google_maps_flutter_web/example/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_web/lib/google_maps_flutter_web.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/convert.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/dom_window_extension.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/google_maps_controller.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/map_styler.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/marker.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/markers.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/overlay.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/utils.dart
- packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml
This PR migrates `google_maps_flutter_web` from `dart:html` to `package:web`.
The `google_maps` package does provide a beta version with support for `package:web`, which is currently what this PR is depending on. Before landing this change, we should change the dependency to the stable release version of that package.
Fixes https://github.com/flutter/flutter/issues/137374
N/A …
> [google_maps_flutter_web] Migrate to package:web

- packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/dom_window_extension.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/map_styler.dart
- packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml
These are needed for 3.3 in order to address issue https://github.com/dart-lang/sdk/issues/54801. This commit also cleans up some unnecessary annotations.
Also publishes 0.5.7.
https://github.com/dart-lang/sdk/issues/55039
> Add library annotations for js interop

- packages/google_maps_flutter/google_maps_flutter_platform_interface/AUTHORS
- packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/events/map_event.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/method_channel/method_channel_google_maps_flutter.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/platform_interface/google_maps_flutter_platform.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/platform_interface/google_maps_inspector_platform.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/cluster.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/cluster_manager.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/cluster_manager_updates.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/map_objects.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/marker.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/types.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/utils/cluster_manager.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/platform_interface/google_maps_flutter_platform_test.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/cluster_manager_test.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/cluster_test.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/marker_test.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/utils/cluster_manager_test.dart
This PR introduces support for marker clustering
This is prequel PR for: https://github.com/flutter/packages/pull/4319
Containing only changes to `google_maps_flutter_platform_interface` package.
Follow up PR:s will hold the platform and app-facing plugin implementations.
Linked issue: https://github.com/flutter/flutter/issues/26863 …
> [google_maps_flutter] Add support for marker clustering - platform interface

- packages/in_app_purchase/in_app_purchase_storekit/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_storekit/darwin/Classes/FIAPReceiptManager.m
- packages/in_app_purchase/in_app_purchase_storekit/example/shared/RunnerTests/InAppPurchasePluginTests.m
- packages/in_app_purchase/in_app_purchase_storekit/pubspec.yaml
The native code did not convert the integer `code` returned from `FIAObjectTranslator getMapFromNSError` to a string before passing it to `FlutterError errorWithCode`. This allowed an `int` to flow into a position where the corresponding Dart code expects a `String`.
Fixes https://github.com/flutter/flutter/issues/144595 …
> [in_app_purchase_storekit] Fix type of error code returned from native code in `SKReceiptManager.retrieveReceiptData`

- packages/google_identity_services_web/CHANGELOG.md
- packages/google_identity_services_web/example/pubspec.yaml
- packages/google_identity_services_web/lib/src/js_interop/package_web_tweaks.dart
- packages/google_identity_services_web/lib/src/js_loader.dart
- packages/google_identity_services_web/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/convert.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/dom_window_extension.dart
- packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml
During the `package:web` migration, some packages that needed the TrustedTypes API defined those as custom JS-interop.
In `google_identity_services_web`, the names of the JS-interop types clashed with those from the incoming package:web, breaking the build.
In `google_maps_flutter_web`, the whole definition code is redundant now that the standard API is exposed through package:web.
Part of: https://github.com/flutter/flutter/issues/117022
[CLA]: …
> [web] Use TrustedTypes from pkg web.

- script/tool/lib/src/common/package_command.dart
- script/tool/lib/src/publish_command.dart
- script/tool/test/common/package_command_test.dart
- script/tool/test/publish_command_test.dart
Adds the flowing to the tool:
- A new `--exact-match-only` flag to be used with `--packages` to prevent group matching (i.e., a selection like `--packages=path_provider --exact-match-only` would only run on `packages/path_provider/path_provider`, not `packages/path_provider/*`).
- Two new `publish` command flags:
- `--tag-for-auto-publish`, to do all the steps that `publish` currently does except for the real `pub publish`, so it would dry-run the publish and then create and push the tag if successful.
- `--already-tagged`, to skip the step of adding and pushing a tag, and replace it with a check that `HEAD` already has the expected tag.
This set of additions supports a workflow where the current `release` step is changed to use `--tag-for-auto-publish`, and then the separate auto-publish …
> [tool] Add features to support GCB auto-publish flow

- packages/rfw/CHANGELOG.md
- packages/rfw/lib/src/flutter/core_widgets.dart
- packages/rfw/lib/src/flutter/runtime.dart
- packages/rfw/test/core_widgets_test.dart
- packages/rfw/test_coverage/bin/test_coverage.dart
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-ch …
> [rfw] Change test coverage logic to enforce 100% coverage

- packages/in_app_purchase/in_app_purchase_storekit/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_storekit/darwin/Classes/FIAObjectTranslator.m
- packages/in_app_purchase/in_app_purchase_storekit/example/shared/RunnerTests/TranslatorTests.m
- packages/in_app_purchase/in_app_purchase_storekit/pubspec.yaml
The native userInfo object can contain nested dictionaries. Previously this information was lost because `FIAObjectTranslator encodeNSErrorUserInfo` did not handle `NSDictionary`s.
Fixes https://github.com/flutter/flutter/issues/138407
[Discord]: …
> [in_app_purchase_storekit] Handle translation of errors nested in dictionaries

- packages/two_dimensional_scrollables/CHANGELOG.md
- packages/two_dimensional_scrollables/lib/src/table_view/table.dart
- packages/two_dimensional_scrollables/pubspec.yaml
- packages/two_dimensional_scrollables/test/table_view/table_test.dart
Fixes https://github.com/flutter/flutter/issues/144100
Picks up doc fix from https://github.com/flutter/packages/pull/6154 as well …
> [two_dimensional_scrollables] Fix another combo of pinned/unpinned merged TableViewCells

- packages/pigeon/CHANGELOG.md
- packages/pigeon/lib/generator_tools.dart
- packages/pigeon/lib/objc_generator.dart
- packages/pigeon/platform_tests/alternate_language_test_plugin/example/ios/RunnerTests/AllDatatypesTest.m
- packages/pigeon/platform_tests/alternate_language_test_plugin/example/ios/RunnerTests/AsyncHandlersTest.m
- packages/pigeon/platform_tests/alternate_language_test_plugin/example/ios/RunnerTests/ListTest.m
- packages/pigeon/platform_tests/alternate_language_test_plugin/ios/Classes/AlternateLanguageTestPlugin.h
- packages/pigeon/platform_tests/alternate_language_test_plugin/ios/Classes/AlternateLanguageTestPlugin.m
- packages/pigeon/platform_tests/alternate_language_test_plugin/ios/Classes/CoreTests.gen.h
- packages/pigeon/platform_tests/alternate_language_test_plugin/ios/Classes/CoreTests.gen.m
- packages/pigeon/pubspec.yaml
- packages/pigeon/test/objc_generator_test.dart
- packages/pigeon/tool/shared/generation.dart
In some areas of the Objc generator, the the name created from [_objcTypeForDartType](https://github.com/flutter/packages/blob/main/packages/pigeon/lib/objc_generator.dart#L1353) is being passed to [_enumName](https://github.com/flutter/packages/blob/main/packages/pigeon/lib/objc_generator.dart#L1196) and both of these methods add a prefix to enums. The locations are when they are used in `HostApi` or `FlutterApi` methods, but the name of the generated enum would be correct. e.g. `FLTEnumName` vs `FLTFLTEnumName`.
This fixes the locations where this is happening by passing the AST name to `_enumName` instead. 
[Tree …
> [pigeon] Fixes double prefixes added to enum names for Objc HostApis and FlutterApis

- packages/flutter_adaptive_scaffold/CHANGELOG.md
- packages/flutter_adaptive_scaffold/README.md
- packages/flutter_adaptive_scaffold/pubspec.yaml
The document this linked to is no longer accessible (possibly overrun with spam?), and we don't have a way to recover it. Given that, remove the link.
Fixes https://github.com/flutter/flutter/issues/145292 …
> [flutter_adaptive_scaffold] Remove broken link from README

- script/tool/lib/src/podspec_check_command.dart
- script/tool/test/podspec_check_command_test.dart
Adds `--allow-warnings` to podspec_check_command.dart so stuff can keep rolling.
**To be removed soon!** …
> [ci] Temporarily allow-warnings in podspec_check_command.dart

- packages/google_sign_in/google_sign_in_ios/CHANGELOG.md
- packages/google_sign_in/google_sign_in_ios/darwin/google_sign_in_ios.podspec
- packages/google_sign_in/google_sign_in_ios/pubspec.yaml
This PR temporarily pins the GoogleSignIn iOS SDK to version 7.0.0 in the darwin podspec configuration.
This'll enable our CI to keep going, until a more proper fix to `google_sign_in_ios` lands, with an update to the latest [7.1 version](https://github.com/google/GoogleSignIn-iOS/releases). See:
* https://github.com/flutter/flutter/issues/145866
For more information about the current CI failures.
This PR should help with the tests that are currently broken in CI. …
> [google_sign_in_ios] Pins GoogleSignIn to 7.0.0 in podspec.

- .github/workflows/release.yml
As suggested in flutter/flutter#137299:
* Adds a 1 minute sleep to our `release.yml` workflow so LUCI checks have time to be populated through the GitHub Webhooks, before attempting to look at them.
This will make the `release` action a little bit slower, but hopefully much more reliable.
* Fixes flutter/flutter#137299 …
> [ci] Adds sleep 60s to release action.

- packages/camera/camera_android_camerax/CHANGELOG.md
- packages/camera/camera_android_camerax/pubspec.yaml
Fixes flutter/flutter/issues/145992
> [camera_android_camerax] Move integration_test dependency to tests

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/example/lib/main.dart
- packages/camera/camera_avfoundation/pubspec.yaml
- packages/flutter_markdown/CHANGELOG.md
- packages/flutter_markdown/lib/src/builder.dart
- packages/flutter_markdown/pubspec.yaml
- packages/flutter_markdown/test/utils.dart
- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/lib/video_player.dart
- packages/video_player/video_player/pubspec.yaml
- packages/video_player/video_player/test/video_player_test.dart
It's no longer needed - for now.
Fixes https://github.com/flutter/flutter/issues/111841.
> [various] Remove all traces of the `_ambiguate` workaround

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/README.md
- packages/video_player/video_player/example/lib/basic.dart
- packages/video_player/video_player/pubspec.yaml
As per https://api.flutter.dev/flutter/widgets/State/dispose.html
> Implementations of this method should end with a call to the inherited method, as in super.dispose().
> [video_player] Call `super.dispose` last in README example

- packages/image_picker/image_picker_platform_interface/CHANGELOG.md
- packages/image_picker/image_picker_platform_interface/lib/src/method_channel/method_channel_image_picker.dart
- packages/image_picker/image_picker_platform_interface/lib/src/types/media_options.dart
- packages/image_picker/image_picker_platform_interface/lib/src/types/multi_image_picker_options.dart
- packages/image_picker/image_picker_platform_interface/pubspec.yaml
- packages/image_picker/image_picker_platform_interface/test/media_options_test.dart
- packages/image_picker/image_picker_platform_interface/test/method_channel_image_picker_test.dart
- packages/image_picker/image_picker_platform_interface/test/multi_image_picker_options_test.dart
Adds limit parameter to `MediaOptions` and `MultiImagePickerOptions`. The `limit` argument defines how many images or media files can be select.
Only platform interface package changes taken from: https://github.com/flutter/packages/pull/6201
Fixes: [flutter/flutter#85772](https://github.com/flutter/flutter/issues/85772) …
> Add limit to image_picker_platform_interface

- packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_android/android/src/main/java/io/flutter/plugins/inapppurchase/Messages.java
- packages/in_app_purchase/in_app_purchase_android/android/src/main/java/io/flutter/plugins/inapppurchase/MethodCallHandlerImpl.java
- packages/in_app_purchase/in_app_purchase_android/android/src/main/java/io/flutter/plugins/inapppurchase/PluginPurchaseListener.java
- packages/in_app_purchase/in_app_purchase_android/android/src/main/java/io/flutter/plugins/inapppurchase/Translator.java
- packages/in_app_purchase/in_app_purchase_android/android/src/test/java/io/flutter/plugins/inapppurchase/MethodCallHandlerTest.java
- packages/in_app_purchase/in_app_purchase_android/android/src/test/java/io/flutter/plugins/inapppurchase/TranslatorTest.java
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/alternative_billing_only_reporting_details_wrapper.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/billing_client_wrapper.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/billing_config_wrapper.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/billing_response_wrapper.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/one_time_purchase_offer_details_wrapper.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/product_details_wrapper.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/purchase_wrapper.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/subscription_offer_details_wrapper.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/user_choice_details_wrapper.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/messages.g.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/pigeon_converters.dart
- packages/in_app_purchase/in_app_purchase_android/pigeons/messages.dart
- packages/in_app_purchase/in_app_purchase_android/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_android/test/billing_client_wrappers/billing_client_wrapper_test.dart
- packages/in_app_purchase/in_app_purchase_android/test/billing_client_wrappers/billing_client_wrapper_test.mocks.dart
- packages/in_app_purchase/in_app_purchase_android/test/in_app_purchase_android_platform_addition_test.dart
- packages/in_app_purchase/in_app_purchase_android/test/in_app_purchase_android_platform_test.dart
- packages/in_app_purchase/in_app_purchase_android/test/test_conversion_utils.dart
Follow-up to https://github.com/flutter/packages/pull/6262, converting the nested data objects from the legacy JSON conversion to typed Pigeon objects.
Deprecates all the JSON code in the wrapper objects, but does not remove it because, unfortunately, the wrapper objects were both platform data transfer objects *and* the public API surface, so the JSON serialization/deserialization code that was part of those objects for platform channel usage is part of the public API as well. At some point we can do a breaking change to clean up that code (https://github.com/flutter/flutter/issues/146202).
Fixes https://github.com/flutter/flutter/issues/117910 …
> [in_app_purchase] Convert Android data objects to Pigeon

- packages/flutter_plugin_android_lifecycle/CHANGELOG.md
- packages/flutter_plugin_android_lifecycle/pubspec.yaml
- packages/path_provider/path_provider_android/CHANGELOG.md
- packages/path_provider/path_provider_android/pubspec.yaml
Release some compileSdk changes made in https://github.com/flutter/packages/pull/5783
See also https://github.com/flutter/packages/pull/5783#issuecomment-2034850385 …
> Release compileSdk changes

- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/pubspec.yaml
- packages/path_provider/path_provider/CHANGELOG.md
- packages/path_provider/path_provider/pubspec.yaml
- packages/shared_preferences/shared_preferences/CHANGELOG.md
- packages/shared_preferences/shared_preferences/pubspec.yaml
- packages/url_launcher/url_launcher/CHANGELOG.md
- packages/url_launcher/url_launcher/pubspec.yaml
- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/pubspec.yaml
Updated multiple packages `pubspec.yaml` to depend on iOS implementation versions that include privacy manifest required by Apple. I touched packages that were referenced in https://github.com/flutter/flutter/issues/131940 issue. 
The reason to do this change is that in a few projects I noticed that updating `url_launcher` dependency to the currently latest 6.2.5 doesn't also update `url_launcher_ios` to version with privacy manifest (appeared in 6.2.4) included in the plugin's `pubspec.yaml` it is declared as `^6.2.0`, thus, version resolution picks 6.2.0 and that is it.
Considering that there is already a deadline of May 1, 2024 from Apple on when apps would have to include privacy manifests, it would be good to let devs already prepare their projects. This change should be especially …
> Update multiple packages to depend on versions with iOS privacy manifest included

- packages/google_sign_in/google_sign_in_ios/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/pointer_interceptor/pointer_interceptor_ios/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/video_player/video_player/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/video_player/video_player_avfoundation/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
fixes https://github.com/flutter/flutter/issues/146358
- [] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
> [packages] Set parallelizable to NO to reduce test flakiness in packages project tests

- packages/go_router/CHANGELOG.md
- packages/go_router/example/lib/shell_route.dart
- packages/go_router/example/lib/shell_route_top_route.dart
- packages/go_router/pubspec.yaml
- packages/go_router/test/go_router_state_test.dart
- packages/go_router_builder/CHANGELOG.md
- packages/go_router_builder/example/lib/all_types.dart
- packages/go_router_builder/example/lib/shell_route_example.dart
- packages/go_router_builder/example/lib/shell_route_with_keys_example.dart
- packages/go_router_builder/example/lib/shell_route_with_observers_example.dart
- packages/go_router_builder/example/test/all_types_test.dart
- packages/go_router_builder/pubspec.yaml
This PR updates examples to use `uri.path` instead of `uri.toString()` for accessing the current location.
While the examples don't use deep linking, promoting the usage of `uri.toString()` in the examples doesn't seem to be a good idea as it can lead to issues when it's used with deep links (It'll include host and scheme).
[Discord]: …
> Access current location using uri.path to support deep links

- packages/file_selector/file_selector_ios/CHANGELOG.md
- packages/file_selector/file_selector_ios/example/ios/Podfile
- packages/file_selector/file_selector_ios/example/ios/Runner.xcodeproj/project.pbxproj
- packages/file_selector/file_selector_ios/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/file_selector/file_selector_ios/example/ios/RunnerTests/FileSelectorTests.m
- packages/file_selector/file_selector_ios/ios/Classes/FFSFileSelectorPlugin.m
- packages/file_selector/file_selector_ios/ios/Classes/FFSFileSelectorPlugin_Test.h
- packages/file_selector/file_selector_ios/pubspec.yaml
To aid in future conversion to Swift, remove the use of OCMock in favor of a protocol and an explicit stub.
[exempt from …
> [file_selector] Remove OCMock from iOS implementation

- packages/flutter_markdown/CHANGELOG.md
- packages/flutter_markdown/lib/src/builder.dart
- packages/flutter_markdown/pubspec.yaml
- packages/flutter_markdown/test/image_test.dart
Gracefully handle parsing failures for image width and height in Markdown. Unit tests are provided.
Fixes https://github.com/flutter/flutter/issues/146739 …
> Fix error in markdown parsing image dimensions

- packages/local_auth/local_auth_android/CHANGELOG.md
- packages/local_auth/local_auth_android/android/build.gradle
- packages/local_auth/local_auth_android/pubspec.yaml
https://github.com/flutter/packages/pull/6506 was supposed to update everything to 19+, but missed local_auth_android. This updates it to require 19 as well.
> Update local_auth_android minSdkVersion to 19

- packages/video_player/video_player_android/CHANGELOG.md
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
- packages/video_player/video_player_android/example/android/app/src/test/java/io/flutter/plugins/videoplayerexample/FlutterActivityTest.java
- packages/video_player/video_player_android/pubspec.yaml
In the `onDetachedFromEngine` function, the `onDestroy` method should be called instead of the `initialize` method, even though the implementation of the two functions is no different.
```java
private void onDestroy() {
// The whole FlutterView is being destroyed. Here we release resources acquired for all
// instances
// of VideoPlayer. Once https://github.com/flutter/flutter/issues/19358 is resolved this may
// be replaced with just asserting that videoPlayers.isEmpty().
// https://github.com/flutter/flutter/issues/20989 tracks this.
disposeAllPlayers();
}
public void initialize() {
disposeAllPlayers();
}
```
[Tree …
> [video_player] Calls `onDestroy` instead of `initialize` in onDetachedFromEngine

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/pubspec.yaml
- script/tool/lib/src/pubspec_check_command.dart
- script/tool/test/pubspec_check_command_test.dart
- Adds `build_runner`, `mockito`, and `pigeon` to the list of dependencies that we expect to only be in dev_dependencies.
- Fixes the error message for violations; I had missed in initial review that the errorr message was the same as the one for non-repo-local depndencies, making it misleading about what the problem was and how to fix it. (Also fixed the indentation, which had always been wrong.)
- Fixes `camera_avfoundation`, which had a violation introduced in my recent PR to start the Pigeon conversion.
See https://github.com/flutter/flutter/issues/117905 …
> [ci] Add more dev dependency checks, and fix errors

- packages/pointer_interceptor/pointer_interceptor_web/example/integration_test/widget_test.dart
After discussing with @yjbanov, we've decided to remove the semantics-related tests from the `pointer_interceptor_web` package.
The tests are no better than general platform view semantics tests in general, and should belong only to the framework/engine.
* Closes https://github.com/flutter/flutter/issues/145238 …
> [pointer_interceptor_web] Remove semantic tests.

- packages/image_picker/image_picker_ios/CHANGELOG.md
- packages/image_picker/image_picker_ios/example/ios/RunnerTests/ImageUtilTests.m
- packages/image_picker/image_picker_ios/ios/Classes/FLTImagePickerImageUtil.m
- packages/image_picker/image_picker_ios/pubspec.yaml
Fix https://github.com/flutter/flutter/issues/146682
Pre-launch Checklist …
> [image_picker] Fix If imageToScale is nil, the app will crash (#146682)

- .ci/legacy_project/README.md
- .ci/legacy_project/all_packages/android/build.gradle
- .ci/legacy_project/all_packages/android/gradle/wrapper/gradle-wrapper.properties
Upgrades legacy all_packages project AGP version to 7.0.0 and Gradle version to 7.0.2 as Flutter will begin enforcing supported versions for these Android dependencies.
This was prompted by dependabot AGP version upgrades like https://github.com/flutter/packages/pull/6522 that are failing due to a what a clear warning* describes as a potential issue:
```
Warning: Flutter support for your project's Gradle version (6.7.1) will soon be dropped. Please upgrade your Gradle version to a version of at least 7.0.2 soon.
Alternatively, use the flag "--android-skip-build-dependency-validation" to bypass this check.
Potential fix: Your project's gradle version is typically defined in the gradle wrapper file. By default, this can be found at …
```
> Bump legacy all_packages project AGP version to 7.0.0, Gradle version to 7.0.2

- packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_android/README.md
- packages/in_app_purchase/in_app_purchase_android/pubspec.yaml
- **Add readme info about user choice billing and alternative billing**
Fixes flutter/flutter/issues/144992
> [in_app_purchase_android] Readme update for Alternative billing

- packages/go_router_builder/CHANGELOG.md
- packages/go_router_builder/lib/src/route_config.dart
- packages/go_router_builder/pubspec.yaml
- packages/go_router_builder/test_inputs/statefull_shell_branch_with_observers_data.dart
- packages/go_router_builder/test_inputs/statefull_shell_branch_with_observers_data.dart.expect
This pr added the ability to provide a list of NavigatorObservers to a StatefulShellBranch. 
The equivalent was never added to go_router_builder, so this pr provides that functionality.
With this change, you can provide NavigatorObservers directly to the StatefulShellBranch and fix https://github.com/flutter/flutter/issues/143869. …
> [go_router_builder] add support to go_router_builder for initializing a StatefulShellBranch with observers

- packages/file_selector/file_selector_android/CHANGELOG.md
- packages/file_selector/file_selector_android/LICENSE
- packages/file_selector/file_selector_android/pubspec.yaml
Updates the `LICENSE` file to cover code used in https://github.com/flutter/packages/blob/main/packages/file_selector/file_selector_android/android/src/main/java/dev/flutter/packages/file_selector_android/FileUtils.java, added in https://github.com/flutter/packages/pull/6438. …
> [file_selector_android] Update `LICENSE` file to include newly added licensed code

- packages/google_maps_flutter/google_maps_flutter_android/AUTHORS
- packages/google_maps_flutter/google_maps_flutter_android/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_android/android/build.gradle
- packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/ClusterManagersController.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapBuilder.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapFactory.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapOptionsSink.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/MarkerBuilder.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/MarkerController.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/MarkersController.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/test/java/io/flutter/plugins/googlemaps/ClusterManagersControllerTest.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/test/java/io/flutter/plugins/googlemaps/ConvertTest.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/test/java/io/flutter/plugins/googlemaps/GoogleMapControllerTest.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/test/java/io/flutter/plugins/googlemaps/MarkersControllerTest.java
- packages/google_maps_flutter/google_maps_flutter_android/example/android/app/build.gradle
- packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/google_maps_tests.dart
- packages/google_maps_flutter/google_maps_flutter_android/example/lib/clustering.dart
- packages/google_maps_flutter/google_maps_flutter_android/example/lib/example_google_map.dart
- packages/google_maps_flutter/google_maps_flutter_android/example/lib/main.dart
- packages/google_maps_flutter/google_maps_flutter_android/example/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_android/example/test/fake_google_maps_flutter_platform.dart
- packages/google_maps_flutter/google_maps_flutter_android/lib/src/google_map_inspector_android.dart
- packages/google_maps_flutter/google_maps_flutter_android/lib/src/google_maps_flutter_android.dart
- packages/google_maps_flutter/google_maps_flutter_android/lib/src/utils/cluster_manager_utils.dart
- packages/google_maps_flutter/google_maps_flutter_android/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_android/test/cluster_manager_utils_test.dart
This PR introduces support for marker clustering for Android platform
An example usage is available in the example application at `./packages/google_maps_flutter/google_maps_flutter_android/example` on the page `Manage clustering`
This is prequel PR for: https://github.com/flutter/packages/pull/4319
and sequel PR for: https://github.com/flutter/packages/pull/6158
Containing only changes to `google_maps_flutter_android` package.
Follow up PR will hold the app-facing plugin implementation.
Linked issue: https://github.com/flutter/flutter/issues/26863 …
> [google_maps_flutter] Add marker clustering support - android implementation

- packages/google_maps_flutter/google_maps_flutter_web/AUTHORS
- packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_web/README.md
- packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/google_maps_controller_test.mocks.dart
- packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/google_maps_plugin_test.dart
- packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/google_maps_plugin_test.mocks.dart
- packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/marker_clustering_test.dart
- packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/markers_test.dart
- packages/google_maps_flutter/google_maps_flutter_web/example/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_web/example/web/index.html
- packages/google_maps_flutter/google_maps_flutter_web/lib/google_maps_flutter_web.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/convert.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/google_maps_controller.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/google_maps_flutter_web.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/google_maps_inspector_web.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/marker.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/marker_clustering.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/marker_clustering_js_interop.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/markers.dart
- packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml
This PR introduces support for marker clustering for Web platform
This is prequel PR for: https://github.com/flutter/packages/pull/4319
and sequel PR for: https://github.com/flutter/packages/pull/6158
Containing only changes to `google_maps_flutter_web` package.
Follow up PR will hold the app-facing plugin implementation.
Linked issue: https://github.com/flutter/flutter/issues/26863 …
> [google_maps_flutter] Add marker clustering support - web implementation

- packages/go_router_builder/CHANGELOG.md
- packages/go_router_builder/lib/src/type_helpers.dart
- packages/go_router_builder/pubspec.yaml
This PR slightly tweaks `go_router_builder` to work with `analyzer-6.5.0` and unblock post-submit [errors](https://github.com/flutter/packages/runs/24440595710).
* Should fix failing tests after this merge: https://github.com/flutter/packages/pull/6631
[Discord]: …
> [go_router_builder] Tweaks for latest analyzer-6.5.0

- script/tool/lib/src/podspec_check_command.dart
- script/tool/test/podspec_check_command_test.dart
Fix for iOS was added in https://github.com/flutter/packages/pull/6627, but neglected to handle when plugin uses darwin directory.
Supplemental fix for https://github.com/flutter/flutter/issues/147548.
[linked to …
> Skip podspec Swift Search Path validation if only swift file is Package.swift for darwin plugins

- packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_android/lib/src/in_app_purchase_android_platform.dart
- packages/in_app_purchase/in_app_purchase_android/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_android/test/in_app_purchase_android_platform_test.dart
- packages/in_app_purchase/in_app_purchase_storekit/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_storekit/lib/src/in_app_purchase_storekit_platform.dart
- packages/in_app_purchase/in_app_purchase_storekit/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_storekit/test/in_app_purchase_storekit_platform_test.dart
- **Rename getCountryCode to country code for ios and android IAP**
- **Add changelog**
fixes https://github.com/flutter/flutter/issues/147230
> [in_app_purchase] implement countryCode correctly

- .ci.yaml
We only need enough recipe CQ coverage to cover the platforms and functionality in the recipes, which doesn't require running so many of our tests there (especially multiple shards of the same test). This reduces the number of tasks in the recipe CQ, while still keeping broad coverage of different kinds of functionality.
> [ci] Reduce the number of tasks in recipe CQ

- packages/camera/camera_android_camerax/CHANGELOG.md
- packages/camera/camera_android_camerax/lib/src/android_camera_camerax.dart
- packages/camera/camera_android_camerax/pubspec.yaml
- packages/camera/camera_android_camerax/test/android_camera_camerax_test.dart
Adds empty implementation for the camera plugin method `prepareForVideoRecording` that is not used on Android.
Prequel to https://github.com/flutter/packages/pull/6629 …
> [camerax] Add empty implementation for `prepareForVideoRecording` not used on Android

- packages/go_router/lib/src/parser.dart
- packages/go_router_builder/CHANGELOG.md
- packages/go_router_builder/example/lib/main.dart
- packages/go_router_builder/pubspec.yaml
Prepares for a fix to the `use_build_context_synchronously` lint (https://dart-review.googlesource.com/c/sdk/+/365541) that will complain about these unsafe usages.
> [go_router] guard context access in then clauses

- packages/flutter_lints/CHANGELOG.md
- packages/flutter_lints/pubspec.yaml
To be submitted after https://github.com/dart-lang/lints/pull/184 is published.
> [flutter_lints] Rev to 4.0.0; prepare for publishing

- .gitignore
The following directories were created when I added SPM support to the `ios_platform_images` plugin:
```
packages/ios_platform_images/ios/ios_platform_images/.build/
packages/ios_platform_images/ios/ios_platform_images/.swiftpm/
```
These shouldn't be checked-in to the packages repository.
Part of https://github.com/flutter/flutter/issues/148018 …
> Update .gitignore for Swift Package Manager

- packages/camera/camera_android_camerax/CHANGELOG.md
- packages/camera/camera_android_camerax/README.md
- packages/camera/camera_android_camerax/android/src/main/java/io/flutter/plugins/camerax/GeneratedCameraXLibrary.java
- packages/camera/camera_android_camerax/android/src/main/java/io/flutter/plugins/camerax/PendingRecordingFlutterApiImpl.java
- packages/camera/camera_android_camerax/android/src/main/java/io/flutter/plugins/camerax/PendingRecordingHostApiImpl.java
- packages/camera/camera_android_camerax/android/src/test/java/io/flutter/plugins/camerax/PendingRecordingTest.java
- packages/camera/camera_android_camerax/example/integration_test/integration_test.dart
- packages/camera/camera_android_camerax/lib/src/android_camera_camerax.dart
- packages/camera/camera_android_camerax/lib/src/camerax_library.g.dart
- packages/camera/camera_android_camerax/lib/src/pending_recording.dart
- packages/camera/camera_android_camerax/pigeons/camerax_library.dart
- packages/camera/camera_android_camerax/pubspec.yaml
- packages/camera/camera_android_camerax/test/android_camera_camerax_test.dart
- packages/camera/camera_android_camerax/test/test_camerax_library.g.dart
Makes changes needed to land https://github.com/flutter/packages/pull/6629. Specifically:
- Fixes timing issue with `stopVideoRecording` such that the `Future` it returns will only complete when CameraX reports that the recording is finalized (via listening for the [finalized video recording event](https://developer.android.com/reference/androidx/camera/video/VideoRecordEvent.Finalize))
- Modifies `startVideoCapturing` such that the `Future` it returns will only complete when CameraX reports that video capturing has started (via listening for the [started video recording event](https://developer.android.com/reference/androidx/camera/video/VideoRecordEvent.Start))
- Adds empty implementation and TODO for implementing `setDescriptionWhileRecording` …
> [camerax] Make fixes required to swap camera_android_camerax for camera_android

- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart
This test has started failing consistently on post-submit. See https://github.com/flutter/flutter/issues/148345
> [webview_flutter_wkwebview] Skip `withWeakReferenceTo` integration test

- packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart
Temporary solution for https://github.com/flutter/flutter/issues/148487 to unblock tree.
[pub …
> [webview_flutter] Skip "Video playback policy" drive tests

- packages/camera/camera_avfoundation/example/ios/Runner.xcodeproj/project.pbxproj
Introduced in https://github.com/flutter/packages/pull/3272/files#diff-92a81cce4f20ea0f44193e7f760655d78f05a720378e1e085a244472fb85fc04R656
Put the bundle ID back to what it was.
> [camera_avfoundation] Revert camera example PRODUCT_BUNDLE_IDENTIFIER

- packages/rfw/CHANGELOG.md
- packages/rfw/lib/src/flutter/argument_decoders.dart
- packages/rfw/pubspec.yaml
- packages/rfw/test/argument_decoders_test.dart
And hard-codes filter qualities in tests to prepare for https://github.com/flutter/flutter/pull/148799, which switches the default to `medium`. This hard-codes a filter quality in the test so the test passes no matter what the default is.
> [rfw] Adds support for `DecorationImage.filterQuality`.

- .ci.yaml
Now that `google_maps_flutter` supports ARM simulators, we should be able to move this task to ARM. This adds the ARM version in bringup mode, with a new name to reflect the fact that it is doing more that just checking podspecs now.
Once this propagates and is green, the x64 version will be removed.
Part of https://github.com/flutter/flutter/issues/141493
> [ci] Start moving podspec check to ARM

- packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/bitmap.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/marker.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/bitmap_test.dart
This PR adds improvements to BitmapDescriptor API for google_maps_flutter_platform_interface 
* Adds better support for marker size and scaling behaviour with `AssetMapBitmap` and `BytesMapBitmap`.
* Deprecates `BitmapDescriptor.fromAssetImage` in favor of `BitmapDescriptor.asset` and `AssetMapBitmap.create`.
* Deprecates `BitmapDescriptor.fromBytes` in favor of `BitmapDescriptor.bytes` and `BytesMapBitmap`
This is prequel PR for: https://github.com/flutter/packages/pull/4055
Containing only changes to `google_maps_flutter_platform_interface` package.
Follow up PR:s will hold the platform and app-facing plugin implementations.
Linked issue: https://github.com/flutter/flutter/issues/34657
[Contributor …
> [google_maps_flutter_platform_interface] Add improvements to BitmapDescriptor API

- packages/go_router/CHANGELOG.md
- packages/go_router/doc/navigation.md
- packages/go_router/pubspec.yaml
[go_router] docs: updated link in navigation.md to correct file path for push_with_shell_route.dart …
> [go_router] docs: updated link in navigation.md to correct file path for push_with_shell_route.dart

- packages/flutter_adaptive_scaffold/CHANGELOG.md
- packages/flutter_adaptive_scaffold/example/lib/main.dart
- packages/flutter_adaptive_scaffold/lib/src/adaptive_scaffold.dart
- packages/flutter_adaptive_scaffold/pubspec.yaml
- packages/rfw/lib/src/flutter/material_widgets.dart
Part of https://github.com/flutter/flutter/issues/148218
Part of https://github.com/flutter/flutter/issues/148361
Migrates off MaterialStateProperty …
> [flutter_adaptive_scaffold] Migrate MaterialStateProperty to WidgetStateProperty

- packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/bitmap.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
Undeprecate BitmapDescriptor.fromAssetImage and BitmapDescriptor.fromBytes
* Undeprecates `BitmapDescriptor.fromAssetImage`.
* Undeprecates `BitmapDescriptor.fromBytes`.
* Fixes issues with deprecation in version 2.7.0.
The new formats won't be supported until https://github.com/flutter/packages/pull/6826 lands.
Deprecation notices can be re-added after the implementation PRs have landed.
Fixes: https://github.com/flutter/flutter/issues/149183 …
> [google_maps_flutter] Undeprecate BitmapDescriptor methods

- packages/camera/camera_android_camerax/CHANGELOG.md
- packages/camera/camera_android_camerax/android/src/main/java/io/flutter/plugins/camerax/CameraXProxy.java
- packages/camera/camera_android_camerax/android/src/main/java/io/flutter/plugins/camerax/PreviewHostApiImpl.java
- packages/camera/camera_android_camerax/android/src/test/java/io/flutter/plugins/camerax/PreviewTest.java
- packages/camera/camera_android_camerax/pubspec.yaml
> Revert "Migrate CameraX from SurfaceTexture to SurfaceProducer."

- packages/image_picker/image_picker/AUTHORS
- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/lib/image_picker.dart
- packages/image_picker/image_picker/pubspec.yaml
- packages/image_picker/image_picker_android/AUTHORS
- packages/image_picker/image_picker_android/CHANGELOG.md
- packages/image_picker/image_picker_android/README.md
- packages/image_picker/image_picker_android/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/147773 …
> [image_picker] Adds comment for the limit parameter

- script/tool/lib/src/native_test_command.dart
- script/tool/lib/src/xcode_analyze_command.dart
- script/tool/test/native_test_command_test.dart
- script/tool/test/xcode_analyze_command_test.dart
On macOS 14, caching seems to be more aggressive with swiftmodules and can cause conflicts between tests. To mitigate this, use `xcodebuild clean` (cleans Derived Data for the project) as part of `xcodebuild analyze` and `xcodebuild test`.
Fixes https://github.com/flutter/flutter/issues/149270. Fixes https://github.com/flutter/flutter/issues/149266.
[Discord]: …
> Clean Xcode project before analyzing and testing

- packages/path_provider/path_provider/example/integration_test/path_provider_test.dart
- packages/path_provider/path_provider_foundation/example/integration_test/path_provider_test.dart
[Sandboxing was recently disabled for macOS CI tests](https://github.com/flutter/flutter/pull/149618). This caused `getApplicationDocumentsDirectory` tests in path_provider to fail because it changes the path.
With sandboxing enabled, the path is `~/Library/Containers/dev.flutter.plugins.pathProviderExample/Data/Documents`. With sandboxing disabled, the path is `~/Documents`, which requires additional permissions to access. 
To workaround, skip verifying a file can be created/deleted and simply validate a path is returned.
Fixes https://github.com/flutter/flutter/issues/149713. …
> [path_provider] Skip verifying sample file on macOS

- packages/google_sign_in/google_sign_in_web/example/lib/button_tester.dart
- packages/google_sign_in/google_sign_in_web/example/lib/src/button_configuration_column.dart
(Cleanup)
While reviewing a separate issue (flutter/flutter#149236), I noticed that the `button_tester` example app hadn't been updated to the latest style of using the `web_only` library to "renderButton".
This PR updates the implementation of the `button_tester` example app to use the `web_only.dart` library from `package:google_sign_in_web`, instead of attempting to access the web-only methods through funky casts.
While I was there, I also changed a couple of things in the selectable options column:
* (Usability) Ensured the "default" value of each option is rendered by default in the option selection as well.
* (Style) Refactored the column of cards to be a `ListView.builder`, rather than a `SingleChildScrollView + Column`.
I haven't deployed this anywhere, but this is what it looks …
> [google_sign_in_web] Update button_tester to use web_only library.

- .ci.yaml
In preparation of upgrading our fleet to macOS 14, allow tests to run on either macOS 13 or 14.
Fixes https://github.com/flutter/flutter/issues/148873. …
> Run tests on macOS 13 or 14

- packages/two_dimensional_scrollables/CHANGELOG.md
- packages/two_dimensional_scrollables/example/lib/tree_view/custom_tree.dart
- packages/two_dimensional_scrollables/example/lib/tree_view/simple_tree.dart
- packages/two_dimensional_scrollables/lib/src/tree_view/tree.dart
- packages/two_dimensional_scrollables/lib/src/tree_view/tree_core.dart
- packages/two_dimensional_scrollables/lib/src/tree_view/tree_delegate.dart
- packages/two_dimensional_scrollables/pubspec.yaml
- packages/two_dimensional_scrollables/test/tree_view/render_tree_test.dart
- packages/two_dimensional_scrollables/test/tree_view/tree_test.dart
This PR adds generics to the callbacks and builders of the TreeView widget. This removes the need to type cast the content of a TreeViewNode.
Fixes https://github.com/flutter/flutter/issues/149656
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/T …
> [two_dimensional_scrollables] Adds generics to the callbacks and builders of TreeView

- packages/video_player/video_player_android/CHANGELOG.md
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
- packages/video_player/video_player_android/android/src/test/java/io/flutter/plugins/videoplayer/VideoPlayerTest.java
- packages/video_player/video_player_android/example/android/app/src/test/java/io/flutter/plugins/videoplayerexample/FlutterActivityTest.java
- packages/video_player/video_player_android/pubspec.yaml
> Revert "Migrate `video_player/android` from `SurfaceTexture`->`SurfaceProducer`."

- packages/pigeon/CHANGELOG.md
- packages/pigeon/lib/cpp_generator.dart
- packages/pigeon/lib/generator_tools.dart
- packages/pigeon/platform_tests/shared_test_plugin_code/lib/integration_tests.dart
- packages/pigeon/platform_tests/test_plugin/windows/pigeon/core_tests.gen.cpp
- packages/pigeon/pubspec.yaml
- packages/pigeon/test/cpp_generator_test.dart
The code generated for Windows (C++) crashes when `null` is passed for a nullable, class-type parameter to a Pigeon method. This fixes that generation, and adds an integration test covering this case since it was missing from the list of types where we echo a `null` in integration tests to catch this kind of issue.
Fixes https://github.com/flutter/flutter/issues/149174 …
> [pigeon] Fix handling of null class args in C++

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/example/integration_test/video_player_test.dart
- packages/video_player/video_player/lib/video_player.dart
- packages/video_player/video_player/pubspec.yaml
This attempts to address two sources of flake:
- A test that playing doesn't continue past the duration flakily fails, at least on Android, with a position a small amount past the duration. This seems like an unexpected library behavior that we wouldn't want to expose to clients, so rather than change the test, this makes the logic that updates the `Value` clamp the position to the duration.
- A test that asset videos play has been restructured to actually wait for the future that should start playing to complete before checking whether it's playing. The test was previously not actually waiting for anything other than animations to complete, and there's no reason the placeholder layout couldn't have completed before the asset loaded. The fact that the test was already disabled for iOS is …
> [video_player] Try to address test flake

- packages/flutter_markdown/CHANGELOG.md
- packages/flutter_markdown/lib/src/builder.dart
- packages/flutter_markdown/pubspec.yaml
- packages/flutter_markdown/test/scrollable_test.dart
Currently all code blocks share the same ScrollController causing an exception when they appear on screen together.  This fixes that situation.
> Ensure each code block specified in the markdown uses its own ScrollController.

- script/tool/lib/src/common/core.dart
- script/tool/lib/src/federation_safety_check_command.dart
- script/tool/lib/src/make_deps_path_based_command.dart
- script/tool/test/federation_safety_check_command_test.dart
Currently if a PR follows the recommended combo PR process for a federated plugin, the main PR will have CI errors that say the PR isn't allowed to do what it is doing, which is confusing, especially to new contributors or reviewers.
This updates the tooling to detect the temporary overrides created by the tooling, and uses that to trigger a different error message that explains that the error is expected, and exists only to prevent accidental landing.
Fixes https://github.com/flutter/flutter/issues/129303
[CLA]: …
> [tool] Provide better CI feedback for combo PRs

- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerCallbacks.java
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerEventCallbacks.java
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
- packages/video_player/video_player_android/android/src/test/java/io/flutter/plugins/videoplayer/VideoPlayerTest.java
Part of https://github.com/flutter/flutter/issues/148417.
I'm working on re-landing https://github.com/flutter/packages/pull/6456, this time without using the `ActivityAware` interface (see https://github.com/flutter/flutter/issues/148417). As part of that work, I'll need to better control the `ExoPlayer` lifecycle and save/restore internal state.
These are some proposed refactors to limit how much work `VideoPlayer` is doing, so I can better understand what needs to be reset (or not) internally. Specifically, `VideoPlayer` no longer knows what an `EventChannel` or `EventSink` is, and does not need to manage the lifecycle (it stores a `private final VideoPlayerCallbacks` instead), and instead there is a `VideoPlayerCallbacks` interface that does all that.
I'm totally open to:
- Landing …
> Refactor `VideoPlayer` to be less exposed to `EventChannel` & related

- packages/pigeon/CHANGELOG.md
- packages/pigeon/platform_tests/test_plugin/example/ios/Runner/AppDelegate.swift
- packages/pigeon/platform_tests/test_plugin/example/ios/RunnerTests/EnumTests.swift
Updating to Xcode 16 exposed a new compilation error: "extension declares a conformance of imported type 'DataWithEnum' to imported protocol 'Equatable'".  The [Swift Warning for Retroactive Conformances of External Types](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0364-retroactive-conformance-warning.md) proposal says:
> It does mean projects building with an older Swift will not have access to [the @retroactive] syntax, so as a source compatible fallback, a client can silence this warning by fully-qualifying all types in the extension. As an example, the above conformance can also be written as
> ```
> extension Foundation.Date: Swift.Identifiable {
>     // ...
> }
> ```
> This will allow projects that need to build with multiple versions of Swift, and which have …
> [pigeon] Fully-qualify types in Equatable extension test

- packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/bitmap.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
Deprecates `BitmapDescriptor.fromAssetImage` in favor of `BitmapDescriptor.asset` and `AssetMapBitmap.create`.
Deprecates `BitmapDescriptor.fromBytes` in favor of `BitmapDescriptor.bytes` and `BytesMapBitmap`
This is part of the implementation of the following federated plugin PR: https://github.com/flutter/packages/pull/4055
Related to issue: https://github.com/flutter/flutter/issues/34657 …
> [google_maps_flutter] deprecate old BitmapDescriptor methods

- packages/camera/camera_android/CHANGELOG.md
- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/Camera.java
- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/MethodCallHandlerImpl.java
- packages/camera/camera_android/android/src/test/java/io/flutter/plugins/camera/CameraTest.java
- packages/camera/camera_android/android/src/test/java/io/flutter/plugins/camera/CameraTest_getRecordingProfileTest.java
- packages/camera/camera_android/pubspec.yaml
Reverts https://github.com/flutter/packages/pull/6461
Resolves https://github.com/flutter/flutter/issues/150549
> Revert "Migrate `camera/android` from `SurfaceTexture`->`SurfaceProducer`."

- packages/pigeon/CONTRIBUTING.md
- packages/pigeon/tool/shared/test_runner.dart
Minor improvements for contributors:
- Explicitly log failure of a test suite. Depeending on the generator and the failure, it may not be obvious (e.g., gtest crashes, which just don't have any output).
- Clarify `test.dart` vs `run_tests.dart`, and mention the `-t` and `-l` flags.
- Add newer generators to the source list. …
> [pigeon] Update testing and docs

- packages/video_player/video_player_android/android/build.gradle
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/LocalVideoAsset.java
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/RemoteVideoAsset.java
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoAsset.java
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerEventCallbacks.java
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
- packages/video_player/video_player_android/android/src/test/java/io/flutter/plugins/videoplayer/ExoPlayerEventListenerTests.java
- packages/video_player/video_player_android/android/src/test/java/io/flutter/plugins/videoplayer/FakeVideoAsset.java
- packages/video_player/video_player_android/android/src/test/java/io/flutter/plugins/videoplayer/VideoAssetTest.java
- packages/video_player/video_player_android/android/src/test/java/io/flutter/plugins/videoplayer/VideoPlayerEventCallbacksTest.java
- packages/video_player/video_player_android/android/src/test/java/io/flutter/plugins/videoplayer/VideoPlayerTest.java
- packages/video_player/video_player_android/example/pubspec.yaml
I'm working on re-landing https://github.com/flutter/packages/pull/6456, this time without using the `ActivityAware` interface (see https://github.com/flutter/flutter/issues/148417). As part of that work, I'll need to better control the `ExoPlayer` lifecycle and save/restore internal state.
Follows the patterns of some of the previous PRs, i.e.
- https://github.com/flutter/packages/pull/6922
- https://github.com/flutter/packages/pull/6908
The changes in this PR are _mostly_ tests, it was extremely difficult to just add more tests to the already very leaky `VideoPlayer` abstraction which had lots of `@VisibleForTesting` methods and other "holes" to observe state. This PR removes all of that, and adds test coverage where it was missing.
Namely it:
- Adds a new class, `VideoAsset`, that …
> Final refactor of `video_player_android` before `SurfaceProducer#setCallback`.

- packages/pigeon/CHANGELOG.md
- packages/pigeon/example/app/android/app/src/main/java/io/flutter/plugins/Messages.java
- packages/pigeon/lib/generator_tools.dart
- packages/pigeon/lib/java_generator.dart
- packages/pigeon/platform_tests/alternate_language_test_plugin/android/src/main/java/com/example/alternate_language_test_plugin/CoreTests.java
- packages/pigeon/platform_tests/alternate_language_test_plugin/android/src/test/java/com/example/alternate_language_test_plugin/AllDatatypesTest.java
- packages/pigeon/pubspec.yaml
Adds implementations of `equals` and `hashCode` to Java data classes. This is frequently useful for native unit tests of plugins using Pigeon (e.g., when using a mock FlutterApi implementation to check that the expected call is being made with the right arguments).
Part of https://github.com/flutter/flutter/issues/118087 …
> [pigeon] Implement equals for Java data classes

- .ci/scripts/build_all_packages_app.sh
- .ci/scripts/create_all_packages_app.sh
- .ci/targets/web_build_all_packages.yaml
- script/configs/exclude_all_packages_app.yaml
- script/configs/exclude_all_packages_app_wasm.yaml
Adds a "--wasm" mode to create and build "all_packages" app to verify all our plugins compile with Wasm.
Except not all do for now, so this also adds a "exclude_all_packages_app_wasm.yaml" file that allows us to remove the packages that aren't fully compatible yet.
* Fixes: https://github.com/flutter/flutter/issues/150748
* Related: https://github.com/flutter/flutter/issues/117022
* Related: https://github.com/flutter/flutter/issues/148624
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#st …
> [ci] Add Wasm compilation to all_packages web app.

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/lib/video_player.dart
- packages/video_player/video_player/pubspec.yaml
- packages/video_player/video_player/test/video_player_initialization_test.dart
- packages/video_player/video_player/test/video_player_test.dart
Exports types `VideoPlayerWebOptions` and `VideoPlayerWebOptionsControls` to customize the `webOptions` field in `VideoPlayerOptions` objects.
Forwards `webOptions` to the web implementation.
Can be used as follows:
```dart
_controller = VideoPlayerController.asset(
'assets/Butterfly-209.mp4',
videoPlayerOptions: const VideoPlayerOptions(
webOptions: VideoPlayerWebOptions(
controls: VideoPlayerWebOptionsControls.enabled(
allowDownload: false,
allowFullscreen: false,
allowPlaybackRate: false,
allowPictureInPicture: false,
),
allowContextMenu: false,
allowRemotePlayback: false,
),
),
);
```
* Fixes: https://github.com/flutter/flutter/issues/150327
* Fixes: https://github.com/flutter/flutter/issues/64397
* Fixes: https://github.com/flutter/flutter/issues/62192
* Fixes part of: …
> [video_player] Exposes VideoPlayerWebOptions.

- packages/google_maps_flutter/google_maps_flutter_ios/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_ios/example/ios14/ios/RunnerTests/FLTGoogleMapJSONConversionsConversionTests.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/FLTGoogleMapJSONConversions.h
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/FLTGoogleMapJSONConversions.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/FLTGoogleMapTileOverlayController.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapCircleController.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapMarkerController.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapPolygonController.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapPolylineController.m
- packages/google_maps_flutter/google_maps_flutter_ios/pubspec.yaml
Eliminates the remaining google_maps_flutter cases of the once-common-in-this-repo type abuse of getting a value from a method channel arguments dictionary that may either be type `T` or `NSNull`, but assigning directly to a variable of type `T`, and then later comparing that variable to `NSNull` with a cast to silence the (correct) warning from the compiler.
Longer term this will be eliminated entirely when the Pigeon conversion is complete, but currently I expect that in the short term we will only do a "shallow" Pigeon conversion (see
https://github.com/flutter/packages/pull/6980 for an Android example), meaning this code will likely stay around for a while. …
> [google_maps_flutter] Fix Obj-C type handling

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/pubspec.yaml
Updates minimum web implementation version to ensure support for the new `webOptions` exposed in the previous release.
* Described here: https://github.com/flutter/flutter/issues/150327#issuecomment-2197399790 …
> [video_player] Bumps web implementation dependency.

- CODEOWNERS
I.e. until https://github.com/flutter/flutter/issues/151018 is completed.
I know this is not foolproof, but I'm hoping it at least keeps me on top of whatever needs to change in the meantime.
> [ci] Adds @matanlurey to some Android CODEOWNERS until Impeller is enabled.

- packages/path_provider/path_provider_windows/CHANGELOG.md
- packages/path_provider/path_provider_windows/lib/src/folders.dart
- packages/path_provider/path_provider_windows/lib/src/guid.dart
- packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart
- packages/path_provider/path_provider_windows/lib/src/win32_wrappers.dart
- packages/path_provider/path_provider_windows/pubspec.yaml
- packages/path_provider/path_provider_windows/test/guid_test.dart
- script/configs/allowed_unpinned_deps.yaml
Per https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#dependencies, we generally do not want third-party dependencies. `path_provider` in particular is a key part of the ecosystem (well over 1,000 packages depend directly on it, and transitively it's probably several times that at least), and thus the maintenance and security considerations are particularly acute.
This eliminates the dependency on `win32`, a large third-party dependency, in favor of direct FFI code written from scratch using the official Win32 reference documentation from Microsoft as the source. The only behavioral change that should result here is that the exceptions thrown in failure cases have changed, but they were never documented, and were entirely platform-specific, so it's …
> [path_provider] Remove `win32`

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/example/ios/RunnerTests/FLTCamSampleBufferTests.m
- packages/camera/camera_avfoundation/ios/Classes/FLTCam.m
- packages/camera/camera_avfoundation/pubspec.yaml
Correctly initialise `_lastVideoSampleTime` and `_lastAudioSampleTime` before first use to avoid propagating invalid (non-numeric) values into methods like `appendPixelBuffer`.
Fixes https://github.com/flutter/flutter/issues/132014 …
> [camera_avfoundation] fix sample times not being numeric after pause/resume.

- packages/google_maps_flutter/google_maps_flutter_ios/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_ios/example/ios14/ios/RunnerTests/FLTGoogleMapJSONConversionsConversionTests.m
- packages/google_maps_flutter/google_maps_flutter_ios/example/ios14/ios/RunnerTests/FLTTileProviderControllerTests.m
- packages/google_maps_flutter/google_maps_flutter_ios/example/ios14/ios/RunnerTests/GoogleMapsPolylinesControllerTests.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/FLTGoogleMapJSONConversions.h
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/FLTGoogleMapJSONConversions.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/FLTGoogleMapTileOverlayController.h
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/FLTGoogleMapTileOverlayController.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapCircleController.h
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapCircleController.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapMarkerController.h
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapMarkerController.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapPolygonController.h
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapPolygonController.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapPolylineController.h
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapPolylineController.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/messages.g.h
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/messages.g.m
- packages/google_maps_flutter/google_maps_flutter_ios/lib/src/google_maps_flutter_ios.dart
- packages/google_maps_flutter/google_maps_flutter_ios/lib/src/messages.g.dart
- packages/google_maps_flutter/google_maps_flutter_ios/pigeons/messages.dart
- packages/google_maps_flutter/google_maps_flutter_ios/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_ios/test/google_maps_flutter_ios_test.dart
Converts all of the Obj-C->Dart calls from raw method channels to Pigeon. This finishes conversion of all of the invocations in `google_maps_flutter_ios`
This is the iOS equivalent of https://github.com/flutter/packages/pull/7040, and much of the Dart code is based on that PR.
Part of https://github.com/flutter/flutter/issues/117907 …
> [google_maps_flutter] Convert Obj-C->Dart calls to Pigeon

- packages/espresso/CHANGELOG.md
- packages/espresso/README.md
- packages/espresso/android/build.gradle
- packages/espresso/android/src/main/java/androidx/test/espresso/flutter/EspressoFlutter.java
- packages/espresso/android/src/main/java/androidx/test/espresso/flutter/action/FlutterActions.java
- packages/espresso/android/src/main/java/androidx/test/espresso/flutter/action/FlutterViewAction.java
- packages/espresso/android/src/main/java/androidx/test/espresso/flutter/action/SyntheticClickAction.java
- packages/espresso/example/android/app/build.gradle
- packages/espresso/example/android/app/src/main/AndroidManifest.xml
- packages/espresso/pubspec.yaml
- **Update espresso dependencies**
fixes #151188
> Update espresso dependencies

- packages/url_launcher/url_launcher_ios/CHANGELOG.md
- packages/url_launcher/url_launcher_ios/ios/url_launcher_ios/Sources/url_launcher_ios/Launcher.swift
- packages/url_launcher/url_launcher_ios/ios/url_launcher_ios/Sources/url_launcher_ios/URLLauncherPlugin.swift
- packages/url_launcher/url_launcher_ios/pubspec.yaml
iOS 18 Beta 3 added `@MainActor @Sendable` for openURL's completion handler: 
```
@available(iOS 10.0, *)
open func open(_ url: URL, options: [UIApplication.OpenExternalURLOptionsKey : Any] = [:], completionHandler completion: (@MainActor @Sendable (Bool) -> Void)? = nil)
```
The addition of `@MainActor` is the one that caused the compile error. It was not there for Beta 1. 
This PR we simply use a `DefaultLauncher` wrapper. As expected, passing in a **non-isolated closure** to a function that expects a **main-actor isolated closure** is fine, since non-isolated closure can be called in any isolation context; plus the minimal concurrency checking also silences the Sendable warning.
But we should check again in newer betas if we can revert this change. Because this compile error forces …
> [ios]Fix compile error when conforming UIApplication to Launcher due to MainActor annotation

- .ci.yaml
- .ci/targets/android_build_all_packages.yaml
- .ci/targets/android_build_all_packages_17plus.yaml
- .ci/targets/android_build_all_packages_jdk17.yaml
- .ci/targets/android_build_all_packages_legacy.yaml
This PR introduces a new `android_build_all_packages_legacy` in `master` and `stable` to build only the "legacy" version of an Android project using JDK11.
This PR is required to resume rolling the flutter framework, like here:
* https://github.com/flutter/packages/pull/7099
Moving forward, `android_build_all_packages` will use JDK17+ and `android_build_all_packages_legacy` will use JDK11, both in `master` and `stable`, instead of having an unified build.
After this lands, the new tasks need to be taken out of `bringup:true`, and the existing `android_build_all_packages` tasks need to point to the _jdk17.yaml configuration file that is being introduced in this PR.
(The not suffixed `android_build_all_packages.yaml` file may be removed, or replaced with the contents of the _jdk17.yaml …
> [ci] Split build_all_packages by JDK version.

- packages/pigeon/CHANGELOG.md
- packages/pigeon/example/README.md
- packages/pigeon/example/app/windows/runner/flutter_window.cpp
- packages/pigeon/example/app/windows/runner/messages.g.h
- packages/pigeon/lib/cpp_generator.dart
- packages/pigeon/lib/generator_tools.dart
- packages/pigeon/platform_tests/test_plugin/windows/pigeon/core_tests.gen.h
- packages/pigeon/platform_tests/test_plugin/windows/test/null_fields_test.cpp
- packages/pigeon/pubspec.yaml
- packages/pigeon/test/cpp_generator_test.dart
The C++ generator wasn't adjusting enum value names, so they were just using the Dart camelCase style. This makes them style-guide compliant by adding the `k` prefix and making the first actual letter upper-case.
Fixes https://github.com/flutter/flutter/issues/147328
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#o …
> [pigeon] Fix C++ enum naming

- script/tool/lib/src/drive_examples_command.dart
- script/tool/test/drive_examples_command_test.dart
Introduces a small fork in the `drive_examples_command` to run integration tests with `--web-renderer=html` in the `stable` channel (and `--web-renderer=canvaskit` in `master`).
This is supposed to be removed, once the current `master` rolls into `stable` (see clean-up issue referenced below).
* Part of: https://github.com/flutter/flutter/issues/143543
* Prevents flakes: https://github.com/flutter/packages/pull/7115#issuecomment-2226661488
* Clean-up issue: https://github.com/flutter/flutter/issues/151869 …
> [ci] Drive tests with html renderer if CHANNEL is stable.

- script/tool/lib/src/build_examples_command.dart
- script/tool/lib/src/common/package_command.dart
- script/tool/test/build_examples_command_test.dart
You can use the Flutter plugin tool to [build the plugins' examples apps](https://github.com/flutter/packages/tree/main/script/tool#run-dart-integration-tests). Currently, the tool can enable the Swift Package Manager feature.
This change allows the tool to disable the Swift Package Manager feature. This will be useful for when SPM is enabled by default on a release channel.
Preparation for: https://github.com/flutter/flutter/issues/151567
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#st …
> [flutter_plugin_tools] Allow disabling Swift Package Manager when building examples

- packages/file_selector/file_selector_android/example/pubspec.yaml
**Update espresso dependency**
I think this is changelog exempt since I am not intending the change to teach/show anything to consumers of the app and it is an example only change. The main reason is to make sure that the 4.0 version of espresso is used in flutter owned code (and to see if the tests fail)
> [file_selector_android] Use Espresso 4.0

- packages/go_router/example/README.md
There was a typo or out-of-date reference to a dart file in the go router example of Stateful Nested Navigation.
This PR fix the name of the file in the `flutter run` command.
Resolve [issue 151961](https://github.com/flutter/flutter/issues/151961)
[pub …
> [go_router] docs: fix flutter run command for Stateful Nested Navigation

- packages/google_identity_services_web/CHANGELOG.md
- packages/google_identity_services_web/example/pubspec.yaml
- packages/google_identity_services_web/pubspec.yaml
Brackets the package:web dependency in gis_web to allow for `">=0.5.1 <2.0.0"`.
This is needed so we can rebase and land:
* Part of: #7202  …
> [gis_web] Allow package:web 1.0.0

- packages/flutter_migrate/test/base/terminal_test.dart
In order to address dart-lang/linter#4354, we are reporting a few more cases in `unnecessary_parenthesis`. `('text') * 2` is one such case. This change is being made in https://dart-review.googlesource.com/c/sdk/+/376540. (These are the only newly-reported unnecessary parentheses for this change.)
This is the _same_ change as https://github.com/flutter/flutter/pull/152031
[Discord]: …
> [flutter_migrate] Remove one set of parens that wrap a single String literal

- packages/path_provider/path_provider/CHANGELOG.md
- packages/path_provider/path_provider/README.md
- packages/path_provider/path_provider/pubspec.yaml
This PR bumps minimum required path_provider_android to 2.2.0 and updates supported paths matrix since Downloads directory was added to android implementation in version 2.2.0
Was not sure about version bump: when I ran `update-release-info` with `--version=minimal` it didn't update version. But since readme updated, I believe it is worth new version since not everyone reads readme on GitHub.
Did not add or change any tests since I think that work was done in https://github.com/flutter/packages/pull/4708
[#151823](https://github.com/flutter/flutter/issues/151823) …
> [path_provider] fix 151823: update minimum required path_provider_android to 2.2.0

- script/tool/lib/src/publish_check_command.dart
- script/tool/test/publish_check_command_test.dart
When running publish-check, any pre-publish hook must be run before the `publish --dry-run` step as the latter succeeding may depend on the former.
Part of https://github.com/flutter/flutter/issues/150210 …
> [tool] Run pre_publish.dart before publish --dry-run

- packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml
- packages/interactive_media_ads/CHANGELOG.md
- packages/interactive_media_ads/android/src/main/kotlin/dev/flutter/packages/interactive_media_ads/AdsRequestProxyApi.kt
- packages/interactive_media_ads/ios/interactive_media_ads/Sources/interactive_media_ads/AdsRequestProxyAPIDelegate.swift
- packages/interactive_media_ads/pubspec.yaml
- script/tool/lib/src/version_check_command.dart
- script/tool/test/version_check_command_test.dart
This PR:
* Modifies the `version_check_command` test so it checks the leading markdown of the first line of a CHANGELOG file, to ensure it's `'##'`.
* Fixes the CHANGELOG in two packages that were allowed by the tool before this fix:
* google_maps_flutter_web
* interactive_media_ads
Fixes https://github.com/flutter/flutter/issues/152638
[Discord]: …
> [ci] version_check_command now checks markdown of first CHANGELOG line.

- packages/shared_preferences/shared_preferences/CHANGELOG.md
- packages/shared_preferences/shared_preferences/example/integration_test/shared_preferences_test.dart
- packages/shared_preferences/shared_preferences/lib/src/shared_preferences_async.dart
- packages/shared_preferences/shared_preferences/pubspec.yaml
I tested this a few different ways and there was never any savings by not casting when the list is already `List<String>`.
fixes https://github.com/flutter/flutter/issues/152607
> [shared_preferences] fix stringlist bug

- packages/camera/camera_windows/windows/capture_controller.cpp
- packages/camera/camera_windows/windows/test/mocks.h
- packages/local_auth/local_auth_windows/windows/local_auth_plugin.cpp
- packages/local_auth/local_auth_windows/windows/test/mocks.h
Some C++ no-body constructors had stray `;`s after them, which cause weird formatting. This removes them all, which is purely a formatting change with no runtime implications.
> [various] Clean up C++ formatting

- packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter/example/lib/main.dart
- packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_android/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_android/example/lib/main.dart
- packages/google_maps_flutter/google_maps_flutter_android/pubspec.yaml
The Android example apps were still using HC mode, from when that was the recommended option due to lost updates with TLHC. Now that the README strongly recommends using TLHC rather than HC, we should reflect that in our examples.
This is both a user-facing change, since it's what shows on pub.dev and we want to set the right example there, and also changes our test coverage. Ideally we would test both, and an issue will be filed to explore that, but for as long as we are only testing one it should be the recommended option.
This came up in the context of investigating https://github.com/flutter/flutter/issues/152691 where impeller on google maps when using hybrid composition caused a crash, and I think it's just an oversight that we hadn't changed this. …
> [google_maps_flutter] Switch Android examples to TLHC

- packages/pointer_interceptor/pointer_interceptor/CHANGELOG.md
- packages/pointer_interceptor/pointer_interceptor/README.md
- packages/pointer_interceptor/pointer_interceptor/pubspec.yaml
Add performance warning to package README on using pointer interceptor on iOS.
Fixes https://github.com/flutter/flutter/issues/151535 …
> [pointer_interceptor] Add performance warning on using pointer interceptor on iOS

- packages/image_picker/image_picker_ios/CHANGELOG.md
- packages/image_picker/image_picker_ios/example/ios/RunnerUITests/ImagePickerFromGalleryUITests.m
- packages/image_picker/image_picker_ios/example/ios/RunnerUITests/ImagePickerFromLimitedGalleryUITests.m
The image picker UI changed from iOS 17 -> iOS 18 (beta), and there's an additional scrollview that wasn't present before.
Instead of selecting the first image in the first scroll view, instead select the image with the accessibility label that starts with "Photo":
```
↪︎Find: First Match
Output: {
Image, 0x10134f070, {{-0.0, 339.7}, {142.2, 142.3}}, label: 'Photo, March 30, 2018, 12:14 PM'
}
```
This works on previous versions of iOS as well.
Fixes https://github.com/flutter/flutter/issues/150220, found in Xcode 16 beta. …
> [image_picker_ios] Update image picker UI test query for iOS 18

- packages/flutter_adaptive_scaffold/CHANGELOG.md
- packages/flutter_adaptive_scaffold/lib/src/adaptive_scaffold.dart
- packages/flutter_adaptive_scaffold/pubspec.yaml
- packages/flutter_adaptive_scaffold/test/adaptive_scaffold_test.dart
https://github.com/flutter/flutter/issues/141060
https://github.com/flutter/flutter/issues/115235 …
> [flutter_adaptive_scaffold] Map NavigationsRails destinations and use group and labelType

- packages/google_maps_flutter/google_maps_flutter_android/example/android/app/src/main/AndroidManifest.xml
Fixes https://github.com/flutter/flutter/issues/152691
I _think_ the engine has rolled up to latest, lets see what CI says.
> [google_maps] remove Impeller opt out.

- packages/shared_preferences/shared_preferences_android/CHANGELOG.md
- packages/shared_preferences/shared_preferences_android/example/integration_test/shared_preferences_test.dart
- packages/shared_preferences/shared_preferences_android/lib/src/shared_preferences_async_android.dart
- packages/shared_preferences/shared_preferences_android/pubspec.yaml
- packages/shared_preferences/shared_preferences_foundation/CHANGELOG.md
- packages/shared_preferences/shared_preferences_foundation/example/integration_test/shared_preferences_test.dart
- packages/shared_preferences/shared_preferences_foundation/lib/src/shared_preferences_async_foundation.dart
- packages/shared_preferences/shared_preferences_foundation/pubspec.yaml
- packages/shared_preferences/shared_preferences_linux/CHANGELOG.md
- packages/shared_preferences/shared_preferences_linux/example/integration_test/shared_preferences_test.dart
- packages/shared_preferences/shared_preferences_linux/lib/shared_preferences_linux.dart
- packages/shared_preferences/shared_preferences_linux/pubspec.yaml
- packages/shared_preferences/shared_preferences_web/CHANGELOG.md
- packages/shared_preferences/shared_preferences_web/example/integration_test/shared_preferences_web_test.dart
- packages/shared_preferences/shared_preferences_web/lib/shared_preferences_web.dart
- packages/shared_preferences/shared_preferences_web/pubspec.yaml
- packages/shared_preferences/shared_preferences_windows/CHANGELOG.md
- packages/shared_preferences/shared_preferences_windows/example/integration_test/shared_preferences_test.dart
- packages/shared_preferences/shared_preferences_windows/lib/shared_preferences_windows.dart
- packages/shared_preferences/shared_preferences_windows/pubspec.yaml
fixes https://github.com/flutter/flutter/issues/153106
fixes https://github.com/flutter/flutter/issues/153112
Will add a follow up pr adding a test to the top level package after this pr lands.
> [shared_preferences] fix cast error and mutable list error with `getStringList`

- packages/animations/test/open_container_test.dart
Preparing for:
- https://github.com/flutter/flutter/pull/149963
> Fix breakages introduced by `SplashFactory`

- packages/flutter_adaptive_scaffold/CHANGELOG.md
- packages/flutter_adaptive_scaffold/example/test/main_test.dart
- packages/flutter_adaptive_scaffold/lib/src/breakpoints.dart
- packages/flutter_adaptive_scaffold/lib/src/slot_layout.dart
- packages/flutter_adaptive_scaffold/pubspec.yaml
- packages/flutter_adaptive_scaffold/test/breakpoint_test.dart
This enables people to check what the current breakpoint is and adjust UI based on that.
[pub …
> [flutter_adaptive_scaffold] Add breakpoint extension to get the current active breakpoint

- .ci.yaml
Same as https://github.com/flutter/flutter/pull/153520 but for `flutter/packages`.
> Roll `avd_cipd_verison` to latest to use the `crashreport` tool.

- packages/go_router/CHANGELOG.md
- packages/go_router/lib/src/delegate.dart
- packages/go_router/lib/src/router.dart
- packages/go_router/pubspec.yaml
- packages/go_router/test/go_router_test.dart
fixes https://github.com/flutter/flutter/issues/141906 …
> [go_router] Fixes an issue where android back button pops wrong page.

- packages/flutter_adaptive_scaffold/CHANGELOG.md
- packages/flutter_adaptive_scaffold/lib/src/breakpoints.dart
- packages/flutter_adaptive_scaffold/lib/src/slot_layout.dart
- packages/flutter_adaptive_scaffold/pubspec.yaml
- packages/flutter_adaptive_scaffold/test/breakpoint_test.dart
- packages/flutter_adaptive_scaffold/test/simulated_layout.dart
https://github.com/flutter/flutter/issues/153496 …
> [flutter_adaptive_scaffold] Fix landscape not showing in andUp

- packages/camera/camera/example/lib/main.dart
- packages/camera/camera_android/example/lib/main.dart
- packages/camera/camera_android_camerax/example/lib/main.dart
- packages/camera/camera_android_camerax/lib/src/camera_state_error.dart
- packages/camera/camera_avfoundation/example/lib/main.dart
- packages/go_router/example/lib/books/src/screens/books.dart
- packages/rfw/lib/src/dart/text.dart
- packages/url_launcher/url_launcher_android/lib/url_launcher_android.dart
- packages/url_launcher/url_launcher_ios/lib/url_launcher_ios.dart
- packages/webview_flutter/webview_flutter_wkwebview/lib/src/webkit_webview_controller.dart
See https://dart.googlesource.com/sdk.git/+/045d26bc74209f5acc6466669f89686344e83de2
> Remove unnecessary breaks in default clauses of switch statements

- script/tool/lib/src/native_test_command.dart
- script/tool/lib/src/update_excerpts_command.dart
- script/tool/test/util.dart
See https://dart.googlesource.com/sdk.git/+/045d26bc74209f5acc6466669f89686344e83de2 …
> [script] Remove unnecessary breaks in default clauses of switch statements

- packages/web_benchmarks/CHANGELOG.md
- packages/web_benchmarks/lib/src/runner.dart
- packages/web_benchmarks/pubspec.yaml
- packages/web_benchmarks/testing/test_app/lib/benchmarks/runner_simple.dart
- packages/web_benchmarks/testing/web_benchmarks_test.dart
We need `crossOriginIsolated` for skwasm to work. Otherwise, this just falls back and benchmarks JS + canvaskit.
> Serve benchmarks with COOP/COEP headers in wasm mode.

- packages/url_launcher/url_launcher_android/lib/url_launcher_android.dart
- packages/url_launcher/url_launcher_ios/lib/url_launcher_ios.dart
The Dart analyzer will soon be changed so that if the `default` clause of a `switch` statement is determined to be unreachable by the exhaustiveness checker, a new warning of type
`unreachable_switch_default` will be issued. This parallels the behavior of the existing `unreachable_switch_case` warning, which is issued whenever a `case` clause of a `switch` statement is determined to be unreachable.
In the vast majority of cases, the most reasonable way to address the warning is to remove the unreachable `default` clause. However, in a few rare cases, it makes sense to keep the `default` clause, because it's intentionally future-proofing the code in case new possible values are added to the enum being switched on.
Three of these rare cases crop up in flutter/packages. This change adds …
> [url_launcher] Ignore new `unreachable_switch_default` warning.

- packages/google_sign_in/google_sign_in_ios/CHANGELOG.md
- packages/google_sign_in/google_sign_in_ios/darwin/Classes/FLTGoogleSignInPlugin.m
- packages/google_sign_in/google_sign_in_ios/pubspec.yaml
The normal Cocoa pattern is to check a result, and only if it's nil then do something with the error.
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ErrorHandlingCocoa/CreateCustomizeNSError/CreateCustomizeNSError.html
> Important: Success or failure is indicated by the return value of the method. Although Cocoa methods that indirectly return error objects in the Cocoa error domain are guaranteed to return such objects if the method indicates failure by directly returning nil or NO, you should always check that the return value is nil or NO before attempting to do anything with the NSError object.
Use this pattern with the result and error from the sign in completion block.  This means `-didSignInForUser` is only called for non-nil users (the possibility of a …
> [google_sign_in_ios] Fix "callee requires a non-null parameter" analyzer warning

- CODEOWNERS
Now that the patches have landed there isn't a lot of value in me getting notified about every change to each package. I'm of course still happy to help, but I'll have to be reached in a different way than the `CODEOWNERS` mechanism :)
> Remove matan from codeowners

- .ci/targets/ios_platform_tests.yaml
- .ci/targets/macos_platform_tests.yaml
- script/configs/exclude_xcode_deprecation.yaml
- script/configs/exclude_xcode_deprecation_ios.yaml
Bump Xcode analyze minimum check version iOS 13 -> iOS 14 and macOS 12.3 -> macOS 13.
- Hit StoreKit2 deprecations. Exclude `in_app_purchase_storekit` to work around StoreKit 1 deprecation warnings.  Added a TODO to remove the exclusion when StoreKit2 is adopted (this should happen in the next few weeks) https://github.com/flutter/flutter/issues/116383.
- Hit https://github.com/flutter/flutter/issues/153587, fixed in https://github.com/flutter/packages/pull/7513
- Hit https://github.com/flutter/flutter/issues/125901 which was `#pragma`'d out in https://github.com/flutter/packages/pull/6221
See related https://github.com/flutter/plugins/pull/5778 and https://github.com/flutter/flutter/issues/102835 …
> Increase deprecation check minimum to iOS 14 and macOS 13

- packages/flutter_adaptive_scaffold/CHANGELOG.md
- packages/flutter_adaptive_scaffold/lib/src/adaptive_scaffold.dart
- packages/flutter_adaptive_scaffold/lib/src/breakpoints.dart
- packages/flutter_adaptive_scaffold/pubspec.yaml
- packages/flutter_adaptive_scaffold/test/adaptive_scaffold_test.dart
- packages/flutter_adaptive_scaffold/test/breakpoint_test.dart
- packages/flutter_adaptive_scaffold/test/simulated_layout.dart
https://m3.material.io/foundations/layout/understanding-layout/parts-of-layout
https://m3.material.io/foundations/layout/understanding-layout/spacing
[Discord]: …
> [flutter_adaptive_scaffold] Add correct material spacing and panes

- packages/flutter_adaptive_scaffold/CHANGELOG.md
- packages/flutter_adaptive_scaffold/README.md
- packages/flutter_adaptive_scaffold/lib/src/breakpoints.dart
- packages/flutter_adaptive_scaffold/pubspec.yaml
- packages/flutter_adaptive_scaffold/test/breakpoint_test.dart
Sometimes you want to compare a breakpoint to a baseline or another breakpoint to determine which UI to show or how to handle something. This adds operators so you can check those things.
```dart
Breakpoint.activeBreakpointOf(context) > Breakpoints.large;
``` …
> [flutter_adaptive_scaffold] Compare breakpoints

- packages/rfw/example/remote/android/build.gradle
- packages/rfw/example/remote/android/gradle/wrapper/gradle-wrapper.properties
`rfw` has multiple example apps - I missed this one in https://github.com/flutter/packages/pull/7521/.
Also missed `extension_google_sign_in_as_googleapis_auth` - will need to upgrade that in a follow up PR (it has additional failures after the AGP upgrade, so it isn't a one line fix). …
> [rfw] Upgrade missed example app

- packages/google_sign_in/google_sign_in_android/CHANGELOG.md
- packages/google_sign_in/google_sign_in_android/android/build.gradle
- packages/google_sign_in/google_sign_in_android/pubspec.yaml
This upgrade is causing issues with our use of R8. I think we should downgrade back, while we investigate what it takes to unblock this upgrade.
Fixes https://github.com/flutter/flutter/issues/154489, 
related to https://github.com/flutter/packages/pull/7571#discussion_r1742551066.
[linked to at least one issue …
> [google_sign_in_android] Downgrade Guava version from `33.3.0` to `32.0.1`

- packages/flutter_adaptive_scaffold/CHANGELOG.md
- packages/flutter_adaptive_scaffold/lib/src/breakpoints.dart
- packages/flutter_adaptive_scaffold/pubspec.yaml
- packages/flutter_adaptive_scaffold/test/breakpoint_test.dart
- packages/flutter_adaptive_scaffold/test/simulated_layout.dart
As pointed out by the docs on this:
> Available width and height are classified separately, so at any point in time, your app has two window size classes—one for width, one for height. Available width is usually more important than available height due to the ubiquity of vertical scrolling, so the width window size class is likely more relevant to your app's UI. …
> [flutter_adaptive_scaffold] Fix breakpoint not being active in certain cases like foldables

- packages/google_maps_flutter/google_maps_flutter_android/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/Messages.java
- packages/google_maps_flutter/google_maps_flutter_android/lib/src/google_maps_flutter_android.dart
- packages/google_maps_flutter/google_maps_flutter_android/lib/src/messages.g.dart
- packages/google_maps_flutter/google_maps_flutter_android/pigeons/messages.dart
- packages/google_maps_flutter/google_maps_flutter_android/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_android/test/google_maps_flutter_android_test.dart
Replace the raw integers used in `PlatformPolyline` to an enum.
https://github.com/flutter/flutter/issues/153718#event-13934571301 …
> [google_maps_flutter_android] Convert `JointType` to an enum

- packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/legacy/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart
Disables tests that are suddenly flaking very badly and keeping the tree closed.
Tracked in https://github.com/flutter/flutter/issues/154826
> [google_maps_flutter] Disable setAndGetScrollPosition on iOS

- packages/camera/camera_android_camerax/lib/src/capture_request_options.dart
- packages/camera/camera_android_camerax/lib/src/live_data.dart
- packages/camera/camera_android_camerax/test/capture_request_options_test.dart
The Dart analyzer will soon be changed so that if the `default` clause of a `switch` statement is determined to be unreachable by the exhaustiveness checker, a new warning of type
`unreachable_switch_default` will be issued. This parallels the behavior of the existing `unreachable_switch_case` warning, which is issued whenever a `case` clause of a `switch` statement is determined to be unreachable.
In the vast majority of cases, the most reasonable way to address the warning is to remove the unreachable `default` clause. However, in a few rare cases, it makes sense to keep the `default` clause, because it's intentionally future-proofing the code in case new possible values are added to the enum being switched on.
Three of these rare cases crop up in the camerax package. This change adds …
> [camerax] Ignore new `unreachable_switch_default` warning.

- packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/camera.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/camera_test.dart
Replace `newLatLngZoom` with `newLatLngBounds` as it should be.
See https://github.com/flutter/packages/pull/7596#pullrequestreview-2297196704
Part of https://github.com/flutter/flutter/issues/152928
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributin …
> [google_maps_flutter_platform_interface] Fix typo in CameraUpdateNewLatLngBounds.toJson

- packages/two_dimensional_scrollables/CHANGELOG.md
- packages/two_dimensional_scrollables/lib/src/tree_view/tree.dart
- packages/two_dimensional_scrollables/pubspec.yaml
- packages/two_dimensional_scrollables/test/tree_view/tree_test.dart
Fixes [#153889 ](https://github.com/flutter/flutter/issues/154292) an issue where nodes were being removed incorrectly when using `AnimationStyle.noAnimation `or the animation duration was zero seconds, which previously caused the erratic behavior due to hidden state updates. Similar to https://github.com/flutter/flutter/pull/153890.
[Discord]: …
> [two_dimensional_scrollables] Fix TreeView bug when animation duration is zero

- packages/video_player/video_player_android/CHANGELOG.md
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
- packages/video_player/video_player_android/android/src/test/java/io/flutter/plugins/videoplayer/VideoPlayerTest.java
- packages/video_player/video_player_android/pubspec.yaml
So embarrassing!
Closes https://github.com/flutter/flutter/issues/154559.
> Fix an if statement with resumed video players on Android.

- packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_android/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart
Reverts flutter/packages#7621
The re-enabled tests are failing in post-submit.
Alternately, instead of reverting we could just re-add the skips with the link, if we still want to keep the updated version as a better foundation to work from.
> Revert "[webview_flutter] Improve flaky scroll tests"

- packages/file_selector/file_selector_macos/CHANGELOG.md
- packages/file_selector/file_selector_macos/macos/file_selector_macos.podspec
- packages/file_selector/file_selector_macos/macos/file_selector_macos/Package.swift
- packages/file_selector/file_selector_macos/macos/file_selector_macos/Sources/file_selector_macos/Resources/PrivacyInfo.xcprivacy
- packages/file_selector/file_selector_macos/pubspec.yaml
- packages/url_launcher/url_launcher_macos/CHANGELOG.md
- packages/url_launcher/url_launcher_macos/macos/url_launcher_macos.podspec
- packages/url_launcher/url_launcher_macos/macos/url_launcher_macos/Sources/url_launcher_macos/Resources/PrivacyInfo.xcprivacy
- packages/url_launcher/url_launcher_macos/pubspec.yaml
- script/tool/lib/src/podspec_check_command.dart
- script/tool/test/podspec_check_command_test.dart
macOS privacy manifest enforcement is rolling out soon, so this brings all macOS plugins into alignment with our iOS policy of always having a manifest, including updating the repo tooling to enforce that.
Very few plugins are affected because most share the implementation package with iOS, and we didn't do any target platform switching when adding the manifests for iOS, automatically covering macOS as well.
Fixes https://github.com/flutter/flutter/issues/155564
[Discord]: …
> [various] Adds macOS privacy manifests

- packages/rfw/test/argument_decoders_test.dart
In https://github.com/flutter/engine/pull/55231, the implementation of `Color.toString()` has changed. Update the test to not depend on the exact implementation.
> Update test to not depend on `Color.toString()`

- packages/video_player/video_player_android/CHANGELOG.md
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
- packages/video_player/video_player_android/pubspec.yaml
... to avoid a revert like https://github.com/flutter/engine/pull/55450.
/cc @jtmcdole another example of churn where I can't do the right thing without manual steps.
> Add a `@SuppressWarnings` in advance 

- packages/pigeon/example/README.md
*Replace a deprecated command in the instructions of using `pigeon`.*
Running `flutter pub run pigeon --input path/to/input.dart` will output the following at the start of the output:
```console
Deprecated. Use `dart run` instead.
``` …
> [pigeon] update deprecated command in README of the example

- packages/pigeon/CHANGELOG.md
- packages/pigeon/lib/dart_generator.dart
- packages/pigeon/lib/generator_tools.dart
- packages/pigeon/platform_tests/shared_test_plugin_code/lib/src/generated/background_platform_channels.gen.dart
- packages/pigeon/platform_tests/shared_test_plugin_code/lib/src/generated/multiple_arity.gen.dart
- packages/pigeon/platform_tests/shared_test_plugin_code/lib/src/generated/nullable_returns.gen.dart
- packages/pigeon/platform_tests/shared_test_plugin_code/lib/src/generated/primitive.gen.dart
- packages/pigeon/pubspec.yaml
- packages/pigeon/test/dart_generator_test.dart
fixes https://github.com/flutter/flutter/issues/155512
> [pigeon] fix int bug

- packages/video_player/video_player_android/CHANGELOG.md
- packages/video_player/video_player_android/android/build.gradle
- packages/video_player/video_player_android/pubspec.yaml
In https://github.com/flutter/plugins/pull/3019 -Werror was incorrectly added directly to the plugin build itself, which impacts client builds. We've since updated our builds to set these flags on the project only when building our own example app, which gives us the CI benefits of this flag without burdening clients with restrictive build settings, so this is no longer needed.
Fixes https://github.com/flutter/flutter/issues/148478 …
> [video_player] Remove -Werror from Android build

- packages/xdg_directories/CHANGELOG.md
- packages/xdg_directories/example/lib/main.dart
- packages/xdg_directories/lib/xdg_directories.dart
- packages/xdg_directories/pubspec.yaml
- packages/xdg_directories/test/xdg_directories_test.dart
This pull request adds a property called `stateHome` that provides the directory for `XDG_STATE_HOME`.
Fixes https://github.com/flutter/flutter/issues/155494
> [xdg_directories] Add `stateHome` property

- packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/bitmap.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/bitmap_test.dart
`BitmapDescriptor` is currently just a wrapper around JSON, with the exception of two of its subclasses. This converts all cases to typesafe structures without breaking the current API.
Part of https://github.com/flutter/flutter/issues/155122 …
> [google_maps_flutter_platform_interface] Convert `BitmapDescriptor` to typesafe subclasses

- packages/rfw/test/material_widgets_test.dart
- packages/rfw/test/tolerant_comparator.dart
- packages/rfw/test/tolerant_comparator_web.dart
- packages/rfw/test/utils.dart
This PR introduces a tolerance for rfw material widget tests to fix the golden test error in https://github.com/flutter/flutter/issues/151611.
Part of a fix for https://github.com/flutter/flutter/issues/151659. …
> [rfw] Increase tolerance for material widget tests

- packages/url_launcher/url_launcher/CHANGELOG.md
- packages/url_launcher/url_launcher/README.md
- packages/url_launcher/url_launcher/example/lib/encoding.dart
- packages/url_launcher/url_launcher/pubspec.yaml
Removes incorrect instructions for SMS that were added in https://github.com/flutter/plugins/pull/6042. These instructions would double-encode the body, causing issues.
This removes, rather than fixes, the instructions because the `sms:` scheme isn't particularly well defined, and has inconsistent handling across platforms (see https://github.com/flutter/flutter/issues/18823 and https://github.com/flutter/flutter/issues/156281 for some examples), so no simple instructions will work everywhere. Handling that kind of platform difference is out of scope for this package and its instructions.
Fixes https://github.com/flutter/flutter/issues/156281 …
> [url_launcher] Remove incorrect SMS instructions

- packages/pigeon/example/README.md
- packages/pigeon/example/app/android/app/src/main/kotlin/dev/flutter/pigeon_example_app/Messages.g.kt
- packages/pigeon/example/app/ios/Runner/Messages.g.swift
- packages/pigeon/example/app/lib/main.dart
- packages/pigeon/example/app/lib/src/messages.g.dart
- packages/pigeon/example/app/pigeons/messages.dart
Now that Pigeon supports non-nullable generics, update the example app to show the much more likely use case of having non-nullable generics for collection types.
Part of https://github.com/flutter/flutter/issues/155891 …
> [pigeon] Use non-nullable generics in example app

- packages/video_player/video_player_android/CHANGELOG.md
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
- packages/video_player/video_player_android/android/src/test/java/io/flutter/plugins/videoplayer/VideoPlayerTest.java
- packages/video_player/video_player_android/pubspec.yaml
Fixes 1 of the 2 reported issues in https://github.com/flutter/flutter/issues/156158 (dispose)
I'd like to write a better (integration) test for this (https://github.com/flutter/flutter/issues/156424), but honestly this should have been caught by existing tests (which call dispose). I am [asking on Discord](https://discord.com/channels/608014603317936148/608020293944082452/1293275599045001276) for more clarification.
> Dispose the `ExoPlayer` before `SurfaceProducer`.

- packages/video_player/video_player_android/CHANGELOG.md
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
- packages/video_player/video_player_android/android/src/test/java/io/flutter/plugins/videoplayer/VideoPlayerTest.java
- packages/video_player/video_player_android/pubspec.yaml
Closes https://github.com/flutter/flutter/issues/156158.
I want to address this better in https://github.com/flutter/flutter/issues/156434 but of course that will take another quarter!
> Disable `SurfaceProducer.Callback` when the surface is disposed manually.

- packages/camera/camera_android_camerax/CHANGELOG.md
- packages/camera/camera_android_camerax/README.md
- packages/camera/camera_android_camerax/android/src/main/AndroidManifest.xml
- packages/camera/camera_android_camerax/pubspec.yaml
Reverts logic to remove `READ_EXTERNAL_STORAGE` permission from merged Android manifest (between plugins and Flutter app) by default. Turns out that this logic conflicts with Flutter plugins/apps that actually require the `READ_EXTERNAL_STORAGE` permission.
Specifically, reverts https://github.com/flutter/packages/pull/4716 and adds documentation so that users know how to manually remove `READ_EXTERNAL_STORAGE`  from the merged manifest if they wish. 
Fixes https://github.com/flutter/flutter/issues/156198 and adds documentation to address https://github.com/flutter/flutter/issues/131116. …
> [camerax] Revert "Explicitly remove READ_EXTERNAL_STORAGE permission"

- packages/video_player/video_player_android/CHANGELOG.md
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
- packages/video_player/video_player_android/android/src/test/java/io/flutter/plugins/videoplayer/VideoPlayerTest.java
- packages/video_player/video_player_android/pubspec.yaml
Closes https://github.com/flutter/flutter/issues/156451.
> Remove additional (harmless but annoying) native stack traces.

- packages/camera/camera_android_camerax/README.md
*Remove the duplicated `report` word in `README.md` of `camera_android_camerax` package.*
[pub …
> [camera_android_camerax] Remove duplicated 'report' in README.md

- packages/flutter_markdown/CHANGELOG.md
- packages/flutter_markdown/lib/src/builder.dart
- packages/flutter_markdown/pubspec.yaml
- packages/flutter_markdown/test/blockquote_test.dart
Makes `flutter_markdown` treat paragraphs in blockquotes like a normal paragraph with respect to soft wrapping.
Currently, line breaks in blockquotes translate directly to line breaks in the output. This happens regardless of the Markdown Specification chosen. Such behavior is different from most Markdown implementations, including the reference ones cited in [flutter_markdown ](https://pub.dev/packages/flutter_markdown) ([Dart Markdown Live Editor](https://dart-lang.github.io/markdown/) and the [Markdown Live Preview](https://markdownlivepreview.com/)).
Example:
```
> my
> blockquote
```
Currently renders like:
> my
> blockquote
And this PR fixes it to become:
> my blockquote
Note: previewing in this GitHub editor, I get the hard-wrap behavior. However, [Dart Markdown Live …
> [flutter_markdown] Soft wrapping in blockquotes

- packages/camera/camera_android/CHANGELOG.md
- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/CameraUtils.java
- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/DartMessenger.java
- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/Messages.java
- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/MethodCallHandlerImpl.java
- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/NoOpVoidResult.java
- packages/camera/camera_android/android/src/test/java/io/flutter/plugins/camera/DartMessengerTest.java
- packages/camera/camera_android/lib/src/android_camera.dart
- packages/camera/camera_android/lib/src/messages.g.dart
- packages/camera/camera_android/lib/src/utils.dart
- packages/camera/camera_android/pigeons/messages.dart
- packages/camera/camera_android/pubspec.yaml
- packages/camera/camera_android/test/android_camera_test.dart
- packages/camera/camera_android/test/utils_test.dart
Part of the effort to transition to typesafe implementations for platform calls. Android analog to https://github.com/flutter/packages/pull/6568/
Part of https://github.com/flutter/flutter/issues/117905 …
> [camera_android] Convert calls from native to dart side to Pigeon.

- analysis_options.yaml
- packages/web_benchmarks/testing/test_app/analysis_options.yaml
Reference: https://github.com/dart-lang/linter/issues/5107
> Disable non-functional, deprecated `package_api_docs` lint

- packages/video_player/video_player_android/CHANGELOG.md
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
- packages/video_player/video_player_android/example/integration_test/video_player_test.dart
- packages/video_player/video_player_android/pubspec.yaml
Closes https://github.com/flutter/flutter/issues/156424.
Also improved an error message that came up as a result.
> Convert use of `mini_player` in the `video_player_android` test to `AndroidVideoPlayer`.

- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/Camera.java
- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/DartMessenger.java
`sendCameraErrorEvent` is package-visible and only called in `Camera.java` and `CameraTest.java`. This should be test- and version-exempt, as it is essentially just an annotation change.
Fixes https://github.com/flutter/flutter/issues/156729 …
> [camera_android] Mark `description` in `sendCameraErrorEvent` as `@NonNull`

- packages/url_launcher/url_launcher_windows/CHANGELOG.md
- packages/url_launcher/url_launcher_windows/pubspec.yaml
- packages/url_launcher/url_launcher_windows/windows/CMakeLists.txt
- packages/url_launcher/url_launcher_windows/windows/test/url_launcher_windows_test.cpp
- packages/url_launcher/url_launcher_windows/windows/url_launcher_plugin.cpp
- ShellExecuteW does not handle file: urls that contain %-encoded UTF-8 strings correctly.  %-encoded ASCII
strings are handled correctly, as are file "urls" that contain Unicode strings in its path component.
- This change perform URL decode on file: urls before passing to ShellExecuteW.
Fixes https://github.com/flutter/flutter/issues/156790
[Discord]: …
> [url_launcher] Decode file URLs before passing it to ShellExecuteW

- packages/camera/camera_android/android/build.gradle
- packages/google_maps_flutter/google_maps_flutter_android/android/build.gradle
- packages/google_maps_flutter/google_maps_flutter_android/android/src/test/java/io/flutter/plugins/googlemaps/ClusterManagersControllerTest.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/test/java/io/flutter/plugins/googlemaps/ConvertTest.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/test/java/io/flutter/plugins/googlemaps/GoogleMapControllerTest.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/test/java/io/flutter/plugins/googlemaps/GoogleMapInitializerTest.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/test/java/io/flutter/plugins/googlemaps/HeatmapsControllerTest.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/test/java/io/flutter/plugins/googlemaps/MarkersControllerTest.java
Tests in the title package that are run using the Robolectric test runner will now run on all SDKs level >= LOLLIPOP (i.e. 21). Raises max heap size to 1G.
Affects only tests, should be version-bump exempt.
Fixes https://github.com/flutter/flutter/issues/152931 …
> [google_maps_android_flutter] Convert `Config.sdk` to `minSdk` in Robolectric tests and lower to `LOLLIPOP`

- packages/flutter_markdown/CHANGELOG.md
- packages/flutter_markdown/lib/src/builder.dart
- packages/flutter_markdown/lib/src/widget.dart
- packages/flutter_markdown/pubspec.yaml
- packages/flutter_markdown/test/custom_syntax_test.dart
This adds support for allowing block tags recognized by the Markdown processor to insert something other than just a `Column` or a `SizedBox` (the defaults for blocks with children, and without). Without this ability, custom builders can't insert their own widgets to, say, make it be a colored container instead.
This addresses a customer request.
Fixes https://github.com/flutter/flutter/issues/135848
> Allow custom blocks to be something other than `Column` or `SizedBox`

- packages/espresso/example/android/app/build.gradle
- packages/google_maps_flutter/google_maps_flutter/example/android/app/build.gradle
- packages/google_maps_flutter/google_maps_flutter_android/example/android/app/build.gradle
- packages/google_sign_in/google_sign_in/example/android/app/build.gradle
- packages/google_sign_in/google_sign_in_android/example/android/app/build.gradle
- packages/image_picker/image_picker/example/android/app/build.gradle
- packages/image_picker/image_picker_android/example/android/app/build.gradle
- packages/interactive_media_ads/example/android/app/build.gradle
- packages/local_auth/local_auth/example/android/app/build.gradle
- packages/local_auth/local_auth_android/example/android/app/build.gradle
We had manually added `multiDexEnabled` to various plugin example apps over time to fix build failures, but it's not needed for plugins with a `minSdk` of 20+ ([reference](https://developer.android.com/build/multidex)), and Flutter (and thus all of our plugins) requires 21+, so the setting is just cruft.
> [various] Remove multiDexEnabled

- packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test_legacy.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/legacy/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart
Starting in macOS 14, webview_flutter integration tests hang due to being unable to connect to the test server. Based on local experimentation, in appears that we are not able to connect when binding to the "any" address, which gives us an IP address of 0.0.0.0, but using the loopback address (which is all we should need; the point is to accept local connections from the test itself) does work.
Since our test fleet is a mixed macOS 13/14 fleet, this should fix flaky timeouts of macOS platform tests in CI, in addition to fixing local runs.
Fixes https://github.com/flutter/flutter/issues/157449 …
> [webview_flutter] Fix macOS 14+ test hangs

- packages/path_provider/path_provider/CHANGELOG.md
- packages/path_provider/path_provider/pubspec.yaml
https://github.com/flutter/engine/pull/52022 removed the Android v1 embedder.
I'm seeing locally that older versions of `path_provider_android` fail due to missing symbols:
```txt
flutter run                   
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply
Warning: This project is still reading the deprecated '.flutter-plugins. file.
In an upcoming stable release support for this file will be completely removed and your build will fail.
See https:/flutter.dev/to/flutter-plugins-configuration. …
```
> Bump `path_provider_android` to `^2.2.5` due to Android v1 embedder.

- analysis_options.yaml
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/convert.dart
- packages/image_picker/image_picker_for_web/lib/src/image_resizer.dart
- packages/url_launcher/url_launcher_web/lib/url_launcher_web.dart
- packages/webview_flutter/webview_flutter_web/lib/src/web_webview_controller.dart
- packages/webview_flutter/webview_flutter_web/lib/src/webview_flutter_web_legacy.dart
Each of these are going to be removed soon.
* avoid_null_checks_in_equality_operators
* unsafe_html
Work towards https://github.com/dart-lang/linter/issues/5063 and https://github.com/dart-lang/linter/issues/5001 …
> Disable two lint rules which are being removed.

- packages/palette_generator/CHANGELOG.md
- packages/palette_generator/README.md
- packages/palette_generator/pubspec.yaml
- script/configs/temp_exclude_excerpt.yaml
Simplifies the README so that it no longer uses a code snippet, as the snippet was not adding any value over pub.dev instructions, and removes it from the code-excerpt exclusion list. …
> [palette_generator] Remove unmanaged code snippet

- script/tool/lib/src/make_deps_path_based_command.dart
- script/tool/test/make_deps_path_based_command_test.dart
`made-deps-path-based` would sometimes create invalid relative paths when `third_party/packages` was involved because it was using the sibling directory of `packages` as the base. This updates the logic to always make the paths relative to the repository root; this is often a longer relative path than necessary, but that's harmless, and always using the repo root makes it easier to reason about.
Also fixes the fact that paths that were already path based (which is always the case for `some_package/example`'s dependency on `some_package`) were being overridden, causing CI to do some unnecessary duplicate analysis work.
> [tool] Fix third_party dependency overrides

- script/tool/lib/src/common/package_command.dart
- script/tool/test/common/package_command_test.dart
Fixes `--current-package` so that when run on a package in third_party/packages/ in works as expected, rather than failing with an error message saying that it must be run from inside a package.
> [tool] Support third_party for --current-package

- .ci/scripts/plugin_tools_format.sh
- .ci/targets/repo_checks.yaml
- script/tool/lib/src/fetch_deps_command.dart
- script/tool/test/build_examples_command_test.dart
Currently the autoformatter check is run per-package, so doesn't include script/tool. This adds a new CI step to check the formatting of the repo tooling, just as we have for running its unit tests.
> [ci] Ensure repo tool is autoformatted

- packages/vector_graphics/CHANGELOG.md
- packages/vector_graphics/lib/src/debug.dart
- packages/vector_graphics/pubspec.yaml
The `dart.library.html` variable is not available with wasm
Since the web version is (currently) a no-op, flip the condition to
check for dart:io instead
> [vector_garphics] fix execution on the web with WebAssembly

- packages/go_router/example/android/build.gradle
The tree is currently closed on an out-of-band failure in the build of this example app:
e: .../transformed/jetified-kotlin-stdlib-1.9.24.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /b/s/w/ir/cache/gradle/caches/transforms-4/6cce2b947fc9e43cca6b44ff30180b61/transformed/jetified-kotlin-stdlib-1.9.24.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: .../transformed/jetified-kotlin-stdlib-1.9.24.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its …
> [go_router] Update example app to Kotlin 1.9.0

- packages/vector_graphics/pubspec.yaml
- packages/vector_graphics_codec/pubspec.yaml
- packages/vector_graphics_compiler/pubspec.yaml
- third_party/packages/flutter_svg/README.md
- third_party/packages/path_parsing/CHANGELOG.md
Fixes a few minor things from the recent import of dnfield's vector-graphics-related packages:
- Fixes a bad copy/paste in the `path_parsing` CHANGELOG so future versions of the CHANGELOG will be less confusing.
- Removes a coverage link from the `flutter_svg` README that is no longer correct.
- Disabled publishing of `vector_graphics*` until a new versioning plan is made.
Because these are extremely minor, I'm overriding our usual versioning policy; it's fine for the CHANGELOG and README fixes to go out the next time we happen to publish rather than immediately.
> [various] Minor cleanup in recently imported packages

- third_party/packages/path_parsing/CHANGELOG.md
- third_party/packages/path_parsing/lib/src/path_parsing.dart
- third_party/packages/path_parsing/pubspec.yaml
Towards https://github.com/flutter/flutter/issues/157940
> [path_parsing] deprecate utility functions that should be private

- packages/vector_graphics/CHANGELOG.md
- packages/vector_graphics/pubspec.yaml
- packages/vector_graphics_codec/pubspec.yaml
- packages/vector_graphics_compiler/CHANGELOG.md
- packages/vector_graphics_compiler/pubspec.yaml
- third_party/packages/flutter_svg/CHANGELOG.md
- third_party/packages/flutter_svg/pubspec.yaml
Relax the dependency constrraints of the vector graphics packages. Since there are no actual changes to the vector_graphics_codec package and the listed version is already published, I don't think it needs a version bump to remove the publish key.
Fixes https://github.com/flutter/flutter/issues/157626
> [vector_graphics*] Relax dependency constraints of vector_graphics, vector_graphics_codec, vector_graphics_compiler, flutter_svg 

- packages/flutter_adaptive_scaffold/example/android/app/build.gradle
- packages/flutter_adaptive_scaffold/example/android/build.gradle
- packages/flutter_adaptive_scaffold/example/android/settings.gradle
- packages/google_sign_in/google_sign_in/example/android/app/build.gradle
- packages/google_sign_in/google_sign_in/example/android/app/src/main/AndroidManifest.xml
- packages/google_sign_in/google_sign_in/example/android/build.gradle
- packages/google_sign_in/google_sign_in/example/android/settings.gradle
- packages/google_sign_in/google_sign_in_android/example/android/app/build.gradle
- packages/google_sign_in/google_sign_in_android/example/android/build.gradle
- packages/google_sign_in/google_sign_in_android/example/android/settings.gradle
- packages/interactive_media_ads/example/android/settings.gradle
- packages/palette_generator/example/android/app/build.gradle
- packages/palette_generator/example/android/build.gradle
- packages/palette_generator/example/android/settings.gradle
- packages/pigeon/platform_tests/alternate_language_test_plugin/example/android/app/build.gradle
- packages/pigeon/platform_tests/alternate_language_test_plugin/example/android/build.gradle
- packages/pigeon/platform_tests/alternate_language_test_plugin/example/android/settings.gradle
- packages/pigeon/platform_tests/test_plugin/example/android/app/build.gradle
- packages/pigeon/platform_tests/test_plugin/example/android/build.gradle
- packages/pigeon/platform_tests/test_plugin/example/android/settings.gradle
Updated applying gradle plugins from usage of imperative apply to usage of declarative blocks {} apply for 7 plugins. Intending on updating all android example apps under packages. The first migration was completed in this PR [here](https://github.com/flutter/packages/pull/7968)
Previously migrated applying `path_provider` plugin example app from imperatively to declaratively in this PR [here](https://github.com/flutter/packages/pull/7822). Tests for changes in the linked PR above.
More information on Flutter Gradle Pluggin Apply [here](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply)
Partially addresses [#152656](https://github.com/flutter/flutter/issues/152656) …
> Applied Gradle Plugins Declaratively for Multiple Plugin Example Apps (Part 2)

- packages/google_identity_services_web/CHANGELOG.md
- packages/google_identity_services_web/example/integration_test/js_interop_oauth_test.dart
- packages/google_identity_services_web/lib/src/js_interop/google_accounts_id.dart
- packages/google_identity_services_web/lib/src/js_interop/google_accounts_oauth2.dart
- packages/google_identity_services_web/lib/src/js_interop/load_callback.dart
- packages/google_identity_services_web/pubspec.yaml
- packages/google_sign_in/google_sign_in_web/CHANGELOG.md
- packages/google_sign_in/google_sign_in_web/lib/src/gis_client.dart
- packages/google_sign_in/google_sign_in_web/pubspec.yaml
These APIs used to accept allowInterop'd callbacks. When the implementation was migrated to use dart:js_interop, they were wrapped with toJS. However, starting in 3.5, to be consistent with dart2wasm, double-wrapping a function is an error. The documentation should be clear that it accepts only Dart functions and uses should be cleaned up to not use allowInterop and type the callbacks' parameter and return value correctly.
> [google_sign_in/google_identity_services] Clear-up documentation of callbacks in various APIs and uses of those APIs

- script/tool/lib/src/format_command.dart
- script/tool/test/format_command_test.dart
Instead of running Dart formatting on the whole repo at once, run it per package, from the package's directory. This is slower, but necessary since the new formatter behaves differently depending on the package's min SDK version.
> [tools] Format Dart per-package

- packages/vector_graphics_compiler/CHANGELOG.md
- packages/vector_graphics_compiler/lib/src/svg/parser.dart
- packages/vector_graphics_compiler/pubspec.yaml
- packages/vector_graphics_compiler/test/parser_test.dart
The following SVG throw an exception (when using flutter_svg) : https://sweden.a.bigcontent.io/v1/static/10000199.
This SVG contain an empty tag : <polygon xmlns="http://www.w3.org/2000/svg" fill="#0a287d" points="" id="polygon7"/> which lead to the issue.
This PR check if path is null to avoid the issue.
PR from https://github.com/dnfield/vector_graphics/pull/254
[Discord]: …
> [vector_graphics_compiler] fix-null-exception

- .github/dependabot.yml
Dependabot now supports [grouping dependencies](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) into one PR instead of one per dependency.
Group github-action updates into one PR. Make github-actions update weekly instead of daily. Remove docker since it was removed in #4822
This means a PR like https://github.com/flutter/packages/pull/7813 will instead be grouped into one.
Here's an example of what that will look like: https://github.com/kubernetes-sigs/cluster-api/pull/11347
__________
__________
https://github.com/kubernetes-sigs/cluster-api/blob/e13abeaed2bd3d7b04abd9c9823e2f4185fa6599/.github/dependabot.yaml#L10-L12
I also updated the reviewers to stop the "One or more of the users or teams you …
> Group dependabot github-action update PRs, delete dead docker updates

- .github/dependabot.yml
- script/tool/lib/src/dependabot_check_command.dart
- script/tool/test/dependabot_check_command_test.dart
[Multi-directory config](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-the-dependabotyml-file) allows duplicated dependabot configs can be removed in favor of one that specifies multiple directories.  Update the Android example apps so they can be updated all at once.
Also updated the dependabot CI command to look for either `directory` or `directories` key.
Part of https://github.com/flutter/flutter/issues/148098 …
> Use dependabot multi-directory configuration for Android example gradle updates

- packages/shared_preferences/shared_preferences/CHANGELOG.md
- packages/shared_preferences/shared_preferences/README.md
- packages/shared_preferences/shared_preferences/lib/src/shared_preferences_legacy.dart
- packages/shared_preferences/shared_preferences/pubspec.yaml
One use of "class" instead of "plugin" to refer to the `SharedPreferences` class specifically slipped through review. This updates it to make it clear that it's talking about a specific class, not the plugin.
Also updates the `setPrefix:` doc comment to clarify that it only applies to that class, now that the addition of other classes to the API surface has made that ambiguous.
Fixes https://github.com/flutter/flutter/issues/158404
[Discord]: …
> [shared_preferences] Fix confusing language in README

- packages/file_selector/file_selector_linux/CHANGELOG.md
- packages/file_selector/file_selector_linux/linux/file_selector_plugin.cc
- packages/file_selector/file_selector_linux/linux/file_selector_plugin_private.h
- packages/file_selector/file_selector_linux/linux/test/file_selector_plugin_test.cc
- packages/file_selector/file_selector_linux/pubspec.yaml
Fixes a regression introduced during the Pigeon conversion where canceling a dialog would fail assertions due to accidentally returning a null list instead of an empty list.
Fixes https://github.com/flutter/flutter/issues/158430 …
> [file_selector] Fix Linux cancel regression

- .ci/targets/repo_checks.yaml
- script/tool/lib/src/format_command.dart
- script/tool/lib/src/license_check_command.dart
- script/tool/test/format_command_test.dart
- script/tool/test/license_check_command_test.dart
The new Dart formatter needs to know the Dart language version of the code it is formatting, and it reads that from a file in `.dart_tool`, not `pubspec.yaml` directly. To avoid it failing to determine the version and assuming the latest (which will almost always be wrong in this repo):
- Adds a step to the `format` repo command to ensure that `pub get` appears to have been run, and runs it if not, and
- To avoid `pub get` running in `format` in CI, adds a deps-fetching step to the `repo_checks` task, as we have in other tasks that need to `pub get`.
This should unblock the roll.
> [tools] Run `pub get` before `format`

- packages/vector_graphics_compiler/lib/src/svg/resolver.dart
- packages/vector_graphics_compiler/lib/src/svg/visitor.dart
An upcoming fix to `avoid_renaming_method_parameters` will flag this rename.
(I updated the base class since that seems more correct.)
For references, here's the fix in flight: https://dart-review.googlesource.com/c/sdk/+/394662 …
> [vector_graphics_compiler] fix a renamed method parameter lint

- packages/camera/camera_windows/CHANGELOG.md
- packages/camera/camera_windows/pubspec.yaml
- packages/camera/camera_windows/windows/capture_controller.cpp
- packages/camera/camera_windows/windows/capture_controller.h
- packages/camera/camera_windows/windows/test/capture_controller_test.cpp
Fixes preview aspect ratio on Windows on some webcams (See https://github.com/flutter/flutter/issues/122966).
Before (main branch 7c1a05c8b12274e940e39adcb42896a32f57df32):
After:
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#ov …
> [camera_windows] Set device media type for video preview explicitly

- packages/google_identity_services_web/CHANGELOG.md
- packages/google_identity_services_web/lib/src/js_interop/package_web_tweaks.dart
- packages/google_identity_services_web/lib/src/js_loader.dart
- packages/google_identity_services_web/pubspec.yaml
- packages/google_identity_services_web/test/js_loader_test.dart
This PR adds logic to `google_identity_services_web/lib/src/js_loader.dart` to cause the `nonce` property to be property set when creating new script elements.
[pub …
> [google_identity_services_web] Set nonce properly in loadWebSdk().

- .github/dependabot.yml
Package was removed in https://github.com/flutter/packages/pull/6898.
However the path was still being passed to dependabot, which made it mad:
```
ERROR <job_916983349> Error during file fetching; aborting: No files found in /packages/platform/example/android/app
```
https://github.com/flutter/packages/actions/runs/11845225387/job/33010210199
I don't understand why this only started failing on https://github.com/flutter/packages/pull/8044 and not when the package was removed (since it moved that path from one place to another https://github.com/flutter/packages/pull/8036/files#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L571) …
> Remove packages/platform from dependabot config

- packages/web_benchmarks/CHANGELOG.md
- packages/web_benchmarks/lib/src/compilation_options.dart
- packages/web_benchmarks/lib/src/runner.dart
- packages/web_benchmarks/pubspec.yaml
Removes the `WebRenderer` enum, and its uses in the `CompilationOptions` class.
This is a breaking change because it's removing public API (`CompilationOptions.renderer`, `WebRenderer`), but in *practice* people shouldn't need any changes to their code (since the `CompilationOptions` class is used through named constructors). In any case, labeling as `v4.0.0`.
Related: https://github.com/flutter/flutter/issues/145954
[CLA]: …
> [web_benchmarks] Remove `WebRenderer` enum.

- .github/dependabot.yml
The [flutter/flutter](https://github.com/flutter/flutter/blob/09941e7b4781b81adeb7bce8b389e5b8b45325ca/.github/dependabot.yml#L19) and [flutter/engine](https://github.com/flutter/engine/blob/5f8e6e465584599bef234b5fea4320cf78041cc2/.github/dependabot.yml#L12-L13) repo put the `autosubmit` label on dependabot PRs so if all checks pass then no review is necessary and it will merge.  For example, https://github.com/flutter/flutter/pull/156024 merged without any human intervention.
In packages this is rarer (due to CHANGELOG and version bumps), but still happens, for example https://github.com/flutter/packages/pull/8097 bumps a `testImplementation` dependency and passed all checks.  
Add `autosubmit` to the packages repo for dependabot PRs so if all checks pass they just merge.  If checks …
> Add autosubmit label to dependabot PRs

- third_party/packages/flutter_svg/CHANGELOG.md
- third_party/packages/flutter_svg/lib/src/loaders.dart
- third_party/packages/flutter_svg/pubspec.yaml
- third_party/packages/flutter_svg/test/loaders_test.dart
closes https://github.com/flutter/flutter/issues/158928
Ensures that if a Client is created in `prepareMessage` it is closed after getting the resource. …
> [flutter_svg] Fix SvgNetworkLoader not closing internal http client

- packages/pigeon/CHANGELOG.md
- packages/pigeon/lib/dart/templates.dart
- packages/pigeon/lib/generator_tools.dart
- packages/pigeon/platform_tests/shared_test_plugin_code/lib/src/generated/proxy_api_tests.gen.dart
- packages/pigeon/pubspec.yaml
- packages/pigeon/test/dart/proxy_api_test.dart
It's common to access the `InstanceManager` when creating platform views, so this removes the `@protected` annotation to prevent lint warnings.
See https://github.com/flutter/packages/pull/7794#discussion_r1828288959 …
> [pigeon] Removes the `@protected` annotation from the InstanceManager field of the   `PigeonInternalProxyApiBaseClass`

- packages/shared_preferences/shared_preferences_android/CHANGELOG.md
- packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
- packages/shared_preferences/shared_preferences_android/android/src/main/kotlin/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.kt
- packages/shared_preferences/shared_preferences_android/android/src/main/kotlin/io/flutter/plugins/sharedpreferences/StringListObjectInputStream.kt
- packages/shared_preferences/shared_preferences_android/android/src/test/kotlin/io/flutter/plugins/sharedpreferences/SharedPreferencesTest.kt
- packages/shared_preferences/shared_preferences_android/pubspec.yaml
When decoding stored preferences for `List<String>` support, only allow lists and strings to avoid potentially instantiating other object types. …
> [shared_preferences] Limit Android decoding

- packages/local_auth/local_auth_android/CHANGELOG.md
- packages/local_auth/local_auth_android/pubspec.yaml
- packages/local_auth/local_auth_darwin/CHANGELOG.md
- packages/local_auth/local_auth_darwin/pubspec.yaml
Nothing in `intl` 0.20 breaks `local_auth` usage, so expand the compatibility window to include 0.20.x for better ecosystem compatibility.
Fixes https://github.com/flutter/flutter/issues/159591 …
> [local_auth] Add compatibility with intl 0.20

- packages/google_maps_flutter/google_maps_flutter/example/integration_test/src/maps_controller.dart
- packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/google_maps_tests.dart
- packages/google_maps_flutter/google_maps_flutter_android/lib/src/google_maps_flutter_android.dart
- packages/google_maps_flutter/google_maps_flutter_ios/example/ios14/integration_test/google_maps_test.dart
- packages/google_maps_flutter/google_maps_flutter_ios/lib/src/google_maps_flutter_ios.dart
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/google_maps_controller.dart
There are several intentional uses of deprecated members from other packages within the plugin group, so annotate them so that they don't show up in the regular team audits:
- App-facing package integration tests of the deprecated style method.
- Handling of deprecated marker bitmap formats.
These turned up in the [routine repo audit](https://github.com/flutter/flutter/blob/main/docs/infra/Packages-Gardener-Rotation.md#deprecations).
[Discord]: …
> [google_maps_flutter] Annotate deprecated member usage

- .github/dependabot.yml
Changes dependabot commit message prefix from "[gradle]" to "[dependabot]" since dependabot handles more than Gradle updates.
Also updates dependabot configuration docs link since the one included didn't work for me. …
> [dependabot] Generalizes dependabot commit message prefix 

- packages/video_player/video_player_avfoundation/CHANGELOG.md
- packages/video_player/video_player_avfoundation/darwin/RunnerTests/VideoPlayerTests.m
- packages/video_player/video_player_avfoundation/darwin/video_player_avfoundation/Sources/video_player_avfoundation/FVPVideoPlayer.m
- packages/video_player/video_player_avfoundation/pubspec.yaml
Supports the audio-only HLS on iOS. 
After through https://github.com/flutter/plugins/pull/4639 and https://github.com/flutter/plugins/pull/4727, we can play HLS videos and audios, but it does not support audio-only HLS. When attempting to play that on iOS, it never finishes initialization.
Show the before/after demonstration here: https://github.com/flutter/flutter/issues/156589#issuecomment-2408846446
Fixes: https://github.com/flutter/flutter/issues/156589
Test with https://github.com/flutter/assets-for-api-docs/pull/252 …
> [video_player_avfoundation] Support the audio-only HLS (.m3u8) on iOS

- packages/go_router_builder/pubspec.yaml
- packages/go_router_builder/test/flutter_test_config.dart
> [go_router_builder] Activate leak testing

- packages/flutter_image/example/macos/Runner/DebugProfile.entitlements
- packages/flutter_image/example/macos/Runner/Release.entitlements
- packages/google_sign_in/google_sign_in/example/macos/Runner/DebugProfile.entitlements
- packages/google_sign_in/google_sign_in/example/macos/Runner/Release.entitlements
- packages/google_sign_in/google_sign_in_ios/example/macos/Runner/DebugProfile.entitlements
- packages/google_sign_in/google_sign_in_ios/example/macos/Runner/Release.entitlements
- packages/image_picker/image_picker/example/macos/Runner/DebugProfile.entitlements
- packages/image_picker/image_picker/example/macos/Runner/Release.entitlements
- packages/in_app_purchase/in_app_purchase/example/macos/Runner/DebugProfile.entitlements
- packages/in_app_purchase/in_app_purchase/example/macos/Runner/Release.entitlements
- packages/in_app_purchase/in_app_purchase_storekit/example/macos/Runner/DebugProfile.entitlements
- packages/in_app_purchase/in_app_purchase_storekit/example/macos/Runner/Release.entitlements
- packages/path_provider/path_provider/example/macos/Runner/DebugProfile.entitlements
- packages/path_provider/path_provider/example/macos/Runner/Release.entitlements
- packages/path_provider/path_provider_foundation/example/macos/Runner/DebugProfile.entitlements
- packages/path_provider/path_provider_foundation/example/macos/Runner/Release.entitlements
- packages/pigeon/platform_tests/alternate_language_test_plugin/example/macos/Runner/DebugProfile.entitlements
- packages/pigeon/platform_tests/alternate_language_test_plugin/example/macos/Runner/Release.entitlements
- packages/shared_preferences/shared_preferences/example/macos/Runner/DebugProfile.entitlements
- packages/shared_preferences/shared_preferences/example/macos/Runner/Release.entitlements
- packages/shared_preferences/shared_preferences_foundation/example/macos/Runner/DebugProfile.entitlements
- packages/shared_preferences/shared_preferences_foundation/example/macos/Runner/Release.entitlements
- packages/url_launcher/url_launcher/example/macos/Runner/DebugProfile.entitlements
- packages/url_launcher/url_launcher/example/macos/Runner/Release.entitlements
- packages/url_launcher/url_launcher_macos/example/macos/Runner/DebugProfile.entitlements
- packages/url_launcher/url_launcher_macos/example/macos/Runner/Release.entitlements
- packages/video_player/video_player/example/macos/Runner/DebugProfile.entitlements
- packages/video_player/video_player/example/macos/Runner/Release.entitlements
- packages/video_player/video_player_avfoundation/example/macos/Runner/DebugProfile.entitlements
- packages/video_player/video_player_avfoundation/example/macos/Runner/Release.entitlements
Revert "Disable sandboxing directly for macOS tests (#6880)", commit 4a178f1ad9004e61fc58e5e8b704cee20e0b45d2, now that the `flutter`-level changes have reached `stable`.
Fixes https://github.com/flutter/flutter/issues/149844
> [ci] Re-enable macOS sandboxing

- packages/camera/camera/example/android/app/build.gradle
- packages/camera/camera/example/android/build.gradle
- packages/camera/camera/example/android/settings.gradle
- packages/camera/camera_android/example/android/app/build.gradle
- packages/camera/camera_android/example/android/build.gradle
- packages/camera/camera_android/example/android/settings.gradle
- packages/camera/camera_android_camerax/example/android/app/build.gradle
- packages/camera/camera_android_camerax/example/android/build.gradle
- packages/camera/camera_android_camerax/example/android/settings.gradle
- packages/pigeon/example/app/android/app/build.gradle
- packages/pigeon/example/app/android/build.gradle
- packages/pigeon/example/app/android/settings.gradle
Updated applying gradle plugins from usage of imperative apply to usage of declarative blocks {} apply for plugin example apps. All other android example apps under packages have been migrated.
Here are previous bulk migrations from imperative apply to declarative apply:
https://github.com/flutter/packages/pull/8019
https://github.com/flutter/packages/pull/8037
Previously migrated applying path_provider plugin example app from imperatively to declaratively in this PR https://github.com/flutter/packages/pull/7822. Tests for changes in the linked PR above.
More information on Flutter Gradle Pluggin Apply [here](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply)
All instances of minSdkVersion for example plugin apps use flutter.minSdkVersion instead of the …
> Applied Gradle Plugins Declaratively All Remaining Example Apps

- packages/video_player/video_player/example/integration_test/video_player_test.dart
- script/tool/lib/src/common/package_looping_command.dart
- script/tool/lib/src/create_all_packages_app_command.dart
- script/tool/lib/src/pubspec_check_command.dart
- script/tool/lib/src/update_min_sdk_command.dart
- script/tool/pubspec.yaml
- script/tool/test/create_all_packages_app_command_test.dart
- script/tool/test/update_min_sdk_command_test.dart
This PR fixes a couple of issues that have popped up in the CI of the tree in the last couple of days:
1. Disables some Android video_player tests that require network access.
2. Fixes our internal tool after a breaking change was made in an upstream dependency.
* Mitigates https://github.com/flutter/flutter/issues/160797
* Fixes https://github.com/flutter/flutter/issues/160799
[Discord]: …
> [ci] Cumulative fixes to reopen the tree.

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/example/lib/main.dart
- packages/camera/camera/example/pubspec.yaml
- packages/camera/camera/example/test/flutter_test_config.dart
- packages/camera/camera/pubspec.yaml
- packages/camera/camera/test/camera_preview_test.dart
- packages/camera/camera/test/flutter_test_config.dart
> [camera] Fix memory leaks in example and activate leak testing

- packages/pigeon/CHANGELOG.md
- packages/pigeon/README.md
- packages/pigeon/lib/generator_tools.dart
- packages/pigeon/pubspec.yaml
Updates the README to discuss two anti-patterns that clients should be aware of:
- Why Pigeon-generated code should not be used in public APIs.
- Why Pigeon-generated code should not be split across packages.
See related discussion in https://github.com/flutter/flutter/issues/160830
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/T …
> [pigeon] Discuss stability in README

- script/tool/lib/src/pubspec_check_command.dart
- script/tool/test/pubspec_check_command_test.dart
Adds `leak_tracker_flutter_testing` to the list of dependencies that can only be added to `dev_dependencies`.
> [tool] Ensure that leak_tracker_flutter_testing is dev-only

- packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter/test/flutter_test_config.dart
Activate leak testing for google_maps_flutter. The package uses disposable objects, it will make sure those are properly disposed.   …
> [google_maps_flutter] Activate leak testing

- packages/camera/camera_android_camerax/CHANGELOG.md
- packages/camera/camera_android_camerax/android/src/main/java/io/flutter/plugins/camerax/PreviewHostApiImpl.java
- packages/video_player/video_player_android/CHANGELOG.md
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
See https://github.com/flutter/flutter/issues/161256
This was causing errors with the Flutter->Packages roller:
```
> Task :camera_android_camerax:compileDebugJavaWithJavac
/b/s/w/ir/x/w/packages/packages/camera/camera_android_camerax/android/src/main/java/io/flutter/plugins/camerax/PreviewHostApiImpl.java:92: warning: [removal] onSurfaceDestroyed() in Callback has been deprecated and marked for removal
public void onSurfaceDestroyed() {
^
error: warnings found and -Werror specified
1 error
1 warning
``` …
> [camera_android_camerax][video_player_android] Suppresses deprecation of the `SurfaceProducer.Callback.onSurfaceDestroyed` method

- packages/camera/camera_platform_interface/CHANGELOG.md
- packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart
- packages/camera/camera_platform_interface/pubspec.yaml
- packages/camera/camera_platform_interface/test/camera_platform_interface_test.dart
Add API support query, supportsImageStreaming for checking if the camera platform supports image streaming.
As requested on this comment: https://github.com/flutter/packages/pull/8234#discussion_r1871232301
Step 3 from the [changing federated plugins guide](https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changing-federated-plugins), split off from #8250 with a new Dart test added.
[CLA]: …
> [camera_platform_interface] Add API support query for image streaming

- packages/go_router_builder/CHANGELOG.md
- packages/go_router_builder/lib/src/type_helpers.dart
- packages/go_router_builder/pubspec.yaml
- packages/go_router_builder/test_inputs/list.dart
- packages/go_router_builder/test_inputs/list.dart.expect
- packages/go_router_builder/test_inputs/set.dart
- packages/go_router_builder/test_inputs/set.dart.expect
- packages/go_router_builder/tool/run_tests.dart
fix issue:  https://github.com/flutter/flutter/issues/149675  …
> [go_router_builder] Add a fallback for a not null List or Set param 

- packages/go_router/CHANGELOG.md
- packages/go_router/README.md
- packages/go_router/pubspec.yaml
> [go_router] Rephrases readme to better describe the current status

- packages/camera/camera_android/pubspec.yaml
- packages/camera/camera_android/test/flutter_test_config.dart
- packages/camera/camera_android_camerax/pubspec.yaml
- packages/camera/camera_android_camerax/test/flutter_test_config.dart
- packages/camera/camera_avfoundation/pubspec.yaml
- packages/camera/camera_avfoundation/test/flutter_test_config.dart
- packages/camera/camera_platform_interface/pubspec.yaml
- packages/camera/camera_platform_interface/test/flutter_test_config.dart
- packages/camera/camera_windows/pubspec.yaml
- packages/camera/camera_windows/test/flutter_test_config.dart
Follow up of https://github.com/flutter/packages/pull/8287
Activates leak testing for the packages including a `test` folder
[Discord]: …
> [camera]: Activate leak testing for sub packages

- .github/dependabot.yml
After #8100,  https://github.com/flutter/packages/pull/8358 and https://github.com/flutter/packages/pull/8357 should have been grouped into one dependabot PR to bump io.mockk:mockk to 1.13.14 across all packages.  Fix the regex to match `io.mockk:mockk`. …
> Fix dependabot test-dependencies group io.mockk regex

- packages/camera/camera_android/CHANGELOG.md
- packages/camera/camera_android/lib/src/android_camera.dart
- packages/camera/camera_android/pubspec.yaml
- packages/camera/camera_android/test/android_camera_test.dart
- packages/camera/camera_android_camerax/CHANGELOG.md
- packages/camera/camera_android_camerax/lib/src/android_camera_camerax.dart
- packages/camera/camera_android_camerax/pubspec.yaml
- packages/camera/camera_android_camerax/test/android_camera_camerax_test.dart
- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/lib/src/avfoundation_camera.dart
- packages/camera/camera_avfoundation/pubspec.yaml
- packages/camera/camera_avfoundation/test/avfoundation_camera_test.dart
Add API support query, `supportsImageStreaming` for checking if the camera platform supports image streaming.
As requested on this comment: https://github.com/flutter/packages/pull/8234#discussion_r1871232301
Attempting to follow the [contribution guide wrt. changing federated plugins](https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changing-federated-plugins).
There is no issue to link to, but should I create one? …
> [camera] Add API support query for image streaming

- packages/two_dimensional_scrollables/lib/src/tree_view/tree.dart
- packages/two_dimensional_scrollables/test/tree_view/render_tree_test.dart
- packages/two_dimensional_scrollables/test/tree_view/tree_test.dart
unblocks https://github.com/flutter/flutter/pull/160564
Will go back through and implement `const` constructors in these spots once the framework PR lands.
> [two_dimensional_scrollables] prepare for `const AnimationStyle`

- packages/local_auth/local_auth_darwin/CHANGELOG.md
- packages/local_auth/local_auth_darwin/darwin/Tests/FLALocalAuthPluginTests.swift
- packages/local_auth/local_auth_darwin/darwin/local_auth_darwin/Sources/local_auth_darwin/FLALocalAuthPlugin.m
- packages/local_auth/local_auth_darwin/pubspec.yaml
LocalAuth  [`-canEvaluatePolicy::`](https://developer.apple.com/documentation/localauthentication/lacontext/canevaluatepolicy(_:error:)?language=objc) returns error `LAErrorBiometryNotAvailable` when either Face ID isn't available at the hardware level, OR the Face ID is available/setup but the permissions for the app were denied.
If it returns `LAErrorBiometryNotAvailable`, also check `biometryType` since this _should_ be none if there really is no biometry, but gets populated with [`LABiometryTypeTouchID`](https://developer.apple.com/documentation/localauthentication/labiometrytype/touchid?language=objc) when the FaceID hardware is available, but permission is denied.  I tried this on a iPhone 16 Pro which has Face ID but not Touch ID support.
Fixes …
> [local_auth_darwin] Handle when FaceID hardware is available but permissions have been denied for the app

- packages/pigeon/CHANGELOG.md
- packages/pigeon/lib/dart_generator.dart
- packages/pigeon/lib/generator_tools.dart
- packages/pigeon/pubspec.yaml
Adds compatibility with the latest major version of `analyzer` and `dart_style` (the latter being required to actually allow `analyzer` 7).
The breaking change of `dart_style` does affect our usage, so this updates rather than expands the allowed version. The range for `analyzer` is updated to drop versions older thas 6 since `dart_style` doesn't allow versions older than 6 anyway.
We have to pick a language version to use for formatting; this (somewhat arbitrarily) uses 3.6, to opt in to the new formatter.
Fixes https://github.com/flutter/flutter/issues/161820
Fixes https://github.com/flutter/flutter/issues/161583
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene. …
> [pigeon] Update analyzer and formatter

- script/tool/lib/src/federation_safety_check_command.dart
- script/tool/test/federation_safety_check_command_test.dart
Currently the special-casing for allowing comment-only changes to other packages in a plugin group as part of a single PR, which is necessary for some changes to add `// ignore` directives, allows comment lines, but not blank lines. Blank lines should be allowed since they are safe, and are expected for certain changes (notably, temporary file-level ignores).
> [tool] Allow blank lines in federated package changes

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/lib/src/camera_controller.dart
- packages/camera/camera/pubspec.yaml
- packages/camera/camera/test/camera_image_stream_test.dart
- packages/camera/camera/test/camera_preview_test.dart
Final step for introducing the `supportsImageStreaming` query method. Expose it through `CameraController`.
Previous steps:
- #8250
- #8307 …
> [camera] Add API support query for image streaming (app-facing)

- packages/video_player/video_player/pubspec.yaml
- packages/video_player/video_player/test/flutter_test_config.dart
- packages/video_player/video_player/test/video_player_test.dart
The package manipulates disposable objects. This PR activates leak testing to make sure disposable objects are correctly disposed.
It also fixes the memory leak warnings from the tests
[linked to at least …
> [video_player] Activate leak testing

- packages/rfw/pubspec.yaml
- packages/rfw/test/argument_decoders_test.dart
- packages/rfw/test/core_widgets_test.dart
- packages/rfw/test/flutter_test_config.dart
- packages/rfw/test/material_widgets_test.dart
- packages/rfw/test/readme_test.dart
- packages/rfw/test/remote_widget_test.dart
- packages/rfw/test/runtime_test.dart
- packages/rfw/test/source_locations_test.dart
The package manipulates disposable objects. This PR activates leak testing to make sure disposable objects are correctly disposed.
It also fixes the memory leak warnings from the tests
[linked to at least …
> [rfw] Activate leak testing

- packages/image_picker/image_picker_macos/CHANGELOG.md
- packages/image_picker/image_picker_macos/README.md
- packages/image_picker/image_picker_macos/pubspec.yaml
Since we don't currently plan to fix
https://github.com/flutter/flutter/issues/125829 in our implementation, and there is now a community implementation that does, reference that in the README and provide a link to quickly locate alternate implementations.
Also fixes a copy-paste mistake that was referencing the wrong app-facing plugin in the instructions.
[Discord]: …
> [image_picker] Reference alternate macOS implementations

- packages/in_app_purchase/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase/README.md
- packages/in_app_purchase/in_app_purchase/example/lib/main.dart
- packages/in_app_purchase/in_app_purchase/example/pubspec.yaml
- packages/in_app_purchase/in_app_purchase/pubspec.yaml
Extracted from https://github.com/flutter/packages/pull/8218.  …
> [in_app_purchase] Update in_app_purchase_android version in in_app_purchase

- packages/video_player/video_player/test/video_player_test.dart
- packages/video_player/video_player_android/lib/src/android_video_player.dart
- packages/video_player/video_player_avfoundation/lib/src/avfoundation_video_player.dart
- packages/video_player/video_player_platform_interface/CHANGELOG.md
- packages/video_player/video_player_platform_interface/lib/video_player_platform_interface.dart
- packages/video_player/video_player_platform_interface/pubspec.yaml
- packages/video_player/video_player_web/lib/video_player_web.dart
This PR is a subset of #8237 - it only adds platform interface changes.
Partially resolves [86613](https://github.com/flutter/flutter/issues/86613). …
> [video_player_platform_interface] Platform view support

- packages/vector_graphics/CHANGELOG.md
- packages/vector_graphics/lib/src/listener.dart
- packages/vector_graphics/lib/src/render_vector_graphic.dart
- packages/vector_graphics/lib/src/vector_graphics.dart
- packages/vector_graphics/pubspec.yaml
- packages/vector_graphics/test/flutter_test_config.dart
- packages/vector_graphics/test/vector_graphics_test.dart
The package manipulates disposable objects. This PR
- Fixes some memory leaks.
- Activates leak testing to make sure disposable objects are correctly disposed.
[linked to at least one issue that this PR …
> [vector_graphics] Fix memory leaks and activate leak testing [prod-leak-fix]

- script/configs/README.md
- script/configs/dart_unit_tests_wasm_exceptions.yaml
- script/configs/exclude_all_packages_app_wasm.yaml
- script/configs/exclude_integration_web_wasm.yaml
- script/tool/lib/src/analyze_command.dart
- script/tool/lib/src/common/package_command.dart
- script/tool/lib/src/pubspec_check_command.dart
- script/tool/test/common/package_command_test.dart
Multiple commands in the Flutter plugin tool have arguments that accepts a list of strings or a list of YAML files that contain a list of strings. This introduces a `getYamlListArg` helper so that this logic doesn't need to be duplicated multiple times. 
In a subsequent pull requests, this will be used to add a list of packages that are allowed to have Xcode warnings. This will be used by the google_sign_in_ios package which will have warnings when using SwiftPM.
Part of: https://github.com/flutter/flutter/issues/146904 …
> [tool] Refactor args of strings or YAML file lists

- packages/go_router_builder/CHANGELOG.md
- packages/go_router_builder/example/lib/all_types.g.dart
- packages/go_router_builder/example/test/location_test.dart
- packages/go_router_builder/lib/src/route_config.dart
- packages/go_router_builder/lib/src/type_helpers.dart
- packages/go_router_builder/pubspec.yaml
- packages/go_router_builder/test_inputs/iterable_with_default_value.dart.expect
- packages/go_router_builder/test_inputs/list.dart.expect
- packages/go_router_builder/test_inputs/set.dart.expect
- packages/go_router_builder/tool/run_tests.dart
Fixes https://github.com/flutter/flutter/issues/127373 …
> [go_router_builder] Fixes trailing `?` by comparing iterables

- packages/video_player/video_player_web/CHANGELOG.md
- packages/video_player/video_player_web/example/integration_test/video_player_web_test.dart
- packages/video_player/video_player_web/example/pubspec.yaml
- packages/video_player/video_player_web/lib/video_player_web.dart
- packages/video_player/video_player_web/pubspec.yaml
This PR adjusts the Web `video_player` implementation to the new platform interface which was introduced in #8453. Specifically, it renames `textureId` to `playerId` (which actually makes sense here, as there are no texture IDs on Web, it was just a "simulation" to comply with the interface).
This PR does not fix any issue directly, but it's related to [#86613](https://github.com/flutter/flutter/issues/86613).
[CLA]: …
> [video_player_web] Adjust Web implementation to the new platform interface

- packages/flutter_markdown/CHANGELOG.md
- packages/flutter_markdown/lib/src/builder.dart
- packages/flutter_markdown/lib/src/style_sheet.dart
- packages/flutter_markdown/pubspec.yaml
- packages/flutter_markdown/test/scrollable_test.dart
- packages/flutter_markdown/test/table_test.dart
Allows markdown tables to be scrollable with IntrinsicColumnWidth. Allows setting the scrollbar thumbVisibility based on stylesheet
- Additional fix from https://github.com/flutter/flutter/issues/129052 …
> [flutter_markdown] Allow tables to be scrollable with IntrinsicColumnWidth

- packages/shared_preferences/shared_preferences_tool/pubspec.yaml
This is causing the `flutter-analyze-try` Dart try bot to [fail](https://ci.chromium.org/ui/p/dart/builders/try/flutter-analyze-try/26500/overview) due to [upgrading the version pinned by flutter](https://github.com/flutter/flutter/commit/3e3bb9fdd586e71bc7fb797ee7158b53a54cd634).
> [shared_preferences_tool] Loosen vm_service constraint to allow for 15

- script/tool/lib/src/make_deps_path_based_command.dart
- script/tool/test/make_deps_path_based_command_test.dart
Updates `make-deps-path-based` to manually output dependency overrides in sorted order, as `YamlMap` apparently doesn't have a defined output ordering, leading to CI analysis failures in some cases.
Fixes https://github.com/flutter/flutter/issues/160810
[pub …
> [tool] Ensure that injected dependency overrides are sorted

- .ci.yaml
This PR moves the new Wasm shards out of bringup, so they become part of the normal testing flow.
Here's some information about the last ~90 builds in the staging builder:
* Unit tests, master channel
* [Shard 1](https://ci.chromium.org/ui/p/flutter/builders/staging/Linux_web%20web_dart_unit_test_wasm_shard_1%20master?limit=200)
* [Shard 2](https://ci.chromium.org/ui/p/flutter/builders/staging/Linux_web%20web_dart_unit_test_wasm_shard_2%20master?limit=200)
* Integration tests, master channel 
* [Shard 1](https://ci.chromium.org/ui/p/flutter/builders/staging/Linux_web%20web_platform_tests_wasm_shard_1%20master?limit=200)
* [Shard 2](https://ci.chromium.org/ui/p/flutter/builders/staging/Linux_web%20web_platform_tests_wasm_shard_2%20master?limit=200)
* [Shard …
> [ci] Move Wasm test shards out of bringup.

- packages/go_router/CHANGELOG.md
- packages/go_router/lib/src/route_data.dart
- packages/go_router/pubspec.yaml
- packages/go_router/test/route_data_test.dart
Part of https://github.com/flutter/flutter/issues/162055
The parameter will be used by `go_router_builder` …
> [go_router] Add `preload` parameter to `StatefulShellBranchData.$branch`

- packages/css_colors/CHANGELOG.md
- packages/css_colors/README.md
- packages/css_colors/pubspec.yaml
- packages/flutter_adaptive_scaffold/CHANGELOG.md
- packages/flutter_adaptive_scaffold/README.md
- packages/flutter_adaptive_scaffold/pubspec.yaml
- packages/flutter_image/CHANGELOG.md
- packages/flutter_image/README.md
- packages/flutter_image/pubspec.yaml
- packages/flutter_markdown/CHANGELOG.md
- packages/flutter_markdown/README.md
- packages/flutter_markdown/pubspec.yaml
- packages/ios_platform_images/CHANGELOG.md
- packages/ios_platform_images/README.md
- packages/ios_platform_images/pubspec.yaml
- packages/palette_generator/CHANGELOG.md
- packages/palette_generator/README.md
- packages/palette_generator/pubspec.yaml
Updates the READMEs for packages slated for deprecation on April 30, 2025 to indicate that they will be deprecated, and to link to the issue coordinating discussion about possible community ownership.
See https://github.com/flutter/flutter/issues/162960
[pub …
> [various] Add deprecation notices to READMEs

- packages/go_router_builder/CHANGELOG.md
- packages/go_router_builder/lib/src/route_config.dart
- packages/go_router_builder/pubspec.yaml
- packages/go_router_builder/test_inputs/stateful_shell_branch_with_preload_data.dart
- packages/go_router_builder/test_inputs/stateful_shell_branch_with_preload_data.dart.expect
Fixes https://github.com/flutter/flutter/issues/162055
Follow up of https://github.com/flutter/packages/pull/8545 …
> [go_router_builder] Add support for `TypedStatefulShellBranch`'s `preload`

- packages/video_player/video_player/example/integration_test/video_player_test.dart
Re-enables `asset videos live stream duration != 0` test that was previously disabled do to emulators having revoked access to the network.
Looks like this passed in https://firebase.corp.google.com/project/flutter-infra-staging/testlab/histories/bh.7dcabc1142c31699/matrices/7642642580824193465/executions/bs.d4c88757f607fa85/testcases/10/test-cases from https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_device_tests_shard_1%20master/14302/overview but let me know if I'm wrong!
Fixes https://github.com/flutter/flutter/issues/160797; see that issue for more details. …
> [video_player] Re-enables `asset videos live stream duration != 0` test for Android

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/FLTCaptureDevice.m
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/include/camera_avfoundation/FLTCaptureDevice.h
- packages/camera/camera_avfoundation/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/163295. Unfortunately Obj-C didn't provide any compile-time safety check for that. …
> [camera] Fix crash when setting activeFormat on FLTCaptureDevice

- packages/camera/camera_windows/CHANGELOG.md
- packages/camera/camera_windows/example/windows/CMakeLists.txt
- packages/camera/camera_windows/pubspec.yaml
- packages/camera/camera_windows/windows/capture_device_info.h
- packages/file_selector/file_selector_windows/CHANGELOG.md
- packages/file_selector/file_selector_windows/example/windows/CMakeLists.txt
- packages/file_selector/file_selector_windows/pubspec.yaml
- packages/file_selector/file_selector_windows/windows/file_selector_plugin.cpp
- packages/image_picker/image_picker_windows/example/windows/CMakeLists.txt
- packages/local_auth/local_auth_windows/example/windows/CMakeLists.txt
- packages/path_provider/path_provider_windows/example/windows/CMakeLists.txt
- packages/pigeon/platform_tests/test_plugin/example/windows/CMakeLists.txt
- packages/pigeon/platform_tests/test_plugin/windows/test_plugin.cpp
- packages/url_launcher/url_launcher_windows/example/windows/CMakeLists.txt
As the Visual Studio C++ compiler moves toward increasingly standards-compliant behavior, things it allows may become errors in the future (as seen in https://github.com/flutter/flutter/issues/163296 and the issues it references). To avoid a whole class of future problems, this enables `/permissive-` for the example apps of all of our Windows plugins that have native code, and fixes the resulting violations.
Fixes https://github.com/flutter/flutter/issues/163296
[Discord]: …
> [various] Enable `permissive-` for Windows plugin examples

- packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/platform_interface/google_maps_flutter_platform.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/platform_interface/google_maps_inspector_platform.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/camera.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/platform_interface/google_maps_flutter_platform_test.dart
This PR contains platform interface changes for support to adjust camera animation speed (https://github.com/flutter/packages/pull/7648).
Linked issue:  https://github.com/flutter/flutter/issues/39810
Linked issue:  https://github.com/flutter/flutter/issues/44284
[linked to at least one issue that this PR …
> [google_maps_flutter] Platform interface for camera animation duration

- .ci.yaml
This test has been at the edge of its time limit for a while, and is now consistently timing out. Longer term we should see if we can shorten the Pigeon test time (it accounts for about 20 minutes), but for now, increase the timeout so that it doesn't fail.
> [ci] Lengthen custom tests timeout

- packages/url_launcher/url_launcher_web/CHANGELOG.md
- packages/url_launcher/url_launcher_web/example/integration_test/link_widget_test.dart
- packages/url_launcher/url_launcher_web/lib/src/link.dart
- packages/url_launcher/url_launcher_web/pubspec.yaml
When a DOM click event is received, we need to make a decision before the end of the event loop whether to allow the browser to navigate or not. At the end of the event loop, the browser will perform the navigation if we don't prevent it.
The problem occurs when the `followLink` signal arrives AFTER the event loop (this can happen in semantics mode when the web engine uses a debouncer to queue events and send them to the framework after some delay). This leads to a situation where we can't make a definitive decision by the end of the event loop, so this PR does the following:
1. [best case] If the `followLink` signal is received before the end of the event loop, we let the browser do the navigation for a full web link experience.
2. [meh case] If no `followLink` signal is received before …
> [url_launcher][web] Prevent browser from navigating when followLink isn't called

- packages/camera/camera_android_camerax/test/capture_request_options_test.dart
- packages/camera/camera_android_camerax/test/focus_metering_action_test.dart
- packages/camera/camera_android_camerax/test/image_analysis_test.dart
- packages/camera/camera_android_camerax/test/image_capture_test.dart
- packages/camera/camera_android_camerax/test/metering_point_test.dart
- packages/camera/camera_android_camerax/test/preview_test.dart
- packages/camera/camera_android_camerax/test/recorder_test.dart
Skips the `create does not call create on the Java side` tests due to excessive flake, while the issue is investigated.
https://github.com/flutter/flutter/issues/164132
> [camera] Disable flaky tests

- packages/file_selector/file_selector_android/android/build.gradle
- packages/google_maps_flutter/google_maps_flutter/example/android/app/build.gradle
- packages/google_maps_flutter/google_maps_flutter_android/android/build.gradle
- packages/google_maps_flutter/google_maps_flutter_android/example/android/app/build.gradle
- packages/google_sign_in/google_sign_in/example/android/app/build.gradle
- packages/google_sign_in/google_sign_in_android/example/android/app/build.gradle
- packages/image_picker/image_picker/example/android/app/build.gradle
- packages/interactive_media_ads/android/build.gradle
- packages/quick_actions/quick_actions/example/android/app/build.gradle
- packages/quick_actions/quick_actions_android/example/android/app/build.gradle
- packages/url_launcher/url_launcher_android/android/build.gradle
- packages/video_player/video_player_android/android/build.gradle
- packages/webview_flutter/webview_flutter/example/android/app/build.gradle
- packages/webview_flutter/webview_flutter_android/android/build.gradle
This is pulled out of https://github.com/flutter/packages/pull/8693 to land on its own while the other issues with that PR are investigated, since it's a useful change regardless.
This updates all packages in the repo to have `androidx.test:core` 1.4.0 if it's not already higher. This fixes a latent problem where older versions of `androidx.test.core` aren't compatible with targeting the current SDK, because it has activities that are not annotated as exported. This issue is currently being masked by the dependency on `integration_test`, which forced a higher version of that package, but `integration_test` will stop exporting that dependency onto the app as of recent master, dropping all the packages here back to a too-old `androidx.test:core`.
> [various] Bump androidx.test:core to 1.4.0

- packages/pigeon/tool/shared/test_runner.dart
Pigeon's tests are taking a substantial amount of CI time, so it would be useful to be able to audit how long each step takes so we have more information if we need to shorten or shard these tests.
> [pigeon] Timestamp test steps in CI

- packages/local_auth/local_auth/example/android/app/build.gradle
part of flutter/flutter/issues/149836
After this pr `find . -type f -name "build.gradle" | xargs grep -e "targetSdk" | tr -d '=' | tr -s ' ' | grep -v flutter\.targetSdkVersion` will return no results.
> [local_auth] Update to use flutter.targetSdkVersion

- packages/flutter_plugin_android_lifecycle/CHANGELOG.md
- packages/flutter_plugin_android_lifecycle/android/build.gradle
- packages/flutter_plugin_android_lifecycle/pubspec.yaml
Fixes #flutter/flutter/issues/164362
Functionally a revert of https://github.com/flutter/packages/pull/8700 which found out what would break.
> [flutter_plugin_android_lifecycle] Removes flutter.compileSdkVersion for 35 to support flutter versions prior to 3.27

- packages/video_player/video_player_avfoundation/darwin/RunnerTests/VideoPlayerTests.m
See https://github.com/flutter/flutter/issues/164381
> [video_player] Disable flaky `testAudioOnlyHLSControls`

- script/tool/lib/src/gradle_check_command.dart
- script/tool/test/gradle_check_command_test.dart
Checks that plugins use `compileSdk` rather than the deprecated `compileSdkVersion`, and that if they set it to
`flutter.compileSdkVersion` they require at least Flutter 3.27.
Would have prevented https://github.com/flutter/flutter/issues/164362
> [tool] Validate gradle compileSdk

- packages/flutter_plugin_android_lifecycle/CHANGELOG.md
- packages/flutter_plugin_android_lifecycle/android/build.gradle
- packages/flutter_plugin_android_lifecycle/pubspec.yaml
- **[flutter_plugin_android_lifecycle] Uses flutter.compileSdkVersion, bumps minimum flutter version to 3.27 (first version to have support)**
related to flutter/flutter/issues/149836 
Functionally a reland of https://github.com/flutter/packages/pull/8700 after the "revert" in https://github.com/flutter/packages/pull/8758
> [flutter_plugin_android_lifecycle] Uses flutter.compileSdkVersion, bumps minimum flutter version to 3.27

- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/darwin/Tests/FrameInfoProxyAPITests.swift
- packages/webview_flutter/webview_flutter_wkwebview/darwin/webview_flutter_wkwebview/Sources/webview_flutter_wkwebview/FrameInfoProxyAPIDelegate.swift
- packages/webview_flutter/webview_flutter_wkwebview/darwin/webview_flutter_wkwebview/Sources/webview_flutter_wkwebview/WebKitLibrary.g.swift
- packages/webview_flutter/webview_flutter_wkwebview/example/pubspec.yaml
- packages/webview_flutter/webview_flutter_wkwebview/lib/src/common/web_kit.g.dart
- packages/webview_flutter/webview_flutter_wkwebview/lib/src/webkit_webview_controller.dart
- packages/webview_flutter/webview_flutter_wkwebview/pigeons/web_kit.dart
- packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml
I manually verified with the example provided in the issue below that the `WKFrameInfo.request` also returns nil with the old Objective-C implementation. This crash seems to be caused by the Swift code crashing when it encounters a nil value that should be nonnull.
Fixes https://github.com/flutter/flutter/issues/163549
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/C …
> [webview_flutter_wkwebview] Fixes crash with nil `WKFrameInfo.request`

- packages/rfw/CHANGELOG.md
- packages/rfw/lib/src/flutter/runtime.dart
- packages/rfw/pubspec.yaml
- packages/rfw/test/runtime_test.dart
**Make widget builders work with loops**
Fixes https://github.com/flutter/flutter/issues/161544
[exempt …
> [rfw] Make widget builders work with loops

- packages/camera/camera_avfoundation/example/ios/Runner.xcodeproj/project.pbxproj
- packages/camera/camera_avfoundation/example/ios/RunnerTests/CameraPluginDelegatingMethodTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/Mocks/MockFLTCam.swift
Backfills tests for the CameraPlugin class as part of https://github.com/flutter/flutter/issues/119109
This PR adds tests for methods of `CameraPlugin` that only delegate to a `FLTCam` instance without any (or almost any for `startVideoRecording`) logic. In most circumstances, I would argue that those methods are so trivial that there is no point in testing them but for a plugin rewrite I believe those tests provide a little bit of value. The tests are also appropriately simple to write. …
> [camera_avfoundation] Tests backfilling - part 2

- packages/camera/camera_avfoundation/example/ios/Runner.xcodeproj/project.pbxproj
- packages/camera/camera_avfoundation/example/ios/RunnerTests/FLTCamSetFlashModeTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/Mocks/MockCaptureDevice.h
- packages/camera/camera_avfoundation/example/ios/RunnerTests/Mocks/MockCaptureDevice.m
- packages/camera/camera_avfoundation/example/ios/RunnerTests/PhotoCaptureTests.swift
Backfills tests for the `FLTCam` class as part of https://github.com/flutter/flutter/issues/119109
Adds tests for the `setFlashMode` method of the `FLTCam` class.
[pub …
> [camera_avfoundation] Tests backfilling - part 3

- packages/camera/camera/test/camera_value_test.dart
A unit test in the app-facing package that predates federation is asserting an expected string that includes constant text that is controlled by a `toString` method from the platform interface package. This fixes the test to only assert the parts that are within the package's control.
Unblocks https://github.com/flutter/packages/pull/8723 …
> [camera] Fix unit test asserting external value

- .github/PULL_REQUEST_TEMPLATE.md
I hadn't added anything about a carve-out originally because I couldn't think of a way that wouldn't make the checklist much more confusing, but it occurred to me that a footnote would get it out of the way while still making the exemption explicit.
> Add a carve-out on the commenting requirement

- packages/image_picker/image_picker_linux/CHANGELOG.md
- packages/image_picker/image_picker_linux/lib/image_picker_linux.dart
- packages/image_picker/image_picker_linux/pubspec.yaml
- packages/image_picker/image_picker_linux/test/image_picker_linux_test.dart
The previous version had a typo where it specified the mime types using the `extensions` field.
~~part of https://github.com/flutter/flutter/issues/148635~~
> [image_picker] Fix getMedia on Linux

- packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter/example/integration_test/src/tiles_inspector.dart
- packages/google_maps_flutter/google_maps_flutter/example/lib/ground_overlay.dart
- packages/google_maps_flutter/google_maps_flutter/example/lib/main.dart
- packages/google_maps_flutter/google_maps_flutter/example/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter/lib/google_maps_flutter.dart
- packages/google_maps_flutter/google_maps_flutter/lib/src/controller.dart
- packages/google_maps_flutter/google_maps_flutter/lib/src/google_map.dart
- packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter/test/fake_google_maps_flutter_platform.dart
- packages/google_maps_flutter/google_maps_flutter/test/groundoverlay_updates_test.dart
Adds Ground Overlay support for google_maps_flutter plugin.
Fixes https://github.com/flutter/flutter/issues/26479
[Android](https://developers.google.com/maps/documentation/android-sdk/groundoverlay):
[iOS](https://developers.google.com/maps/documentation/ios-sdk/overlays):
[Web](https://developers.google.com/maps/documentation/javascript/groundoverlays):
Documentation for groundOverlays parameter on app-facing plugin:
[CLA]: …
> [google_maps_flutter] Support for Ground Overlay

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/example/ios/Runner.xcodeproj/project.pbxproj
- packages/camera/camera_avfoundation/example/ios/RunnerTests/CameraSettingsTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/FLTCamSetDeviceOrientationTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/Mocks/MockCaptureConnection.h
- packages/camera/camera_avfoundation/example/ios/RunnerTests/Mocks/MockCaptureConnection.m
- packages/camera/camera_avfoundation/example/ios/RunnerTests/Mocks/MockCapturePhotoOutput.h
- packages/camera/camera_avfoundation/example/ios/RunnerTests/Mocks/MockCapturePhotoOutput.m
- packages/camera/camera_avfoundation/example/ios/RunnerTests/Mocks/MockCaptureVideoDataOutput.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/SampleBufferTests.swift
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/FLTCam.m
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/FLTCamMediaSettingsAVWrapper.m
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/FLTCaptureConnection.m
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/FLTCapturePhotoOutput.m
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/FLTCaptureVideoDataOutput.m
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/include/camera_avfoundation/FLTCamMediaSettingsAVWrapper.h
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/include/camera_avfoundation/FLTCam_Test.h
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/include/camera_avfoundation/FLTCaptureConnection.h
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/include/camera_avfoundation/FLTCaptureOutput.h
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/include/camera_avfoundation/FLTCapturePhotoOutput.h
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/include/camera_avfoundation/FLTCaptureVideoDataOutput.h
- packages/camera/camera_avfoundation/pubspec.yaml
Backfills tests for the `FLTCam` class as part of https://github.com/flutter/flutter/issues/119109
Adds tests for the `setDeviceOrientation` method of the `FLTCam` class. I had to add `FLTCaptureVideoDataOutput` and `FLTCaptureOutput` wrappers around AVFoundation classes to make it mockable (similar to the existing `FLTCapturePhotoOutput`wrapper)
[Discord]: …
> [camera_avfoundation] Tests backfilling - part 4

- packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test_legacy.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/legacy/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart
Tests on macOS were [failing](https://github.com/flutter/flutter/issues/164632#issuecomment-2741901749) due to `videoTestBase64` not being initialized. This PR moved `videoTestBase64` initialization into each individual test.
Tests on macOS were [failing](https://github.com/flutter/flutter/issues/164632#issuecomment-2740875017) due matching failing because on some devices JavaScript turns a boolean as a string like `"false"` and sometimes as a number like `"0"`. This PR changes it to accept either regardless of device.
Some legacy iOS tests are [flaking](https://github.com/flutter/flutter/issues/164632#issue-2897773107) with Xcode 16, so we're skipping them for now.
[^1]: Regular contributors who have …
> [webview_flutter] Fix macOS test issues and skip some legacy iOS tests

- packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter/example/integration_test/src/maps_inspector.dart
- packages/google_maps_flutter/google_maps_flutter/example/lib/animate_camera.dart
- packages/google_maps_flutter/google_maps_flutter/example/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter/lib/src/controller.dart
- packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter/test/camera_test.dart
- packages/google_maps_flutter/google_maps_flutter/test/fake_google_maps_flutter_platform.dart
Adds ability to configure camera animation duration on Android and iOS.
Resolves [#39810](https://github.com/flutter/flutter/issues/39810)
Resolves [#44284](https://github.com/flutter/flutter/issues/44284) …
> [google_maps_flutter] Add ability to animate camera with duration

- packages/pigeon/lib/src/cpp/cpp_generator.dart
- packages/pigeon/lib/src/dart/dart_generator.dart
- packages/pigeon/lib/src/generator.dart
- packages/pigeon/lib/src/generator_tools.dart
- packages/pigeon/lib/src/gobject/gobject_generator.dart
- packages/pigeon/lib/src/java/java_generator.dart
- packages/pigeon/lib/src/kotlin/kotlin_generator.dart
- packages/pigeon/lib/src/objc/objc_generator.dart
- packages/pigeon/lib/src/swift/swift_generator.dart
This update is necessary for an impending linter change. 
Corrects improper usage of generics in the options for generators
> [pigeon] correct usage of extended generics in generator methods

- packages/google_adsense/CHANGELOG.md
- packages/google_adsense/example/integration_test/experimental_ad_unit_widget_test.dart
- packages/google_adsense/lib/src/adsense/ad_unit_widget.dart
- packages/google_adsense/pubspec.yaml
These unit tests were failing when a skwasm change caused a subtle timing difference. See https://github.com/flutter/flutter/issues/165347
> Use a more deterministic way of waiting for ad widgets to be ready.

- packages/google_maps_flutter/google_maps_flutter/example/integration_test/src/maps_inspector.dart
This test stared hanging in CI due to OOB failure. Skipping to re-open the tree while it's investigated.
See https://github.com/flutter/flutter/issues/166139
> [google_maps_flutter] Skip test that hangs iOS CI

- packages/extension_google_sign_in_as_googleapis_auth/CHANGELOG.md
- packages/extension_google_sign_in_as_googleapis_auth/pubspec.yaml
Allows using the extension with v2.0.0 of `googleapis_auth`, which has just been published:
https://pub.dev/packages/googleapis_auth/changelog#200
> [extension_gsi] Support the latest version of googleapis_auth

- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/legacy/webview_flutter_test.dart
I previously skipped these tests in `webview_flutter_wkwebview` example app (https://github.com/flutter/packages/pull/8895), but need to also skip in the `webview_flutter` example app.
Temporary solution for https://github.com/flutter/flutter/issues/164632.
[CLA]: …
> [webview_flutter] Skip flaky legacy tests on iOS

- packages/google_maps_flutter/google_maps_flutter/example/integration_test/src/maps_inspector.dart
Now `testAnimateCameraWithDuration` is failing as well, as I had expected previously. It's not clear why it didn't fail in the PR where I disabled the `WithoutDuration` variant but is failing now.
Part of https://github.com/flutter/flutter/issues/166139
> [google_maps_flutter] Skip more hanging iOS tests

- packages/multicast_dns/CHANGELOG.md
- packages/multicast_dns/lib/multicast_dns.dart
- packages/multicast_dns/pubspec.yaml
- packages/multicast_dns/test/client_test.dart
MDnsClient::Listen now supports an optional onError callback function,
called in case of a stream error. If omitted any errors on the stream
are considered unhandled, and will be passed to the current [Zone]'s
error handler. By default unhandled async errors are treated as if they
were uncaught top-level errors.
This fixes an unhandled exception occuring (tested on Android), when the
network is disconnected.
Fixes https://github.com/flutter/flutter/issues/165482 …
> [multicast_dns] MDnsClient::listen supports onError callback

- packages/shared_preferences/shared_preferences_android/CHANGELOG.md
- packages/shared_preferences/shared_preferences_android/android/src/main/kotlin/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.kt
- packages/shared_preferences/shared_preferences_android/example/android/app/src/main/java/dev/flutter/plugins/shared_preferences_example/MainActivity.java
- packages/shared_preferences/shared_preferences_android/example/integration_test/shared_preferences_test.dart
- packages/shared_preferences/shared_preferences_android/pubspec.yaml
Resolves issue [#165781](https://github.com/flutter/flutter/issues/165781) by falling back to reading preference as an int then upcasted to a Long.
[CLA]: …
> [shared_preferences] Allow reading int as long in SharedPreferences #165781

- script/tool/lib/src/common/flutter_command_utils.dart
- script/tool/lib/src/fetch_deps_command.dart
- script/tool/lib/src/firebase_test_lab_command.dart
- script/tool/lib/src/lint_android_command.dart
- script/tool/lib/src/native_test_command.dart
- script/tool/lib/src/xcode_analyze_command.dart
- script/tool/test/firebase_test_lab_command_test.dart
- script/tool/test/xcode_analyze_command_test.dart
Currently xcode-analyze relies on the native project files already having been generated. This is unreliably locally, and now is problematic on CI as well since Xcode builds now (as of https://github.com/flutter/flutter/pull/165916) must match the last build mode, so analysis will fail if the previous CI step built in release mode (as is currently the case).
This adds a config-only build call in debug mode before analyzing. Since running a config-only build is a common operation in the tool, this extracts a helper to abstract the logic.
Unblocks the flutter/flutter->flutter/packages roller.
> [tool] Run a config-only build before Xcode analyze

- script/tool/lib/src/native_test_command.dart
- script/tool/test/native_test_command_test.dart
Follow-up to https://github.com/flutter/packages/pull/9075. On iOS and macOS, `native-test` also requires an unconditional project file generatino in debug mode now, to ensure that the debug Xcode build of the tests will not fail due to a build mode mismatch.
Unblocks the flutter/flutter->flutter/packages roller.
> [tool] Run config-only build for iOS/macOS native-test

- packages/go_router/CHANGELOG.md
- packages/go_router/README.md
- packages/go_router/lib/src/match.dart
- packages/go_router/lib/src/route.dart
- packages/go_router/pubspec.yaml
- packages/go_router/test/go_router_test.dart
Fixes https://github.com/flutter/flutter/issues/162487
Fixes https://github.com/flutter/flutter/issues/166576
[Discord]: …
> [go_router] Adds `caseSensitive` to `GoRoute`

- packages/google_sign_in/google_sign_in_ios/CHANGELOG.md
- packages/google_sign_in/google_sign_in_ios/darwin/google_sign_in_ios.podspec
- packages/google_sign_in/google_sign_in_ios/darwin/google_sign_in_ios/Package.swift
- packages/google_sign_in/google_sign_in_ios/pubspec.yaml
Updates the SDK version from 7.1 to 8.0, to pick up Firebase App Check support.
The breaking change in the SDK is because it dropped iOS 11 support, which this plugin already didn't support.
Fixes https://github.com/flutter/flutter/issues/166967 …
> [google_sign_is] Update iOS SDK to 8.0

- packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/platform_webview_controller.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/types/over_scroll_mode.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/types/types.dart
- packages/webview_flutter/webview_flutter_platform_interface/pubspec.yaml
- packages/webview_flutter/webview_flutter_platform_interface/test/platform_webview_controller_test.dart
Platform interface portion of https://github.com/flutter/flutter/issues/57090
[Discord]: …
> [webview_flutter_platform_interface] Adds method to set overscroll mode

- packages/webview_flutter/webview_flutter_android/CHANGELOG.md
- packages/webview_flutter/webview_flutter_android/android/src/main/java/io/flutter/plugins/webviewflutter/AndroidWebkitLibrary.g.kt
- packages/webview_flutter/webview_flutter_android/android/src/main/java/io/flutter/plugins/webviewflutter/ViewProxyApi.java
- packages/webview_flutter/webview_flutter_android/android/src/test/java/io/flutter/plugins/webviewflutter/ViewTest.java
- packages/webview_flutter/webview_flutter_android/example/pubspec.yaml
- packages/webview_flutter/webview_flutter_android/lib/src/android_webkit.g.dart
- packages/webview_flutter/webview_flutter_android/lib/src/android_webview_controller.dart
- packages/webview_flutter/webview_flutter_android/pigeons/android_webkit.dart
- packages/webview_flutter/webview_flutter_android/pubspec.yaml
- packages/webview_flutter/webview_flutter_android/test/android_webview_controller_test.dart
- packages/webview_flutter/webview_flutter_android/test/android_webview_controller_test.mocks.dart
- packages/webview_flutter/webview_flutter_android/test/android_webview_cookie_manager_test.mocks.dart
- packages/webview_flutter/webview_flutter_android/test/legacy/webview_android_widget_test.mocks.dart
- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/example/pubspec.yaml
- packages/webview_flutter/webview_flutter_wkwebview/lib/src/webkit_webview_controller.dart
- packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml
- packages/webview_flutter/webview_flutter_wkwebview/test/webkit_webview_controller_test.dart
Platform implementation for https://github.com/flutter/flutter/issues/57090
[Discord]: …
> [webview_flutter_android][webview_flutter_wkwebview] Adds platform implementations to set over-scroll mode

- packages/go_router/CHANGELOG.md
- packages/go_router/lib/src/route_data.dart
- packages/go_router/pubspec.yaml
- packages/go_router/test/route_data_test.dart
First part of https://github.com/flutter/flutter/issues/167277
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contribut …
> [go_router_builder] Add `caseSensitive` to `TypedGoRoute`

- packages/in_app_purchase/in_app_purchase_storekit/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_storekit/darwin/in_app_purchase_storekit/Sources/in_app_purchase_storekit/InAppPurchasePlugin.swift
- packages/in_app_purchase/in_app_purchase_storekit/darwin/in_app_purchase_storekit/Sources/in_app_purchase_storekit/StoreKit2/InAppPurchasePlugin+StoreKit2.swift
- packages/in_app_purchase/in_app_purchase_storekit/example/shared/RunnerTests/InAppPurchaseStoreKit2PluginTests.swift
- packages/in_app_purchase/in_app_purchase_storekit/pubspec.yaml
Equeue to the channel from the main thread to avoid channel safety issues.
Background: `sendTransactionUpdate` can be called from the main thread, where it is safe to send messages on the `onTransactionsUpdated` channel. This seems to happen when the purchase code path succeeds and generates a transaction. However `sendTransactionUpdate` can also be called on non-main threads serving background executors, when transaction callbacks result from restoring purchases or other transactions are reported to the transaction subscription (eg. a purchase made outside of the app, or a refund is issued -- this can be triggered from XCode's StoreKit Test transaction log). In these cases, at least sometimes, an error is logged about writing to a channel on a non-platform thread (see the issue below). …
> [in_app_purchase] Write to the transactions update queue from the main thread

- AUTHORS
- packages/vector_graphics_compiler/CHANGELOG.md
- packages/vector_graphics_compiler/lib/src/svg/parser.dart
- packages/vector_graphics_compiler/lib/vector_graphics_compiler.dart
- packages/vector_graphics_compiler/pubspec.yaml
- packages/vector_graphics_compiler/test/parser_test.dart
Fixes [#158735](https://github.com/flutter/flutter/issues/158735)
[Discord]: …
> [vector_graphics_compiler] fix: Stroke opacity not applied

- CODEOWNERS
Remove loic-sharma and add LongCatIsLooong to iOS CODEOWNERS. Also, assign 2 people to each plugin.
[Discord]: …
> Redistribute iOS CODEOWNERS

- packages/google_maps_flutter/google_maps_flutter_ios/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_ios/example/ios14/integration_test/google_maps_test.dart
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapMarkerController.h
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapMarkerController.m
- packages/google_maps_flutter/google_maps_flutter_ios/pubspec.yaml
Fixes a regression introduced on version 2.12.0: _Adds support for marker clustering_ (https://github.com/flutter/packages/pull/6186), where visible info windows are not visible after marker updates.
Adds tests accordingly.
Fixes https://github.com/flutter/flutter/issues/167459
Related to https://github.com/flutter/flutter/issues/159471 …
> [google_maps_flutter_ios] Fix iOS regression where updating a marker hides its info window

- packages/camera/camera_android_camerax/CHANGELOG.md
- packages/camera/camera_android_camerax/lib/src/android_camera_camerax.dart
- packages/camera/camera_android_camerax/pubspec.yaml
- packages/camera/camera_android_camerax/test/android_camera_camerax_test.dart
This ensures DeviceOrientationManager is released on dispose.  Prevents leaked IntentReceiver on close.
Fixes: https://github.com/flutter/flutter/issues/166529
> [camerax] Ensure DeviceOrientationManager stops on dispose

- packages/go_router_builder/CHANGELOG.md
- packages/go_router_builder/example/lib/case_sensitive_example.dart
- packages/go_router_builder/example/lib/case_sensitive_example.g.dart
- packages/go_router_builder/example/pubspec.yaml
- packages/go_router_builder/example/test/case_sensitivity_example_test.dart
- packages/go_router_builder/lib/src/route_config.dart
- packages/go_router_builder/pubspec.yaml
- packages/go_router_builder/test_inputs/case_sensitivity.dart
- packages/go_router_builder/test_inputs/case_sensitivity.dart.expect
Fixes https://github.com/flutter/flutter/issues/167277
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat …
> [go_router_builder] Add support for caseSensitive

- packages/css_colors/CHANGELOG.md
- packages/css_colors/README.md
- packages/css_colors/pubspec.yaml
- packages/flutter_adaptive_scaffold/CHANGELOG.md
- packages/flutter_adaptive_scaffold/README.md
- packages/flutter_adaptive_scaffold/pubspec.yaml
- packages/flutter_image/CHANGELOG.md
- packages/flutter_image/README.md
- packages/flutter_image/pubspec.yaml
- packages/flutter_markdown/CHANGELOG.md
- packages/flutter_markdown/README.md
- packages/flutter_markdown/pubspec.yaml
- packages/ios_platform_images/CHANGELOG.md
- packages/ios_platform_images/README.md
- packages/ios_platform_images/pubspec.yaml
- packages/palette_generator/CHANGELOG.md
- packages/palette_generator/README.md
- packages/palette_generator/pubspec.yaml
Updates the READMEs of the packages that are being discontinued to indicate that they are now discontinued.
The source will be removed in a follow-up PR.
See https://github.com/flutter/flutter/issues/162960
[Discord]: …
> [various] Update READMEs of discontinued packages

- packages/camera/camera_avfoundation/example/ios/RunnerTests/CameraOrientationTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/CameraPluginInitializeCameraTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/CameraPreviewPauseTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/CameraSessionPresetsTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/CameraSettingsTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/CameraTestUtils.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/FLTCamExposureTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/FLTCamFocusTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/FLTCamSetDeviceOrientationTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/FLTCamSetFlashModeTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/FLTCamZoomTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/PhotoCaptureTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/StreamingTests.swift
This PR prepares for the next big one (`FLTCam` class migration):
1. Extracts a util method for creating a test `FLTCam` instance. After migration, the `FLTCam` constructor is marked with `throws` so it requires some asserts to ignore it in tests
2. Removes dependence on KVO in `StreamingTests`
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/T …
> [camera_avfoundation] Implementation swift migration - part 3

- packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/platform_webview_controller.dart
- packages/webview_flutter/webview_flutter_platform_interface/pubspec.yaml
- packages/webview_flutter/webview_flutter_platform_interface/test/platform_webview_controller_test.dart
Part of https://github.com/flutter/flutter/issues/62464
Platform interface portion for https://github.com/flutter/packages/pull/9024 …
> [webview_flutter_platform_interface] Adds support to set whether to draw the scrollbar

- packages/camera/camera_android_camerax/CHANGELOG.md
- packages/camera/camera_android_camerax/android/src/main/java/io/flutter/plugins/camerax/DeviceOrientationManager.java
- packages/camera/camera_android_camerax/android/src/test/java/io/flutter/plugins/camerax/DeviceOrientationManagerTest.java
- packages/camera/camera_android_camerax/lib/src/surface_texture_rotated_preview.dart
- packages/camera/camera_android_camerax/pubspec.yaml
Replaces usage of [`BroadcastReceiver`](https://developer.android.com/reference/android/content/BroadcastReceiver) (that is registered with the [`ACTION_CONFIGURATION_CHANGED`](https://developer.android.com/reference/android/content/Intent#ACTION_CONFIGURATION_CHANGED) intent) with an [`OrientationEventListener`](https://developer.android.com/reference/android/view/OrientationEventListener) to notify the plugin of changes in device orientation.
Using an `OrientationEventListener` allows the plugin to more regularly to orientation updates, whereas listening to the  `ACTION_CONFIGURATION_CHANGED` only reports changes in device configuration. This is an issue because sometimes, a device changing from a landscape orientation to another landscape orientation is not considered a change in …
> [camera_android_camerax] Swap out `BroadcastReceiver` for `OrientationEventListener`

- packages/video_player/video_player/example/integration_test/video_player_test.dart
- packages/video_player/video_player_web/example/integration_test/video_player_web_test.dart
Skips some tests on web; see https://github.com/flutter/flutter/issues/169219
> [video_player] Skip some integration tests on web

- packages/file_selector/file_selector_macos/CHANGELOG.md
- packages/file_selector/file_selector_macos/example/macos/RunnerTests/RunnerTests.swift
- packages/file_selector/file_selector_macos/macos/file_selector_macos/Sources/file_selector_macos/FileSelectorPlugin.swift
- packages/file_selector/file_selector_macos/pubspec.yaml
file_selector_macos is trying to set [`nameFieldStringValue`](https://developer.apple.com/documentation/appkit/nssavepanel/namefieldstringvalue) for an `NSOpenPanel`. However, `nameFieldStringValue` does not support `NSOpenPanel`, it only supports `NSSavePanel`.
This PR does not set `nameFieldStringValue` if using `NSOpenPanel`. It also updates the tests to verify it works for `NSSavePanel` and not `NSOpenPanel`.
Fixes https://github.com/flutter/flutter/issues/169510. …
> [file_selector_macos] Do not set nameFieldStringValue for NSOpenPanel

- packages/webview_flutter/webview_flutter_wkwebview/darwin/Tests/FrameInfoProxyAPITests.swift
This test was introduced in https://github.com/flutter/packages/pull/8766 to fix a crash when `WKFrameInfo.request` returned nil. It appears that macOS 15.5 fixed `WKFrameInfo.request` so it no longer returns nil and instead returns an empty `URLRequest`. This updates the test to accept either `nil` or an empty `URLRequest`.
Fixes https://github.com/flutter/flutter/issues/169511.
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree- …
> [webview_flutter_wkwebview] Fix `testNilRequest` test for macOS 15.5

- packages/pointer_interceptor/pointer_interceptor_web/CHANGELOG.md
- packages/pointer_interceptor/pointer_interceptor_web/example/integration_test/widget_test.dart
- packages/pointer_interceptor/pointer_interceptor_web/lib/pointer_interceptor_web.dart
- packages/pointer_interceptor/pointer_interceptor_web/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/157920
When the `TextField` is placed above the `HtmlElementView`, it becomes unresponsive on Safari and Firefox. After the investigation, I found that this happens because the underlying `input`/`textarea` loses focus, leading to not listening to the keyboard input.
After some investigation, I found out that calling `preventDefault` on `mousedown` events on `PointerInterceptor` `div` element prevents the `input/textarea` from losing focus.
The same was already done for `SelectionArea` in https://github.com/flutter/flutter/pull/167275
| Before | After |
| :---: | :---: |
| https://input-above-interceptor-bug.web.app | https://input-above-interceptor-fix.web.app |
| <video src="https://github.com/user-attachments/assets/3537d34d-9eb2-4a36-bbcf …
> [pointer_interceptor_web] Fix unresponsive input above PointerInterceptor on Safari and Firefox.

- packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/marker.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/marker_test.dart
This is just the platform interface package part of #8012  …
> [google_maps_flutter_platform_interface] Add a new zIndexInt param to marker and deprecate zIndex 

- packages/go_router/CHANGELOG.md
- packages/go_router/lib/src/route.dart
- packages/go_router/pubspec.yaml
- packages/two_dimensional_scrollables/CHANGELOG.md
- packages/two_dimensional_scrollables/lib/src/common/span.dart
- packages/two_dimensional_scrollables/pubspec.yaml
- packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/types/javascript_message.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/types/load_request_params.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/types/platform_navigation_delegate_creation_params.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/types/platform_webview_controller_creation_params.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/types/platform_webview_cookie_manager_creation_params.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/types/platform_webview_widget_creation_params.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/types/web_resource_error.dart
- packages/webview_flutter/webview_flutter_platform_interface/pubspec.yaml
Usage of `@tool sample` and `@tool snippet` are not rendered in package docs here like they are in flutter/flutter.
[Discord]: …
> [multi] Remove @tool from docs that does not work

- packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/marker.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/marker_test.dart
This assertion fails when using the `copyWith` method.
https://github.com/flutter/packages/blob/007e2f1e468b8e870544c16ce21ad39f97299241/packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/marker.dart#L165 …
> Fix the `zIndex`-related issue in the `copyWith` method.

- packages/google_maps_flutter/google_maps_flutter_ios/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/FGMImageUtils.h
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/FGMImageUtils.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/google_maps_flutter_ios/pubspec.yaml
Fixes analysis failures that fail CI in newer versions of the toolchain. Currently these are surfaced in the Xcode UI, but not the command-line analysis run done in CI.
This unblocks future CI updates.
Fixes https://github.com/flutter/flutter/issues/170354
[CLA]: …
> [google_maps_flutter] Fix iOS analysis for newer Xcode

- packages/pigeon/CHANGELOG.md
- packages/pigeon/CONTRIBUTING.md
- packages/pigeon/example/app/linux/messages.g.cc
- packages/pigeon/example/app/linux/messages.g.h
- packages/pigeon/lib/src/generator_tools.dart
- packages/pigeon/lib/src/gobject/gobject_generator.dart
- packages/pigeon/platform_tests/test_plugin/linux/pigeon/core_tests.gen.cc
- packages/pigeon/platform_tests/test_plugin/linux/pigeon/core_tests.gen.h
- packages/pigeon/pubspec.yaml
- packages/pigeon/test/gobject_generator_test.dart
Adds a custom type identifier to generated gobject headers for the user. Calling fl_value_new_custom_object is now possible with that constant.
This fixes https://github.com/flutter/flutter/issues/156100 …
> [pigeon] Use a const for custom type ids for gobject generated files (#156100)

- packages/go_router/lib/src/match.dart
- packages/go_router/lib/src/route.dart
We plan to export the `internal` attribute from `package:flutter/foundation.dart`.
Currently, `go_router` has files that import both `package:meta/meta.dart` and `package:flutter/foundation.dart`. This causes [lint failures](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8712222978061136193/+/u/run_test.dart_for_flutter_plugins_shard_and_subshard_analyze/stdout) when `foundation` exports `internal`:
```
info - lib/src/match.dart:12:8 - The import of 'package:meta/meta.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/foundation.dart'. Try removing the import directive. - unnecessary_import
info - lib/src/route.dart:10:8 - The import of 'package:meta/meta.dart' is unnecessary because all of the used elements are …
```
> [go_router] Use library prefix for meta

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/Camera.swift
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/DefaultCamera.swift
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation_objc/FLTCam.m
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation_objc/include/camera_avfoundation/FLTCam.h
- packages/camera/camera_avfoundation/pubspec.yaml
This PR migrates a part of `FLTCam` class to Swift.
This PR includes the second chunk:
- `start`
- `stop`
- `close`
- `receivedImageStreamData`
- `reportInitializationState`
- `setExposureMode`
- `setExposureOffset`
- `setExposurePoint`
- `setFocusMode`
- `setFocusPoint`
Some properties of the `FLTCam` have to be temporarily made public so that they are accessible in `DefaultCamera`. …
> [camera_avfoundation] Implementation swift migration - part 5

- packages/camera/camera_android_camerax/CHANGELOG.md
- packages/camera/camera_android_camerax/android/src/main/java/io/flutter/plugins/camerax/PreviewProxyApi.java
- packages/camera/camera_android_camerax/android/src/test/java/io/flutter/plugins/camerax/PreviewTest.java
- packages/camera/camera_android_camerax/pubspec.yaml
Reverts flutter/packages#9360
It uses an API that's not available on `stable`, breaking compilation of the plugin on `stable`.
> Revert "[camera_android_camerax] Force new `Surface` for each `SurfaceRequest`"

- packages/google_sign_in/google_sign_in/CHANGELOG.md
- packages/google_sign_in/google_sign_in/CONTRIBUTING.md
Adds a CONTRIBUTING.md that explains how to configure the example app for manual testing, since we don't currently maintain a central project for testing it.
Also opportunistically fixes a minor latent mistake in an older CHANGELOG entry, so that the next publication will include that fix.
Fixes https://github.com/flutter/flutter/issues/83759
Fixes https://github.com/flutter/flutter/issues/167906 …
> [google_sign_in] Add contributor setup instructions

- packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/legacy_renderer_test.dart
Re: https://github.com/flutter/flutter/issues/171306
This skips a test that has been flaky for a while but now seems to be permanently blocking the tree. Nothing in the code has changed recently that could have caused it to deterministically fail. …
> Skip test to unblock packages

- packages/video_player/video_player_platform_interface/CHANGELOG.md
- packages/video_player/video_player_platform_interface/lib/video_player_platform_interface.dart
- packages/video_player/video_player_platform_interface/pubspec.yaml
- packages/video_player/video_player_platform_interface/test/video_player_web_options_test.dart
This PR adds support for the poster attribute on web by introducing a poster field in VideoPlayerWebOptions. It allows setting a thumbnail image for videos using the native HTML5 poster property, improving the out-of-the-box web experience.
This PR is is the changes to platform_interface for this [one](https://github.com/flutter/packages/pull/8940)
Solve this issue:
https://github.com/flutter/flutter/issues/166232 …
> [video_player] Add poster attribute for html video tag in video_player_platform_interface

- packages/in_app_purchase/in_app_purchase_android/example/integration_test/in_app_purchase_test.dart
Annotate an intentional use of a deprecated method in an integration test, so that it doesn't show up in deprecation audits.
See https://github.com/flutter/flutter/blob/main/docs/infra/Packages-Gardener-Rotation.md#deprecations
> [in_app_purchase] Annotate deprecation in test

- packages/video_player/video_player_avfoundation/CHANGELOG.md
- packages/video_player/video_player_avfoundation/darwin/RunnerTests/VideoPlayerTests.m
- packages/video_player/video_player_avfoundation/darwin/video_player_avfoundation/Sources/video_player_avfoundation/FVPCADisplayLink.m
- packages/video_player/video_player_avfoundation/darwin/video_player_avfoundation/Sources/video_player_avfoundation/FVPTextureBasedVideoPlayer.m
- packages/video_player/video_player_avfoundation/darwin/video_player_avfoundation/Sources/video_player_avfoundation/FVPVideoPlayerPlugin.m
- packages/video_player/video_player_avfoundation/darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPDisplayLink.h
- packages/video_player/video_player_avfoundation/darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPFrameUpdater.h
- packages/video_player/video_player_avfoundation/darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPTextureBasedVideoPlayer.h
- packages/video_player/video_player_avfoundation/darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPVideoPlayerPlugin_Test.h
- packages/video_player/video_player_avfoundation/darwin/video_player_avfoundation/Sources/video_player_avfoundation_macos/FVPCVDisplayLink.m
- packages/video_player/video_player_avfoundation/darwin/video_player_avfoundation/Sources/video_player_avfoundation_macos/FVPCoreVideoDisplayLink.m
- packages/video_player/video_player_avfoundation/pubspec.yaml
Marks the CVDisplayLink-based implementation that was previously used on macOS in all cases with deprecation suppressions, and switches macOS 14+ to share the CADisplayLink-based implementation that is currently used for iOS.
Fixes https://github.com/flutter/flutter/issues/171391
[the auto-formatter]: https://github.com/flutter/packages/blob/main/script/tool/READM …
> [video_player] Use CADisplayLink on macOS 14.0+

- packages/google_sign_in/google_sign_in_android/CHANGELOG.md
- packages/google_sign_in/google_sign_in_android/README.md
- packages/google_sign_in/google_sign_in_android/pubspec.yaml
Since the launch of the new `CredentialManager`-based implementation, there has been user confusion around configuration errors, especially because `CredentialManager` returns what appears to be the wrong error ("canceled") for many configuration errors. Since the plugin can't do anything about that SDK behavior, this at least documents it so that users seeing that behavior are less likely to be misled about what the problem is.
Fixes https://github.com/flutter/flutter/issues/171761 …
> [google_sign_in] Add troubleshooting to Android README

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/example/ios/RunnerTests/FLTCamSetDeviceOrientationTests.swift
- packages/camera/camera_avfoundation/example/ios/RunnerTests/Mocks/MockCamera.swift
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/Camera.swift
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/CameraPlugin.swift
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/DefaultCamera.swift
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation_objc/FLTCam.m
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation_objc/include/camera_avfoundation/FLTCam.h
- packages/camera/camera_avfoundation/pubspec.yaml
This PR migrates the 3rd chunk of `FLTCam` class to Swift:
* `minimumExposureOffset`, `maximumExposureOffset`, `minimumAvailableZoomFactor`, `maximumAvailableZoomFactor`
* `pauseVideoRecording`, `resumeVideoRecording`, `pausePreview`, `resumePreview`
* `setDeviceOrientation`, `lockCaptureOrientation`, `unlockCaptureOrientation`
Some properties of the `FLTCam` have to be temporarily made public so that they are accessible in `DefaultCamera`.
[Contributor …
> [camera_avfoundation] Implementation swift migration - part 6

- packages/rfw/test/argument_decoders_test.dart
This is needed to land https://github.com/flutter/flutter/pull/171916, which updates `NetworkImage.toString()`. Checking against `toString()` is flaky anyways.
[CLA]: …
> [rfw] Update test to not depend on toString()

- packages/quick_actions/quick_actions_android/example/android/app/src/androidTest/java/io/flutter/plugins/quickactionsexample/QuickActionsTest.java
This was temporarily disabled due to https://github.com/flutter/flutter/issues/170141, which should be fixed now.
> [quick_actions] Restore the appShortcutLaunchActivityAfterStarting test in quick_actions_android

- packages/google_sign_in/google_sign_in/CHANGELOG.md
- packages/google_sign_in/google_sign_in/MIGRATION.md
- packages/google_sign_in/google_sign_in/lib/google_sign_in.dart
- packages/google_sign_in/google_sign_in/pubspec.yaml
Adds discussion of the new exception flows to the migration guide.
Also makes the API comment discussion of initialize more thorough
Fixes https://github.com/flutter/flutter/issues/171704
Fixes https://github.com/flutter/flutter/issues/171746
[CLA]: …
> [google_sign_in] Add exception info to migration guide

- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/darwin/Tests/ProxyAPIRegistrarTests.swift
- packages/webview_flutter/webview_flutter_wkwebview/darwin/webview_flutter_wkwebview/Sources/webview_flutter_wkwebview/ProxyAPIRegistrar.swift
- packages/webview_flutter/webview_flutter_wkwebview/example/ios/Runner.xcodeproj/project.pbxproj
- packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml
The assertion caused a crash with hot restart if a Flutter method call happened at the same time. Changing this to `NSLog` also allows logging failures when in release mode.
Fixes https://github.com/flutter/flutter/issues/170643 …
> [webview_flutter_wkwebview] Replace Flutter method failure assertion with nslog

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/DefaultCamera.swift
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation_objc/FLTCam.m
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation_objc/include/camera_avfoundation/FLTCam.h
- packages/camera/camera_avfoundation/pubspec.yaml
This PR migrates the 4th chunk of `FLTCam` class to Swift:
* `setZoomLevel`
* `setFlashMode`
* `flutterErrorFromNSError`
Some properties of the `FLTCam` have to be temporarily made public so that they are accessible in `DefaultCamera`. …
> [camera_avfoundation] Implementation swift migration - part 7

- .github/PULL_REQUEST_TEMPLATE.md
Apparently line wrapping in this file is preserved in the HTML display, which I wasn't expecting, and makes the note look terrible. This removes it so that it will wrap based on the UI width.
> Fix Gemini note wrapping

- packages/two_dimensional_scrollables/CHANGELOG.md
- packages/two_dimensional_scrollables/lib/src/table_view/table.dart
- packages/two_dimensional_scrollables/pubspec.yaml
- packages/two_dimensional_scrollables/test/table_view/table_test.dart
Fixes https://github.com/flutter/flutter/issues/167813
The cache extent was not being applied to leading children, only trailing.
This fixes that. 
Will check TreeView to see if the same issue applies after this. …
> [two_dimensional_scrollables] Fix missing leading cache extent for TableView

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/DefaultCamera.swift
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation_objc/FLTCam.m
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation_objc/include/camera_avfoundation/FLTCam.h
- packages/camera/camera_avfoundation/pubspec.yaml
This PR migrates the 5th chunk of `FLTCam` class to Swift:
* `setVideoFormat`
* `stopVideoRecording`
* `stopImageStream`
* stopping accelerometer updates (`deinit`)
* `setDescriptionWhileRecording`
* `createConnection` (adds Swift implementation, FLTCam still depends on private non-static implementation)
NOTE:  `setDescriptionWhileRecording` is migrated close to verbatim, the [issue](https://github.com/flutter/flutter/issues/168134) affecting it remains.
Some properties of the `FLTCam` have to be temporarily made public so that they are accessible in `DefaultCamera`.
[^1]: Regular contributors who have …
> [camera_avfoundation] Implementation swift migration - part 8

- .gemini/config.yaml
Set an initial ignore list for Gemini reviews that includes the two Flutter version pins. This is an experiment to see if having a PR that contains only ignored files will be ignored by Gemini, so that we don't end up with [this comment](https://github.com/flutter/packages/pull/9646#pullrequestreview-3033902418) on every roll.
> Have Gemini ignore Flutter version pin

- packages/google_sign_in/google_sign_in_ios/CHANGELOG.md
- packages/google_sign_in/google_sign_in_ios/darwin/Tests/GoogleSignInTests.m
- packages/google_sign_in/google_sign_in_ios/darwin/google_sign_in_ios.podspec
- packages/google_sign_in/google_sign_in_ios/darwin/google_sign_in_ios/Package.swift
- packages/google_sign_in/google_sign_in_ios/darwin/google_sign_in_ios/Sources/google_sign_in_ios/FLTGoogleSignInPlugin.m
- packages/google_sign_in/google_sign_in_ios/pubspec.yaml
Updates the dependency on the GoogleSignIn iOS SDK to the recently released 9.0. Some specific benefits include:
- Allows wiring up the nonce parameter on iOS, which was plumbed most of the way through already since the PR had landed upstream when nonce was added to `google_sign_in`, but not fully connected since it wasn't released.
- Avoids transitive dependency conflicts with plugins that use AppAuth 2.x.
Fixes https://github.com/flutter/flutter/issues/172453 Finishes https://github.com/flutter/flutter/issues/85439 for iOS
**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the …
> [google_sign_in] Update to GoogleSignIn-iOS 9

- packages/google_sign_in/google_sign_in_android/CHANGELOG.md
- packages/google_sign_in/google_sign_in_android/README.md
- packages/google_sign_in/google_sign_in_android/pubspec.yaml
When I wrote the docs I thought that Firebase would always include a web OAuth client ID, but it appears that this is not always the case (e.g.,
https://stackoverflow.com/questions/55572583/google-services-json-missing-client-type-3) so this adds more docs about what is required for this to work correctly.
Also adds a note that a missing ID error could be due to incorrect gradle configuration, as that's not necessarily clear from the Firebase docs.
Fixes https://github.com/flutter/flutter/issues/172073 …
> [google_sign_in] Add more serverClientId info to README

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/example/ios/RunnerTests/PhotoCaptureTests.swift
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/CameraPlugin.swift
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/DefaultCamera.swift
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/QueueUtils.swift
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation_objc/FLTCam.m
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation_objc/QueueUtils.m
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation_objc/include/camera_avfoundation/FLTCam.h
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation_objc/include/camera_avfoundation/QueueUtils.h
- packages/camera/camera_avfoundation/pubspec.yaml
This PR migrates the 7th chunk of `FLTCam` class to Swift:
* `captureToFile`
* `getTemporaryFilePath`
We can also finally switch to Swift interface for dispatch queue specific because all usages are now in Swift.
**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please …
> [camera_avfoundation] Implementation swift migration - part 10

- packages/video_player/video_player_android/CHANGELOG.md
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/HttpVideoAsset.java
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/Messages.java
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/RtspVideoAsset.java
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoAsset.java
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerEventCallbacks.java
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
- packages/video_player/video_player_android/android/src/test/java/io/flutter/plugins/videoplayer/VideoAssetTest.java
- packages/video_player/video_player_android/android/src/test/java/io/flutter/plugins/videoplayer/VideoPlayerEventCallbacksTest.java
- packages/video_player/video_player_android/lib/src/android_video_player.dart
- packages/video_player/video_player_android/lib/src/messages.g.dart
- packages/video_player/video_player_android/pigeons/messages.dart
- packages/video_player/video_player_android/pubspec.yaml
- packages/video_player/video_player_android/test/android_video_player_test.dart
- packages/video_player/video_player_android/test/android_video_player_test.mocks.dart
Moves some logic from native code to Dart:
- User-Agent header -> ExoPlayer user agent extraction logic (with TODOs for future improvements, based on implementation issues/questions I noticed while converting it).
- Asset -> URL lookup.
- Conversion of buffer position to the buffer range list required for the Dart event stream.
Also converts video format hint from strings to enums, which was missed in earlier Pigeon conversions. Using strings was the pre-Pigeon way of handling this kind of thing.
Part of https://github.com/flutter/flutter/issues/172763
**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as …
> [video_player] Move more Java logic to Dart

- packages/in_app_purchase/in_app_purchase_storekit/example/lib/main.dart
```dart
void main() {
WidgetsFlutterBinding.ensureInitialized();
// When using the Android plugin directly it is mandatory to register
// the plugin as default instance as part of initializing the app.
InAppPurchaseStoreKitPlatform.registerPlatform();
```
```dart
void main() {
WidgetsFlutterBinding.ensureInitialized();
// When using the StoreKit plugin directly it is mandatory to register
// the plugin as default instance as part of initializing the app.
InAppPurchaseStoreKitPlatform.registerPlatform();
```
Closes https://github.com/flutter/flutter/issues/159623
[^1]: Regular contributors who have demonstrated familiarity with the repository guidelines only need to comment if the PR is not auto-exempted …
> [in_app_purchase_storekit] Updated comment 

- .ci.yaml
Extending timeout on `Linux_android android_build_all_packages` to prevent further timeouts to improve dev velocity. This is a temporary solution.
Partially Addresses https://github.com/flutter/flutter/issues/173066
**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated …
> Extending Timeout on `Linux_android android_build_all_packages *`

- packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/platform_webview_controller.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/types/load_file_params.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/types/types.dart
- packages/webview_flutter/webview_flutter_platform_interface/pubspec.yaml
- packages/webview_flutter/webview_flutter_platform_interface/test/platform_webview_controller_test.dart
[https://github.com/flutter/flutter/issues/136479](https://github.com/flutter/flutter/issues/136479)
These are the platform interface changes, after the main PR was approved.
[https://github.com/flutter/packages/pull/8787](https://github.com/flutter/packages/pull/8787)
What was changed:
* Added `LoadFileParams` to specify parameters for loading local HTML pages.
* `PlatformWebViewController` class extended with the new method `loadFileWithParams(LoadFileParams)`.
* Unit tests for the new functionality of the `PlatformWebViewController` were added. …
> [webview_flutter_platform_interface] Provide flexible API for loading local HTML files

- AGENTS.md
- script/tool/lib/src/common/file_filters.dart
- script/tool/test/xcode_analyze_command_test.dart
First attempt at an AGENTS.md file to make Jules more effective at creating PRs.
I started with an initial draft, then iterated based on feedback from Gemini Code Assist, taking most of its suggestions (under the theory that it has more examples of AGENTS.md files in its model than I do), but removing some hallucinations.
I was going to put the "Agent Environment Setup" in a separate file, so that people could manually add it to their Jules configuration, but Gemini found that file and thought it should be in AGENTS.md. I'm curious to see if that will work well enough that we don't each need to do the manual one-time configuration. If it doesn't work, we can move it later.
🤷🏻
> Add an initial AGENTS.md

- packages/interactive_media_ads/CHANGELOG.md
- packages/interactive_media_ads/android/src/main/kotlin/dev/flutter/packages/interactive_media_ads/AdsRequestProxyApi.kt
- packages/interactive_media_ads/ios/interactive_media_ads/Sources/interactive_media_ads/AdsRequestProxyAPIDelegate.swift
- packages/interactive_media_ads/lib/src/android/android_ads_loader.dart
- packages/interactive_media_ads/pubspec.yaml
- packages/interactive_media_ads/test/android/ads_loader_test.dart
> [interactive_media_ads] Fixes setting adsresponse on Android

- .ci/targets/macos_repo_checks.yaml
Xcode 26 is showing deprecation usage as warnings: https://github.com/flutter/flutter/issues/170437. These warnings are causing `podspec-check` to fail as these warnings are being treated as errors.
To unblock testing Xcode 26 in CI, exclude the existing `exclude_xcode_deprecation` packages from the podspec check command.
Currently used here:
https://github.com/flutter/packages/blob/83ae18a4faf6cbd18138d6fe7a20859a28b84166/.ci/targets/ios_platform_tests.yaml#L21
https://github.com/flutter/packages/blob/83ae18a4faf6cbd18138d6fe7a20859a28b84166/.ci/targets/macos_platform_tests.yaml#L18
This isn't a perfect solution, as the podspec check will find more issues than just deprecation warnings (Swift 6 warnings, [for example](https://github.com/flutter/flutter/issues/170439)), and this will …
> [ci] Exclude packages using deprecated APIs from the pod linter check

- packages/webview_flutter/webview_flutter_android/CHANGELOG.md
- packages/webview_flutter/webview_flutter_android/example/pubspec.yaml
- packages/webview_flutter/webview_flutter_android/lib/src/android_webview_controller.dart
- packages/webview_flutter/webview_flutter_android/pubspec.yaml
- packages/webview_flutter/webview_flutter_android/test/android_webview_controller_test.dart
- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/example/pubspec.yaml
- packages/webview_flutter/webview_flutter_wkwebview/lib/src/webkit_webview_controller.dart
- packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml
- packages/webview_flutter/webview_flutter_wkwebview/test/webkit_webview_controller_test.dart
The `readAccessURLProvider` property has been added to the `WebKitWebViewControllerCreationParams` class. This function allows customization of the path to associated resources when loading a local HTML page using `loadFile` on iOS.
Fixes https://github.com/flutter/flutter/issues/136479
The native `WKWebView` takes two arguments when loading local HTML pages:
1. **The file URL** – The local HTML file to be loaded.
2. **The read access URL** – A file or directory that `WKWebView` can access (e.g., .css, .js files).
Currently, the Flutter implementation always sets the parent folder of the specified HTML file as the read access directory. This behavior is not configurable, which limits how local web content can be structured.
For example, the following structure does not work because the …
> [webview_flutter_wkwebview] Extended Web View API on iOS to add flexibility when working with local HTML content

- packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/platform_interface/google_maps_flutter_platform.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/advanced_marker.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/bitmap.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/map_configuration.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/marker.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/types.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/utils/map_configuration_serialization.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/platform_interface/google_maps_flutter_platform_test.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/advanced_marker_test.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/bitmap_test.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/map_configuration_test.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/utils/map_configuration_serialization_test.dart
This PR adds Advanced markers support to the platform interface of `google_maps_flutter`.
Approved combined PR: #7882
Issue: [#155526](https://github.com/flutter/flutter/issues/155526) …
> [google_maps_flutter_platform_interface] Add Advanced markers support

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/example/ios/RunnerTests/StreamingTests.swift
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/DefaultCamera.swift
- packages/camera/camera_avfoundation/pubspec.yaml
In `captureOutput`, we receive both pixel and audio buffers (audio only during recording with audio enabled, when streaming alone is enabled, everything works correctly). Currently, the streaming part of this method doesn't handle non-pixel buffers properly, causing a crash because of force unwrapping of nil.
This PR changes the logic to ignore non-pixel buffers for purposes of streaming.
Resolves https://github.com/flutter/flutter/issues/172894.
**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from …
> [camera_avfoundation] Fix crash when streaming while recording

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation/DefaultCamera.swift
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation_objc/FLTCam.m
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation_objc/include/camera_avfoundation/FLTCam.h
- packages/camera/camera_avfoundation/ios/camera_avfoundation/Sources/camera_avfoundation_objc/include/camera_avfoundation/FLTCam_Test.h
- packages/camera/camera_avfoundation/pubspec.yaml
Resolves https://github.com/flutter/flutter/issues/170439. This PR migrates the last one of the problematic methods (`startImageStream`) to Switft, which resolves the issue.
This PR migrates the 8th chunk of `FLTCam` class to Swift:
* `startImageStream`
* `setUpCaptureSessionForAudioIfNeeded`
* `reportErrorMessage` (ObjC implementation removal)
Some properties of the FLTCam have to be temporarily made public so that they are accessible in DefaultCamera.
**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code …
> [camera_avfoundation] Implementation swift migration - part 11

- packages/interactive_media_ads/CHANGELOG.md
- packages/interactive_media_ads/README.md
- packages/interactive_media_ads/android/src/main/kotlin/dev/flutter/packages/interactive_media_ads/AdsRequestProxyApi.kt
- packages/interactive_media_ads/example/android/app/build.gradle
- packages/interactive_media_ads/ios/interactive_media_ads/Sources/interactive_media_ads/AdsRequestProxyAPIDelegate.swift
- packages/interactive_media_ads/pubspec.yaml
Get started for IMA on Android includes enabling desugaring: https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/get-started#2.-add-the-ima-sdk-to-your-project
This updates the README for the plugin with the same information.
**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's …
> [interactive_media_ads] Updates `README` with information about enabling desugaring on Android

- packages/go_router/test/go_router_test.dart
This test was failing in https://github.com/flutter/flutter/pull/152330. That PR adds a PopScope inside of nested Navigators. When a back gesture happens, the PopScope takes 1 frame to rerender and update the state of its pop handling. The test was breaking because it performed two back gestures in one frame. Putting a pump in between them fixes it when the PR is  merged (and works fine without the PR too).
It took me so many hours to realize this one little pump was the fix I needed 😭 .
> Handle automatic PopScope

- .gemini/styleguide.md
Adds a section to the review agent configuration to try to get it to stop leaving comments like [this one](https://github.com/flutter/packages/pull/9878#discussion_r2296811190) on federated plugin PRs that are following our standard, documented process.
> Try to convince GCA to stop complaining about `dependency_overrides`

- packages/camera/camera/README.md
https://github.com/flutter/packages/pull/9853 bumped it to 23, so updating the README.
[^1]: Regular contributors who have demonstrated familiarity with the repository guidelines only need …
> [camera_android_camerax] Update Android minimum SDK version

- packages/google_fonts/CONTRIBUTING.md
- packages/google_fonts/generator/README.md
Apply feedback from https://github.com/flutter/packages/pull/9895
Note: the `families_diff` file created by the generator should suffice in writing CHANGELOG updates
[^1]: Regular …
> [google_fonts] Improve CONTRIBUTING and generator README

- packages/url_launcher/url_launcher_android/CHANGELOG.md
- packages/url_launcher/url_launcher_android/android/build.gradle
- packages/url_launcher/url_launcher_android/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java
- packages/url_launcher/url_launcher_android/example/lib/main.dart
- packages/url_launcher/url_launcher_android/example/pubspec.yaml
- packages/url_launcher/url_launcher_android/lib/src/messages.g.dart
- packages/url_launcher/url_launcher_android/lib/url_launcher_android.dart
- packages/url_launcher/url_launcher_android/pubspec.yaml
This re-lands the `url_launcher_android` portion of https://github.com/flutter/packages/pull/9851, which was reverted in https://github.com/flutter/packages/pull/9986, but with the missing min SDK update this time.
Part of https://github.com/flutter/flutter/issues/170807
[the auto-formatter]: https://github.com/flutter/packages/blob/main/script/tool/README.md#form …
> [url_launcher] Re-remove Android API<24 support

- packages/file_selector/file_selector/CHANGELOG.md
- packages/file_selector/file_selector/README.md
- packages/file_selector/file_selector/example/lib/open_image_page.dart
- packages/file_selector/file_selector/example/lib/open_multiple_images_page.dart
- packages/file_selector/file_selector/example/lib/open_text_page.dart
- packages/file_selector/file_selector/pubspec.yaml
Fixes the example app to work on iOS; unlike the other platforms, iOS doesn't support `extensions`, so `uniformTypeIdentifiers` must also be set. This should have been done when we endorsed the iOS implementation package, but I forgot.
Fixes https://github.com/flutter/flutter/issues/175381 …
> [file_selector] Fix example on iOS

- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/media/ImageStreamReaderUtils.java
Remove references to [mlkit/android/vision-quickstart](https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart) as per my findings in https://github.com/flutter/packages/pull/10022#discussion_r2369586533.
**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which …
> [camera_android] Remove references to third party `googlesamples/mlkit` code

- script/configs/exclude_integration_android_legacy_emulator.yaml
Now that the legacy emulators are API 31, not 22, these exclusions are stale.
Fixes https://github.com/flutter/flutter/issues/136824
Fixes https://github.com/flutter/flutter/issues/136823
> [ci] Re-enable all Android legacy emulator tests

- packages/google_sign_in/google_sign_in/example/lib/src/web_wrapper.dart
Flutter has already migrated from dart:js_util to dart:js_interop (which is unsupported by dart2wasm). This migrates a remaining reference to js_util which will be broken when dart2wasm drops the library entirely.
> [google_sign_in] Remove references to dart:js_util

- packages/espresso/CHANGELOG.md
- packages/espresso/android/build.gradle
- packages/espresso/pubspec.yaml
Update minimum flutter version to 3.35 to force a minimum AGP version to something that requires java 17.
part of https://github.com/flutter/flutter/issues/176027
> [espresso] updates build files to use JVM 17 

- packages/webview_flutter/webview_flutter_android/CHANGELOG.md
- packages/webview_flutter/webview_flutter_android/README.md
- packages/webview_flutter/webview_flutter_android/example/lib/readme_excerpts.dart
- packages/webview_flutter/webview_flutter_android/pubspec.yaml
Adds a section to `webview_flutter_android`'s README explaining how to enable geolocation.
Fixes https://github.com/flutter/flutter/issues/173279
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/ …
> [webview_flutter] Add Android geolocation README
